// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: assets/assets_service.proto

// Protobuf Java Version: 3.25.5
package grpc.tradeapi.v1.assets;

public interface ExchangesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.tradeapi.v1.assets.ExchangesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Информация о бирже
   * </pre>
   *
   * <code>repeated .grpc.tradeapi.v1.assets.Exchange exchanges = 1;</code>
   */
  java.util.List<grpc.tradeapi.v1.assets.Exchange> 
      getExchangesList();
  /**
   * <pre>
   * Информация о бирже
   * </pre>
   *
   * <code>repeated .grpc.tradeapi.v1.assets.Exchange exchanges = 1;</code>
   */
  grpc.tradeapi.v1.assets.Exchange getExchanges(int index);
  /**
   * <pre>
   * Информация о бирже
   * </pre>
   *
   * <code>repeated .grpc.tradeapi.v1.assets.Exchange exchanges = 1;</code>
   */
  int getExchangesCount();
  /**
   * <pre>
   * Информация о бирже
   * </pre>
   *
   * <code>repeated .grpc.tradeapi.v1.assets.Exchange exchanges = 1;</code>
   */
  java.util.List<? extends grpc.tradeapi.v1.assets.ExchangeOrBuilder> 
      getExchangesOrBuilderList();
  /**
   * <pre>
   * Информация о бирже
   * </pre>
   *
   * <code>repeated .grpc.tradeapi.v1.assets.Exchange exchanges = 1;</code>
   */
  grpc.tradeapi.v1.assets.ExchangeOrBuilder getExchangesOrBuilder(
      int index);
}
