// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: assets/assets_service.proto

// Protobuf Java Version: 3.25.5
package grpc.tradeapi.v1.assets;

public interface GetAssetRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.tradeapi.v1.assets.GetAssetRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Символ инструмента
   * </pre>
   *
   * <code>string symbol = 1;</code>
   * @return The symbol.
   */
  java.lang.String getSymbol();
  /**
   * <pre>
   * Символ инструмента
   * </pre>
   *
   * <code>string symbol = 1;</code>
   * @return The bytes for symbol.
   */
  com.google.protobuf.ByteString
      getSymbolBytes();

  /**
   * <pre>
   * ID аккаунта для которого будет подбираться информация по инструменту
   * </pre>
   *
   * <code>string account_id = 2;</code>
   * @return The accountId.
   */
  java.lang.String getAccountId();
  /**
   * <pre>
   * ID аккаунта для которого будет подбираться информация по инструменту
   * </pre>
   *
   * <code>string account_id = 2;</code>
   * @return The bytes for accountId.
   */
  com.google.protobuf.ByteString
      getAccountIdBytes();
}
