// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: assets/assets_service.proto

// Protobuf Java Version: 3.25.5
package grpc.tradeapi.v1.assets;

/**
 * <pre>
 * Торговые параметры инструмента
 * </pre>
 *
 * Protobuf type {@code grpc.tradeapi.v1.assets.GetAssetParamsResponse}
 */
public final class GetAssetParamsResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:grpc.tradeapi.v1.assets.GetAssetParamsResponse)
    GetAssetParamsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetAssetParamsResponse.newBuilder() to construct.
  private GetAssetParamsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetAssetParamsResponse() {
    symbol_ = "";
    accountId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetAssetParamsResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.tradeapi.v1.assets.AssetsServiceOuterClass.internal_static_grpc_tradeapi_v1_assets_GetAssetParamsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.tradeapi.v1.assets.AssetsServiceOuterClass.internal_static_grpc_tradeapi_v1_assets_GetAssetParamsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.tradeapi.v1.assets.GetAssetParamsResponse.class, grpc.tradeapi.v1.assets.GetAssetParamsResponse.Builder.class);
  }

  private int bitField0_;
  public static final int SYMBOL_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object symbol_ = "";
  /**
   * <pre>
   * Символ инструмента
   * </pre>
   *
   * <code>string symbol = 1;</code>
   * @return The symbol.
   */
  @java.lang.Override
  public java.lang.String getSymbol() {
    java.lang.Object ref = symbol_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      symbol_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Символ инструмента
   * </pre>
   *
   * <code>string symbol = 1;</code>
   * @return The bytes for symbol.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSymbolBytes() {
    java.lang.Object ref = symbol_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      symbol_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ACCOUNT_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object accountId_ = "";
  /**
   * <pre>
   * ID аккаунта для которого подбираются торговые параметры
   * </pre>
   *
   * <code>string account_id = 2;</code>
   * @return The accountId.
   */
  @java.lang.Override
  public java.lang.String getAccountId() {
    java.lang.Object ref = accountId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      accountId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * ID аккаунта для которого подбираются торговые параметры
   * </pre>
   *
   * <code>string account_id = 2;</code>
   * @return The bytes for accountId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAccountIdBytes() {
    java.lang.Object ref = accountId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      accountId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TRADEABLE_FIELD_NUMBER = 3;
  private boolean tradeable_ = false;
  /**
   * <pre>
   * Доступны ли торговые операции
   * </pre>
   *
   * <code>bool tradeable = 3;</code>
   * @return The tradeable.
   */
  @java.lang.Override
  public boolean getTradeable() {
    return tradeable_;
  }

  public static final int LONGABLE_FIELD_NUMBER = 4;
  private grpc.tradeapi.v1.assets.Longable longable_;
  /**
   * <pre>
   * Доступны ли операции в Лонг 
   * </pre>
   *
   * <code>.grpc.tradeapi.v1.assets.Longable longable = 4;</code>
   * @return Whether the longable field is set.
   */
  @java.lang.Override
  public boolean hasLongable() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Доступны ли операции в Лонг 
   * </pre>
   *
   * <code>.grpc.tradeapi.v1.assets.Longable longable = 4;</code>
   * @return The longable.
   */
  @java.lang.Override
  public grpc.tradeapi.v1.assets.Longable getLongable() {
    return longable_ == null ? grpc.tradeapi.v1.assets.Longable.getDefaultInstance() : longable_;
  }
  /**
   * <pre>
   * Доступны ли операции в Лонг 
   * </pre>
   *
   * <code>.grpc.tradeapi.v1.assets.Longable longable = 4;</code>
   */
  @java.lang.Override
  public grpc.tradeapi.v1.assets.LongableOrBuilder getLongableOrBuilder() {
    return longable_ == null ? grpc.tradeapi.v1.assets.Longable.getDefaultInstance() : longable_;
  }

  public static final int SHORTABLE_FIELD_NUMBER = 5;
  private grpc.tradeapi.v1.assets.Shortable shortable_;
  /**
   * <pre>
   * Доступны ли операции в Шорт
   * </pre>
   *
   * <code>.grpc.tradeapi.v1.assets.Shortable shortable = 5;</code>
   * @return Whether the shortable field is set.
   */
  @java.lang.Override
  public boolean hasShortable() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * Доступны ли операции в Шорт
   * </pre>
   *
   * <code>.grpc.tradeapi.v1.assets.Shortable shortable = 5;</code>
   * @return The shortable.
   */
  @java.lang.Override
  public grpc.tradeapi.v1.assets.Shortable getShortable() {
    return shortable_ == null ? grpc.tradeapi.v1.assets.Shortable.getDefaultInstance() : shortable_;
  }
  /**
   * <pre>
   * Доступны ли операции в Шорт
   * </pre>
   *
   * <code>.grpc.tradeapi.v1.assets.Shortable shortable = 5;</code>
   */
  @java.lang.Override
  public grpc.tradeapi.v1.assets.ShortableOrBuilder getShortableOrBuilder() {
    return shortable_ == null ? grpc.tradeapi.v1.assets.Shortable.getDefaultInstance() : shortable_;
  }

  public static final int LONG_RISK_RATE_FIELD_NUMBER = 6;
  private com.google.type.Decimal longRiskRate_;
  /**
   * <pre>
   * Ставка риска для операции в Лонг
   * </pre>
   *
   * <code>.google.type.Decimal long_risk_rate = 6;</code>
   * @return Whether the longRiskRate field is set.
   */
  @java.lang.Override
  public boolean hasLongRiskRate() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <pre>
   * Ставка риска для операции в Лонг
   * </pre>
   *
   * <code>.google.type.Decimal long_risk_rate = 6;</code>
   * @return The longRiskRate.
   */
  @java.lang.Override
  public com.google.type.Decimal getLongRiskRate() {
    return longRiskRate_ == null ? com.google.type.Decimal.getDefaultInstance() : longRiskRate_;
  }
  /**
   * <pre>
   * Ставка риска для операции в Лонг
   * </pre>
   *
   * <code>.google.type.Decimal long_risk_rate = 6;</code>
   */
  @java.lang.Override
  public com.google.type.DecimalOrBuilder getLongRiskRateOrBuilder() {
    return longRiskRate_ == null ? com.google.type.Decimal.getDefaultInstance() : longRiskRate_;
  }

  public static final int LONG_COLLATERAL_FIELD_NUMBER = 7;
  private com.google.type.Money longCollateral_;
  /**
   * <pre>
   * Сумма обеспечения для поддержания позиции Лонг
   * </pre>
   *
   * <code>.google.type.Money long_collateral = 7;</code>
   * @return Whether the longCollateral field is set.
   */
  @java.lang.Override
  public boolean hasLongCollateral() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <pre>
   * Сумма обеспечения для поддержания позиции Лонг
   * </pre>
   *
   * <code>.google.type.Money long_collateral = 7;</code>
   * @return The longCollateral.
   */
  @java.lang.Override
  public com.google.type.Money getLongCollateral() {
    return longCollateral_ == null ? com.google.type.Money.getDefaultInstance() : longCollateral_;
  }
  /**
   * <pre>
   * Сумма обеспечения для поддержания позиции Лонг
   * </pre>
   *
   * <code>.google.type.Money long_collateral = 7;</code>
   */
  @java.lang.Override
  public com.google.type.MoneyOrBuilder getLongCollateralOrBuilder() {
    return longCollateral_ == null ? com.google.type.Money.getDefaultInstance() : longCollateral_;
  }

  public static final int SHORT_RISK_RATE_FIELD_NUMBER = 8;
  private com.google.type.Decimal shortRiskRate_;
  /**
   * <pre>
   * Ставка риска для операции в Шорт
   * </pre>
   *
   * <code>.google.type.Decimal short_risk_rate = 8;</code>
   * @return Whether the shortRiskRate field is set.
   */
  @java.lang.Override
  public boolean hasShortRiskRate() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <pre>
   * Ставка риска для операции в Шорт
   * </pre>
   *
   * <code>.google.type.Decimal short_risk_rate = 8;</code>
   * @return The shortRiskRate.
   */
  @java.lang.Override
  public com.google.type.Decimal getShortRiskRate() {
    return shortRiskRate_ == null ? com.google.type.Decimal.getDefaultInstance() : shortRiskRate_;
  }
  /**
   * <pre>
   * Ставка риска для операции в Шорт
   * </pre>
   *
   * <code>.google.type.Decimal short_risk_rate = 8;</code>
   */
  @java.lang.Override
  public com.google.type.DecimalOrBuilder getShortRiskRateOrBuilder() {
    return shortRiskRate_ == null ? com.google.type.Decimal.getDefaultInstance() : shortRiskRate_;
  }

  public static final int SHORT_COLLATERAL_FIELD_NUMBER = 9;
  private com.google.type.Money shortCollateral_;
  /**
   * <pre>
   * Сумма обеспечения для поддержания позиции Шорт
   * </pre>
   *
   * <code>.google.type.Money short_collateral = 9;</code>
   * @return Whether the shortCollateral field is set.
   */
  @java.lang.Override
  public boolean hasShortCollateral() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <pre>
   * Сумма обеспечения для поддержания позиции Шорт
   * </pre>
   *
   * <code>.google.type.Money short_collateral = 9;</code>
   * @return The shortCollateral.
   */
  @java.lang.Override
  public com.google.type.Money getShortCollateral() {
    return shortCollateral_ == null ? com.google.type.Money.getDefaultInstance() : shortCollateral_;
  }
  /**
   * <pre>
   * Сумма обеспечения для поддержания позиции Шорт
   * </pre>
   *
   * <code>.google.type.Money short_collateral = 9;</code>
   */
  @java.lang.Override
  public com.google.type.MoneyOrBuilder getShortCollateralOrBuilder() {
    return shortCollateral_ == null ? com.google.type.Money.getDefaultInstance() : shortCollateral_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(symbol_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, symbol_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(accountId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, accountId_);
    }
    if (tradeable_ != false) {
      output.writeBool(3, tradeable_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(4, getLongable());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(5, getShortable());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(6, getLongRiskRate());
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeMessage(7, getLongCollateral());
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeMessage(8, getShortRiskRate());
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      output.writeMessage(9, getShortCollateral());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(symbol_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, symbol_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(accountId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, accountId_);
    }
    if (tradeable_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, tradeable_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getLongable());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getShortable());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getLongRiskRate());
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getLongCollateral());
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getShortRiskRate());
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, getShortCollateral());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.tradeapi.v1.assets.GetAssetParamsResponse)) {
      return super.equals(obj);
    }
    grpc.tradeapi.v1.assets.GetAssetParamsResponse other = (grpc.tradeapi.v1.assets.GetAssetParamsResponse) obj;

    if (!getSymbol()
        .equals(other.getSymbol())) return false;
    if (!getAccountId()
        .equals(other.getAccountId())) return false;
    if (getTradeable()
        != other.getTradeable()) return false;
    if (hasLongable() != other.hasLongable()) return false;
    if (hasLongable()) {
      if (!getLongable()
          .equals(other.getLongable())) return false;
    }
    if (hasShortable() != other.hasShortable()) return false;
    if (hasShortable()) {
      if (!getShortable()
          .equals(other.getShortable())) return false;
    }
    if (hasLongRiskRate() != other.hasLongRiskRate()) return false;
    if (hasLongRiskRate()) {
      if (!getLongRiskRate()
          .equals(other.getLongRiskRate())) return false;
    }
    if (hasLongCollateral() != other.hasLongCollateral()) return false;
    if (hasLongCollateral()) {
      if (!getLongCollateral()
          .equals(other.getLongCollateral())) return false;
    }
    if (hasShortRiskRate() != other.hasShortRiskRate()) return false;
    if (hasShortRiskRate()) {
      if (!getShortRiskRate()
          .equals(other.getShortRiskRate())) return false;
    }
    if (hasShortCollateral() != other.hasShortCollateral()) return false;
    if (hasShortCollateral()) {
      if (!getShortCollateral()
          .equals(other.getShortCollateral())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SYMBOL_FIELD_NUMBER;
    hash = (53 * hash) + getSymbol().hashCode();
    hash = (37 * hash) + ACCOUNT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getAccountId().hashCode();
    hash = (37 * hash) + TRADEABLE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getTradeable());
    if (hasLongable()) {
      hash = (37 * hash) + LONGABLE_FIELD_NUMBER;
      hash = (53 * hash) + getLongable().hashCode();
    }
    if (hasShortable()) {
      hash = (37 * hash) + SHORTABLE_FIELD_NUMBER;
      hash = (53 * hash) + getShortable().hashCode();
    }
    if (hasLongRiskRate()) {
      hash = (37 * hash) + LONG_RISK_RATE_FIELD_NUMBER;
      hash = (53 * hash) + getLongRiskRate().hashCode();
    }
    if (hasLongCollateral()) {
      hash = (37 * hash) + LONG_COLLATERAL_FIELD_NUMBER;
      hash = (53 * hash) + getLongCollateral().hashCode();
    }
    if (hasShortRiskRate()) {
      hash = (37 * hash) + SHORT_RISK_RATE_FIELD_NUMBER;
      hash = (53 * hash) + getShortRiskRate().hashCode();
    }
    if (hasShortCollateral()) {
      hash = (37 * hash) + SHORT_COLLATERAL_FIELD_NUMBER;
      hash = (53 * hash) + getShortCollateral().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.tradeapi.v1.assets.GetAssetParamsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.tradeapi.v1.assets.GetAssetParamsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.tradeapi.v1.assets.GetAssetParamsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.tradeapi.v1.assets.GetAssetParamsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.tradeapi.v1.assets.GetAssetParamsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.tradeapi.v1.assets.GetAssetParamsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.tradeapi.v1.assets.GetAssetParamsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.tradeapi.v1.assets.GetAssetParamsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static grpc.tradeapi.v1.assets.GetAssetParamsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static grpc.tradeapi.v1.assets.GetAssetParamsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.tradeapi.v1.assets.GetAssetParamsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.tradeapi.v1.assets.GetAssetParamsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.tradeapi.v1.assets.GetAssetParamsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Торговые параметры инструмента
   * </pre>
   *
   * Protobuf type {@code grpc.tradeapi.v1.assets.GetAssetParamsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:grpc.tradeapi.v1.assets.GetAssetParamsResponse)
      grpc.tradeapi.v1.assets.GetAssetParamsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.tradeapi.v1.assets.AssetsServiceOuterClass.internal_static_grpc_tradeapi_v1_assets_GetAssetParamsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.tradeapi.v1.assets.AssetsServiceOuterClass.internal_static_grpc_tradeapi_v1_assets_GetAssetParamsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.tradeapi.v1.assets.GetAssetParamsResponse.class, grpc.tradeapi.v1.assets.GetAssetParamsResponse.Builder.class);
    }

    // Construct using grpc.tradeapi.v1.assets.GetAssetParamsResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getLongableFieldBuilder();
        getShortableFieldBuilder();
        getLongRiskRateFieldBuilder();
        getLongCollateralFieldBuilder();
        getShortRiskRateFieldBuilder();
        getShortCollateralFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      symbol_ = "";
      accountId_ = "";
      tradeable_ = false;
      longable_ = null;
      if (longableBuilder_ != null) {
        longableBuilder_.dispose();
        longableBuilder_ = null;
      }
      shortable_ = null;
      if (shortableBuilder_ != null) {
        shortableBuilder_.dispose();
        shortableBuilder_ = null;
      }
      longRiskRate_ = null;
      if (longRiskRateBuilder_ != null) {
        longRiskRateBuilder_.dispose();
        longRiskRateBuilder_ = null;
      }
      longCollateral_ = null;
      if (longCollateralBuilder_ != null) {
        longCollateralBuilder_.dispose();
        longCollateralBuilder_ = null;
      }
      shortRiskRate_ = null;
      if (shortRiskRateBuilder_ != null) {
        shortRiskRateBuilder_.dispose();
        shortRiskRateBuilder_ = null;
      }
      shortCollateral_ = null;
      if (shortCollateralBuilder_ != null) {
        shortCollateralBuilder_.dispose();
        shortCollateralBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.tradeapi.v1.assets.AssetsServiceOuterClass.internal_static_grpc_tradeapi_v1_assets_GetAssetParamsResponse_descriptor;
    }

    @java.lang.Override
    public grpc.tradeapi.v1.assets.GetAssetParamsResponse getDefaultInstanceForType() {
      return grpc.tradeapi.v1.assets.GetAssetParamsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.tradeapi.v1.assets.GetAssetParamsResponse build() {
      grpc.tradeapi.v1.assets.GetAssetParamsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.tradeapi.v1.assets.GetAssetParamsResponse buildPartial() {
      grpc.tradeapi.v1.assets.GetAssetParamsResponse result = new grpc.tradeapi.v1.assets.GetAssetParamsResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(grpc.tradeapi.v1.assets.GetAssetParamsResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.symbol_ = symbol_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.accountId_ = accountId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.tradeable_ = tradeable_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.longable_ = longableBuilder_ == null
            ? longable_
            : longableBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.shortable_ = shortableBuilder_ == null
            ? shortable_
            : shortableBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.longRiskRate_ = longRiskRateBuilder_ == null
            ? longRiskRate_
            : longRiskRateBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.longCollateral_ = longCollateralBuilder_ == null
            ? longCollateral_
            : longCollateralBuilder_.build();
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.shortRiskRate_ = shortRiskRateBuilder_ == null
            ? shortRiskRate_
            : shortRiskRateBuilder_.build();
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.shortCollateral_ = shortCollateralBuilder_ == null
            ? shortCollateral_
            : shortCollateralBuilder_.build();
        to_bitField0_ |= 0x00000020;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.tradeapi.v1.assets.GetAssetParamsResponse) {
        return mergeFrom((grpc.tradeapi.v1.assets.GetAssetParamsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.tradeapi.v1.assets.GetAssetParamsResponse other) {
      if (other == grpc.tradeapi.v1.assets.GetAssetParamsResponse.getDefaultInstance()) return this;
      if (!other.getSymbol().isEmpty()) {
        symbol_ = other.symbol_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getAccountId().isEmpty()) {
        accountId_ = other.accountId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getTradeable() != false) {
        setTradeable(other.getTradeable());
      }
      if (other.hasLongable()) {
        mergeLongable(other.getLongable());
      }
      if (other.hasShortable()) {
        mergeShortable(other.getShortable());
      }
      if (other.hasLongRiskRate()) {
        mergeLongRiskRate(other.getLongRiskRate());
      }
      if (other.hasLongCollateral()) {
        mergeLongCollateral(other.getLongCollateral());
      }
      if (other.hasShortRiskRate()) {
        mergeShortRiskRate(other.getShortRiskRate());
      }
      if (other.hasShortCollateral()) {
        mergeShortCollateral(other.getShortCollateral());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              symbol_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              accountId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              tradeable_ = input.readBool();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              input.readMessage(
                  getLongableFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  getShortableFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              input.readMessage(
                  getLongRiskRateFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              input.readMessage(
                  getLongCollateralFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              input.readMessage(
                  getShortRiskRateFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 74: {
              input.readMessage(
                  getShortCollateralFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object symbol_ = "";
    /**
     * <pre>
     * Символ инструмента
     * </pre>
     *
     * <code>string symbol = 1;</code>
     * @return The symbol.
     */
    public java.lang.String getSymbol() {
      java.lang.Object ref = symbol_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        symbol_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Символ инструмента
     * </pre>
     *
     * <code>string symbol = 1;</code>
     * @return The bytes for symbol.
     */
    public com.google.protobuf.ByteString
        getSymbolBytes() {
      java.lang.Object ref = symbol_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        symbol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Символ инструмента
     * </pre>
     *
     * <code>string symbol = 1;</code>
     * @param value The symbol to set.
     * @return This builder for chaining.
     */
    public Builder setSymbol(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      symbol_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Символ инструмента
     * </pre>
     *
     * <code>string symbol = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSymbol() {
      symbol_ = getDefaultInstance().getSymbol();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Символ инструмента
     * </pre>
     *
     * <code>string symbol = 1;</code>
     * @param value The bytes for symbol to set.
     * @return This builder for chaining.
     */
    public Builder setSymbolBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      symbol_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object accountId_ = "";
    /**
     * <pre>
     * ID аккаунта для которого подбираются торговые параметры
     * </pre>
     *
     * <code>string account_id = 2;</code>
     * @return The accountId.
     */
    public java.lang.String getAccountId() {
      java.lang.Object ref = accountId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        accountId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * ID аккаунта для которого подбираются торговые параметры
     * </pre>
     *
     * <code>string account_id = 2;</code>
     * @return The bytes for accountId.
     */
    public com.google.protobuf.ByteString
        getAccountIdBytes() {
      java.lang.Object ref = accountId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accountId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * ID аккаунта для которого подбираются торговые параметры
     * </pre>
     *
     * <code>string account_id = 2;</code>
     * @param value The accountId to set.
     * @return This builder for chaining.
     */
    public Builder setAccountId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      accountId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ID аккаунта для которого подбираются торговые параметры
     * </pre>
     *
     * <code>string account_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAccountId() {
      accountId_ = getDefaultInstance().getAccountId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ID аккаунта для которого подбираются торговые параметры
     * </pre>
     *
     * <code>string account_id = 2;</code>
     * @param value The bytes for accountId to set.
     * @return This builder for chaining.
     */
    public Builder setAccountIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      accountId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private boolean tradeable_ ;
    /**
     * <pre>
     * Доступны ли торговые операции
     * </pre>
     *
     * <code>bool tradeable = 3;</code>
     * @return The tradeable.
     */
    @java.lang.Override
    public boolean getTradeable() {
      return tradeable_;
    }
    /**
     * <pre>
     * Доступны ли торговые операции
     * </pre>
     *
     * <code>bool tradeable = 3;</code>
     * @param value The tradeable to set.
     * @return This builder for chaining.
     */
    public Builder setTradeable(boolean value) {

      tradeable_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Доступны ли торговые операции
     * </pre>
     *
     * <code>bool tradeable = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTradeable() {
      bitField0_ = (bitField0_ & ~0x00000004);
      tradeable_ = false;
      onChanged();
      return this;
    }

    private grpc.tradeapi.v1.assets.Longable longable_;
    private com.google.protobuf.SingleFieldBuilderV3<
        grpc.tradeapi.v1.assets.Longable, grpc.tradeapi.v1.assets.Longable.Builder, grpc.tradeapi.v1.assets.LongableOrBuilder> longableBuilder_;
    /**
     * <pre>
     * Доступны ли операции в Лонг 
     * </pre>
     *
     * <code>.grpc.tradeapi.v1.assets.Longable longable = 4;</code>
     * @return Whether the longable field is set.
     */
    public boolean hasLongable() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * Доступны ли операции в Лонг 
     * </pre>
     *
     * <code>.grpc.tradeapi.v1.assets.Longable longable = 4;</code>
     * @return The longable.
     */
    public grpc.tradeapi.v1.assets.Longable getLongable() {
      if (longableBuilder_ == null) {
        return longable_ == null ? grpc.tradeapi.v1.assets.Longable.getDefaultInstance() : longable_;
      } else {
        return longableBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Доступны ли операции в Лонг 
     * </pre>
     *
     * <code>.grpc.tradeapi.v1.assets.Longable longable = 4;</code>
     */
    public Builder setLongable(grpc.tradeapi.v1.assets.Longable value) {
      if (longableBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        longable_ = value;
      } else {
        longableBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Доступны ли операции в Лонг 
     * </pre>
     *
     * <code>.grpc.tradeapi.v1.assets.Longable longable = 4;</code>
     */
    public Builder setLongable(
        grpc.tradeapi.v1.assets.Longable.Builder builderForValue) {
      if (longableBuilder_ == null) {
        longable_ = builderForValue.build();
      } else {
        longableBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Доступны ли операции в Лонг 
     * </pre>
     *
     * <code>.grpc.tradeapi.v1.assets.Longable longable = 4;</code>
     */
    public Builder mergeLongable(grpc.tradeapi.v1.assets.Longable value) {
      if (longableBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          longable_ != null &&
          longable_ != grpc.tradeapi.v1.assets.Longable.getDefaultInstance()) {
          getLongableBuilder().mergeFrom(value);
        } else {
          longable_ = value;
        }
      } else {
        longableBuilder_.mergeFrom(value);
      }
      if (longable_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Доступны ли операции в Лонг 
     * </pre>
     *
     * <code>.grpc.tradeapi.v1.assets.Longable longable = 4;</code>
     */
    public Builder clearLongable() {
      bitField0_ = (bitField0_ & ~0x00000008);
      longable_ = null;
      if (longableBuilder_ != null) {
        longableBuilder_.dispose();
        longableBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Доступны ли операции в Лонг 
     * </pre>
     *
     * <code>.grpc.tradeapi.v1.assets.Longable longable = 4;</code>
     */
    public grpc.tradeapi.v1.assets.Longable.Builder getLongableBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getLongableFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Доступны ли операции в Лонг 
     * </pre>
     *
     * <code>.grpc.tradeapi.v1.assets.Longable longable = 4;</code>
     */
    public grpc.tradeapi.v1.assets.LongableOrBuilder getLongableOrBuilder() {
      if (longableBuilder_ != null) {
        return longableBuilder_.getMessageOrBuilder();
      } else {
        return longable_ == null ?
            grpc.tradeapi.v1.assets.Longable.getDefaultInstance() : longable_;
      }
    }
    /**
     * <pre>
     * Доступны ли операции в Лонг 
     * </pre>
     *
     * <code>.grpc.tradeapi.v1.assets.Longable longable = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        grpc.tradeapi.v1.assets.Longable, grpc.tradeapi.v1.assets.Longable.Builder, grpc.tradeapi.v1.assets.LongableOrBuilder> 
        getLongableFieldBuilder() {
      if (longableBuilder_ == null) {
        longableBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            grpc.tradeapi.v1.assets.Longable, grpc.tradeapi.v1.assets.Longable.Builder, grpc.tradeapi.v1.assets.LongableOrBuilder>(
                getLongable(),
                getParentForChildren(),
                isClean());
        longable_ = null;
      }
      return longableBuilder_;
    }

    private grpc.tradeapi.v1.assets.Shortable shortable_;
    private com.google.protobuf.SingleFieldBuilderV3<
        grpc.tradeapi.v1.assets.Shortable, grpc.tradeapi.v1.assets.Shortable.Builder, grpc.tradeapi.v1.assets.ShortableOrBuilder> shortableBuilder_;
    /**
     * <pre>
     * Доступны ли операции в Шорт
     * </pre>
     *
     * <code>.grpc.tradeapi.v1.assets.Shortable shortable = 5;</code>
     * @return Whether the shortable field is set.
     */
    public boolean hasShortable() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     * Доступны ли операции в Шорт
     * </pre>
     *
     * <code>.grpc.tradeapi.v1.assets.Shortable shortable = 5;</code>
     * @return The shortable.
     */
    public grpc.tradeapi.v1.assets.Shortable getShortable() {
      if (shortableBuilder_ == null) {
        return shortable_ == null ? grpc.tradeapi.v1.assets.Shortable.getDefaultInstance() : shortable_;
      } else {
        return shortableBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Доступны ли операции в Шорт
     * </pre>
     *
     * <code>.grpc.tradeapi.v1.assets.Shortable shortable = 5;</code>
     */
    public Builder setShortable(grpc.tradeapi.v1.assets.Shortable value) {
      if (shortableBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        shortable_ = value;
      } else {
        shortableBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Доступны ли операции в Шорт
     * </pre>
     *
     * <code>.grpc.tradeapi.v1.assets.Shortable shortable = 5;</code>
     */
    public Builder setShortable(
        grpc.tradeapi.v1.assets.Shortable.Builder builderForValue) {
      if (shortableBuilder_ == null) {
        shortable_ = builderForValue.build();
      } else {
        shortableBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Доступны ли операции в Шорт
     * </pre>
     *
     * <code>.grpc.tradeapi.v1.assets.Shortable shortable = 5;</code>
     */
    public Builder mergeShortable(grpc.tradeapi.v1.assets.Shortable value) {
      if (shortableBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          shortable_ != null &&
          shortable_ != grpc.tradeapi.v1.assets.Shortable.getDefaultInstance()) {
          getShortableBuilder().mergeFrom(value);
        } else {
          shortable_ = value;
        }
      } else {
        shortableBuilder_.mergeFrom(value);
      }
      if (shortable_ != null) {
        bitField0_ |= 0x00000010;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Доступны ли операции в Шорт
     * </pre>
     *
     * <code>.grpc.tradeapi.v1.assets.Shortable shortable = 5;</code>
     */
    public Builder clearShortable() {
      bitField0_ = (bitField0_ & ~0x00000010);
      shortable_ = null;
      if (shortableBuilder_ != null) {
        shortableBuilder_.dispose();
        shortableBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Доступны ли операции в Шорт
     * </pre>
     *
     * <code>.grpc.tradeapi.v1.assets.Shortable shortable = 5;</code>
     */
    public grpc.tradeapi.v1.assets.Shortable.Builder getShortableBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return getShortableFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Доступны ли операции в Шорт
     * </pre>
     *
     * <code>.grpc.tradeapi.v1.assets.Shortable shortable = 5;</code>
     */
    public grpc.tradeapi.v1.assets.ShortableOrBuilder getShortableOrBuilder() {
      if (shortableBuilder_ != null) {
        return shortableBuilder_.getMessageOrBuilder();
      } else {
        return shortable_ == null ?
            grpc.tradeapi.v1.assets.Shortable.getDefaultInstance() : shortable_;
      }
    }
    /**
     * <pre>
     * Доступны ли операции в Шорт
     * </pre>
     *
     * <code>.grpc.tradeapi.v1.assets.Shortable shortable = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        grpc.tradeapi.v1.assets.Shortable, grpc.tradeapi.v1.assets.Shortable.Builder, grpc.tradeapi.v1.assets.ShortableOrBuilder> 
        getShortableFieldBuilder() {
      if (shortableBuilder_ == null) {
        shortableBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            grpc.tradeapi.v1.assets.Shortable, grpc.tradeapi.v1.assets.Shortable.Builder, grpc.tradeapi.v1.assets.ShortableOrBuilder>(
                getShortable(),
                getParentForChildren(),
                isClean());
        shortable_ = null;
      }
      return shortableBuilder_;
    }

    private com.google.type.Decimal longRiskRate_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.type.Decimal, com.google.type.Decimal.Builder, com.google.type.DecimalOrBuilder> longRiskRateBuilder_;
    /**
     * <pre>
     * Ставка риска для операции в Лонг
     * </pre>
     *
     * <code>.google.type.Decimal long_risk_rate = 6;</code>
     * @return Whether the longRiskRate field is set.
     */
    public boolean hasLongRiskRate() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <pre>
     * Ставка риска для операции в Лонг
     * </pre>
     *
     * <code>.google.type.Decimal long_risk_rate = 6;</code>
     * @return The longRiskRate.
     */
    public com.google.type.Decimal getLongRiskRate() {
      if (longRiskRateBuilder_ == null) {
        return longRiskRate_ == null ? com.google.type.Decimal.getDefaultInstance() : longRiskRate_;
      } else {
        return longRiskRateBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Ставка риска для операции в Лонг
     * </pre>
     *
     * <code>.google.type.Decimal long_risk_rate = 6;</code>
     */
    public Builder setLongRiskRate(com.google.type.Decimal value) {
      if (longRiskRateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        longRiskRate_ = value;
      } else {
        longRiskRateBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Ставка риска для операции в Лонг
     * </pre>
     *
     * <code>.google.type.Decimal long_risk_rate = 6;</code>
     */
    public Builder setLongRiskRate(
        com.google.type.Decimal.Builder builderForValue) {
      if (longRiskRateBuilder_ == null) {
        longRiskRate_ = builderForValue.build();
      } else {
        longRiskRateBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Ставка риска для операции в Лонг
     * </pre>
     *
     * <code>.google.type.Decimal long_risk_rate = 6;</code>
     */
    public Builder mergeLongRiskRate(com.google.type.Decimal value) {
      if (longRiskRateBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
          longRiskRate_ != null &&
          longRiskRate_ != com.google.type.Decimal.getDefaultInstance()) {
          getLongRiskRateBuilder().mergeFrom(value);
        } else {
          longRiskRate_ = value;
        }
      } else {
        longRiskRateBuilder_.mergeFrom(value);
      }
      if (longRiskRate_ != null) {
        bitField0_ |= 0x00000020;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Ставка риска для операции в Лонг
     * </pre>
     *
     * <code>.google.type.Decimal long_risk_rate = 6;</code>
     */
    public Builder clearLongRiskRate() {
      bitField0_ = (bitField0_ & ~0x00000020);
      longRiskRate_ = null;
      if (longRiskRateBuilder_ != null) {
        longRiskRateBuilder_.dispose();
        longRiskRateBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Ставка риска для операции в Лонг
     * </pre>
     *
     * <code>.google.type.Decimal long_risk_rate = 6;</code>
     */
    public com.google.type.Decimal.Builder getLongRiskRateBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return getLongRiskRateFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Ставка риска для операции в Лонг
     * </pre>
     *
     * <code>.google.type.Decimal long_risk_rate = 6;</code>
     */
    public com.google.type.DecimalOrBuilder getLongRiskRateOrBuilder() {
      if (longRiskRateBuilder_ != null) {
        return longRiskRateBuilder_.getMessageOrBuilder();
      } else {
        return longRiskRate_ == null ?
            com.google.type.Decimal.getDefaultInstance() : longRiskRate_;
      }
    }
    /**
     * <pre>
     * Ставка риска для операции в Лонг
     * </pre>
     *
     * <code>.google.type.Decimal long_risk_rate = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.type.Decimal, com.google.type.Decimal.Builder, com.google.type.DecimalOrBuilder> 
        getLongRiskRateFieldBuilder() {
      if (longRiskRateBuilder_ == null) {
        longRiskRateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.type.Decimal, com.google.type.Decimal.Builder, com.google.type.DecimalOrBuilder>(
                getLongRiskRate(),
                getParentForChildren(),
                isClean());
        longRiskRate_ = null;
      }
      return longRiskRateBuilder_;
    }

    private com.google.type.Money longCollateral_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.type.Money, com.google.type.Money.Builder, com.google.type.MoneyOrBuilder> longCollateralBuilder_;
    /**
     * <pre>
     * Сумма обеспечения для поддержания позиции Лонг
     * </pre>
     *
     * <code>.google.type.Money long_collateral = 7;</code>
     * @return Whether the longCollateral field is set.
     */
    public boolean hasLongCollateral() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <pre>
     * Сумма обеспечения для поддержания позиции Лонг
     * </pre>
     *
     * <code>.google.type.Money long_collateral = 7;</code>
     * @return The longCollateral.
     */
    public com.google.type.Money getLongCollateral() {
      if (longCollateralBuilder_ == null) {
        return longCollateral_ == null ? com.google.type.Money.getDefaultInstance() : longCollateral_;
      } else {
        return longCollateralBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Сумма обеспечения для поддержания позиции Лонг
     * </pre>
     *
     * <code>.google.type.Money long_collateral = 7;</code>
     */
    public Builder setLongCollateral(com.google.type.Money value) {
      if (longCollateralBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        longCollateral_ = value;
      } else {
        longCollateralBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Сумма обеспечения для поддержания позиции Лонг
     * </pre>
     *
     * <code>.google.type.Money long_collateral = 7;</code>
     */
    public Builder setLongCollateral(
        com.google.type.Money.Builder builderForValue) {
      if (longCollateralBuilder_ == null) {
        longCollateral_ = builderForValue.build();
      } else {
        longCollateralBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Сумма обеспечения для поддержания позиции Лонг
     * </pre>
     *
     * <code>.google.type.Money long_collateral = 7;</code>
     */
    public Builder mergeLongCollateral(com.google.type.Money value) {
      if (longCollateralBuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0) &&
          longCollateral_ != null &&
          longCollateral_ != com.google.type.Money.getDefaultInstance()) {
          getLongCollateralBuilder().mergeFrom(value);
        } else {
          longCollateral_ = value;
        }
      } else {
        longCollateralBuilder_.mergeFrom(value);
      }
      if (longCollateral_ != null) {
        bitField0_ |= 0x00000040;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Сумма обеспечения для поддержания позиции Лонг
     * </pre>
     *
     * <code>.google.type.Money long_collateral = 7;</code>
     */
    public Builder clearLongCollateral() {
      bitField0_ = (bitField0_ & ~0x00000040);
      longCollateral_ = null;
      if (longCollateralBuilder_ != null) {
        longCollateralBuilder_.dispose();
        longCollateralBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Сумма обеспечения для поддержания позиции Лонг
     * </pre>
     *
     * <code>.google.type.Money long_collateral = 7;</code>
     */
    public com.google.type.Money.Builder getLongCollateralBuilder() {
      bitField0_ |= 0x00000040;
      onChanged();
      return getLongCollateralFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Сумма обеспечения для поддержания позиции Лонг
     * </pre>
     *
     * <code>.google.type.Money long_collateral = 7;</code>
     */
    public com.google.type.MoneyOrBuilder getLongCollateralOrBuilder() {
      if (longCollateralBuilder_ != null) {
        return longCollateralBuilder_.getMessageOrBuilder();
      } else {
        return longCollateral_ == null ?
            com.google.type.Money.getDefaultInstance() : longCollateral_;
      }
    }
    /**
     * <pre>
     * Сумма обеспечения для поддержания позиции Лонг
     * </pre>
     *
     * <code>.google.type.Money long_collateral = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.type.Money, com.google.type.Money.Builder, com.google.type.MoneyOrBuilder> 
        getLongCollateralFieldBuilder() {
      if (longCollateralBuilder_ == null) {
        longCollateralBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.type.Money, com.google.type.Money.Builder, com.google.type.MoneyOrBuilder>(
                getLongCollateral(),
                getParentForChildren(),
                isClean());
        longCollateral_ = null;
      }
      return longCollateralBuilder_;
    }

    private com.google.type.Decimal shortRiskRate_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.type.Decimal, com.google.type.Decimal.Builder, com.google.type.DecimalOrBuilder> shortRiskRateBuilder_;
    /**
     * <pre>
     * Ставка риска для операции в Шорт
     * </pre>
     *
     * <code>.google.type.Decimal short_risk_rate = 8;</code>
     * @return Whether the shortRiskRate field is set.
     */
    public boolean hasShortRiskRate() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <pre>
     * Ставка риска для операции в Шорт
     * </pre>
     *
     * <code>.google.type.Decimal short_risk_rate = 8;</code>
     * @return The shortRiskRate.
     */
    public com.google.type.Decimal getShortRiskRate() {
      if (shortRiskRateBuilder_ == null) {
        return shortRiskRate_ == null ? com.google.type.Decimal.getDefaultInstance() : shortRiskRate_;
      } else {
        return shortRiskRateBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Ставка риска для операции в Шорт
     * </pre>
     *
     * <code>.google.type.Decimal short_risk_rate = 8;</code>
     */
    public Builder setShortRiskRate(com.google.type.Decimal value) {
      if (shortRiskRateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        shortRiskRate_ = value;
      } else {
        shortRiskRateBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Ставка риска для операции в Шорт
     * </pre>
     *
     * <code>.google.type.Decimal short_risk_rate = 8;</code>
     */
    public Builder setShortRiskRate(
        com.google.type.Decimal.Builder builderForValue) {
      if (shortRiskRateBuilder_ == null) {
        shortRiskRate_ = builderForValue.build();
      } else {
        shortRiskRateBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Ставка риска для операции в Шорт
     * </pre>
     *
     * <code>.google.type.Decimal short_risk_rate = 8;</code>
     */
    public Builder mergeShortRiskRate(com.google.type.Decimal value) {
      if (shortRiskRateBuilder_ == null) {
        if (((bitField0_ & 0x00000080) != 0) &&
          shortRiskRate_ != null &&
          shortRiskRate_ != com.google.type.Decimal.getDefaultInstance()) {
          getShortRiskRateBuilder().mergeFrom(value);
        } else {
          shortRiskRate_ = value;
        }
      } else {
        shortRiskRateBuilder_.mergeFrom(value);
      }
      if (shortRiskRate_ != null) {
        bitField0_ |= 0x00000080;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Ставка риска для операции в Шорт
     * </pre>
     *
     * <code>.google.type.Decimal short_risk_rate = 8;</code>
     */
    public Builder clearShortRiskRate() {
      bitField0_ = (bitField0_ & ~0x00000080);
      shortRiskRate_ = null;
      if (shortRiskRateBuilder_ != null) {
        shortRiskRateBuilder_.dispose();
        shortRiskRateBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Ставка риска для операции в Шорт
     * </pre>
     *
     * <code>.google.type.Decimal short_risk_rate = 8;</code>
     */
    public com.google.type.Decimal.Builder getShortRiskRateBuilder() {
      bitField0_ |= 0x00000080;
      onChanged();
      return getShortRiskRateFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Ставка риска для операции в Шорт
     * </pre>
     *
     * <code>.google.type.Decimal short_risk_rate = 8;</code>
     */
    public com.google.type.DecimalOrBuilder getShortRiskRateOrBuilder() {
      if (shortRiskRateBuilder_ != null) {
        return shortRiskRateBuilder_.getMessageOrBuilder();
      } else {
        return shortRiskRate_ == null ?
            com.google.type.Decimal.getDefaultInstance() : shortRiskRate_;
      }
    }
    /**
     * <pre>
     * Ставка риска для операции в Шорт
     * </pre>
     *
     * <code>.google.type.Decimal short_risk_rate = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.type.Decimal, com.google.type.Decimal.Builder, com.google.type.DecimalOrBuilder> 
        getShortRiskRateFieldBuilder() {
      if (shortRiskRateBuilder_ == null) {
        shortRiskRateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.type.Decimal, com.google.type.Decimal.Builder, com.google.type.DecimalOrBuilder>(
                getShortRiskRate(),
                getParentForChildren(),
                isClean());
        shortRiskRate_ = null;
      }
      return shortRiskRateBuilder_;
    }

    private com.google.type.Money shortCollateral_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.type.Money, com.google.type.Money.Builder, com.google.type.MoneyOrBuilder> shortCollateralBuilder_;
    /**
     * <pre>
     * Сумма обеспечения для поддержания позиции Шорт
     * </pre>
     *
     * <code>.google.type.Money short_collateral = 9;</code>
     * @return Whether the shortCollateral field is set.
     */
    public boolean hasShortCollateral() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <pre>
     * Сумма обеспечения для поддержания позиции Шорт
     * </pre>
     *
     * <code>.google.type.Money short_collateral = 9;</code>
     * @return The shortCollateral.
     */
    public com.google.type.Money getShortCollateral() {
      if (shortCollateralBuilder_ == null) {
        return shortCollateral_ == null ? com.google.type.Money.getDefaultInstance() : shortCollateral_;
      } else {
        return shortCollateralBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Сумма обеспечения для поддержания позиции Шорт
     * </pre>
     *
     * <code>.google.type.Money short_collateral = 9;</code>
     */
    public Builder setShortCollateral(com.google.type.Money value) {
      if (shortCollateralBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        shortCollateral_ = value;
      } else {
        shortCollateralBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Сумма обеспечения для поддержания позиции Шорт
     * </pre>
     *
     * <code>.google.type.Money short_collateral = 9;</code>
     */
    public Builder setShortCollateral(
        com.google.type.Money.Builder builderForValue) {
      if (shortCollateralBuilder_ == null) {
        shortCollateral_ = builderForValue.build();
      } else {
        shortCollateralBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Сумма обеспечения для поддержания позиции Шорт
     * </pre>
     *
     * <code>.google.type.Money short_collateral = 9;</code>
     */
    public Builder mergeShortCollateral(com.google.type.Money value) {
      if (shortCollateralBuilder_ == null) {
        if (((bitField0_ & 0x00000100) != 0) &&
          shortCollateral_ != null &&
          shortCollateral_ != com.google.type.Money.getDefaultInstance()) {
          getShortCollateralBuilder().mergeFrom(value);
        } else {
          shortCollateral_ = value;
        }
      } else {
        shortCollateralBuilder_.mergeFrom(value);
      }
      if (shortCollateral_ != null) {
        bitField0_ |= 0x00000100;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Сумма обеспечения для поддержания позиции Шорт
     * </pre>
     *
     * <code>.google.type.Money short_collateral = 9;</code>
     */
    public Builder clearShortCollateral() {
      bitField0_ = (bitField0_ & ~0x00000100);
      shortCollateral_ = null;
      if (shortCollateralBuilder_ != null) {
        shortCollateralBuilder_.dispose();
        shortCollateralBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Сумма обеспечения для поддержания позиции Шорт
     * </pre>
     *
     * <code>.google.type.Money short_collateral = 9;</code>
     */
    public com.google.type.Money.Builder getShortCollateralBuilder() {
      bitField0_ |= 0x00000100;
      onChanged();
      return getShortCollateralFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Сумма обеспечения для поддержания позиции Шорт
     * </pre>
     *
     * <code>.google.type.Money short_collateral = 9;</code>
     */
    public com.google.type.MoneyOrBuilder getShortCollateralOrBuilder() {
      if (shortCollateralBuilder_ != null) {
        return shortCollateralBuilder_.getMessageOrBuilder();
      } else {
        return shortCollateral_ == null ?
            com.google.type.Money.getDefaultInstance() : shortCollateral_;
      }
    }
    /**
     * <pre>
     * Сумма обеспечения для поддержания позиции Шорт
     * </pre>
     *
     * <code>.google.type.Money short_collateral = 9;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.type.Money, com.google.type.Money.Builder, com.google.type.MoneyOrBuilder> 
        getShortCollateralFieldBuilder() {
      if (shortCollateralBuilder_ == null) {
        shortCollateralBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.type.Money, com.google.type.Money.Builder, com.google.type.MoneyOrBuilder>(
                getShortCollateral(),
                getParentForChildren(),
                isClean());
        shortCollateral_ = null;
      }
      return shortCollateralBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:grpc.tradeapi.v1.assets.GetAssetParamsResponse)
  }

  // @@protoc_insertion_point(class_scope:grpc.tradeapi.v1.assets.GetAssetParamsResponse)
  private static final grpc.tradeapi.v1.assets.GetAssetParamsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.tradeapi.v1.assets.GetAssetParamsResponse();
  }

  public static grpc.tradeapi.v1.assets.GetAssetParamsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetAssetParamsResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetAssetParamsResponse>() {
    @java.lang.Override
    public GetAssetParamsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetAssetParamsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetAssetParamsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.tradeapi.v1.assets.GetAssetParamsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

