// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: assets/assets_service.proto

// Protobuf Java Version: 3.25.5
package grpc.tradeapi.v1.assets;

public interface OptionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.tradeapi.v1.assets.Option)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Символ инструмента
   * </pre>
   *
   * <code>string symbol = 1;</code>
   * @return The symbol.
   */
  java.lang.String getSymbol();
  /**
   * <pre>
   * Символ инструмента
   * </pre>
   *
   * <code>string symbol = 1;</code>
   * @return The bytes for symbol.
   */
  com.google.protobuf.ByteString
      getSymbolBytes();

  /**
   * <pre>
   * Тип инструмента
   * </pre>
   *
   * <code>.grpc.tradeapi.v1.assets.Option.Type type = 2;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <pre>
   * Тип инструмента
   * </pre>
   *
   * <code>.grpc.tradeapi.v1.assets.Option.Type type = 2;</code>
   * @return The type.
   */
  grpc.tradeapi.v1.assets.Option.Type getType();

  /**
   * <pre>
   * Лот, количество базового актива в инструменте
   * </pre>
   *
   * <code>.google.type.Decimal contract_size = 4;</code>
   * @return Whether the contractSize field is set.
   */
  boolean hasContractSize();
  /**
   * <pre>
   * Лот, количество базового актива в инструменте
   * </pre>
   *
   * <code>.google.type.Decimal contract_size = 4;</code>
   * @return The contractSize.
   */
  com.google.type.Decimal getContractSize();
  /**
   * <pre>
   * Лот, количество базового актива в инструменте
   * </pre>
   *
   * <code>.google.type.Decimal contract_size = 4;</code>
   */
  com.google.type.DecimalOrBuilder getContractSizeOrBuilder();

  /**
   * <pre>
   * Дата старта торговли
   * </pre>
   *
   * <code>.google.type.Date trade_first_day = 5;</code>
   * @return Whether the tradeFirstDay field is set.
   */
  boolean hasTradeFirstDay();
  /**
   * <pre>
   * Дата старта торговли
   * </pre>
   *
   * <code>.google.type.Date trade_first_day = 5;</code>
   * @return The tradeFirstDay.
   */
  com.google.type.Date getTradeFirstDay();
  /**
   * <pre>
   * Дата старта торговли
   * </pre>
   *
   * <code>.google.type.Date trade_first_day = 5;</code>
   */
  com.google.type.DateOrBuilder getTradeFirstDayOrBuilder();

  /**
   * <pre>
   * Дата окончания торговли
   * </pre>
   *
   * <code>.google.type.Date trade_last_day = 6;</code>
   * @return Whether the tradeLastDay field is set.
   */
  boolean hasTradeLastDay();
  /**
   * <pre>
   * Дата окончания торговли
   * </pre>
   *
   * <code>.google.type.Date trade_last_day = 6;</code>
   * @return The tradeLastDay.
   */
  com.google.type.Date getTradeLastDay();
  /**
   * <pre>
   * Дата окончания торговли
   * </pre>
   *
   * <code>.google.type.Date trade_last_day = 6;</code>
   */
  com.google.type.DateOrBuilder getTradeLastDayOrBuilder();

  /**
   * <pre>
   * Цена исполнения опциона
   * </pre>
   *
   * <code>.google.type.Decimal strike = 7;</code>
   * @return Whether the strike field is set.
   */
  boolean hasStrike();
  /**
   * <pre>
   * Цена исполнения опциона
   * </pre>
   *
   * <code>.google.type.Decimal strike = 7;</code>
   * @return The strike.
   */
  com.google.type.Decimal getStrike();
  /**
   * <pre>
   * Цена исполнения опциона
   * </pre>
   *
   * <code>.google.type.Decimal strike = 7;</code>
   */
  com.google.type.DecimalOrBuilder getStrikeOrBuilder();

  /**
   * <pre>
   * Множитель опциона
   * </pre>
   *
   * <code>.google.type.Decimal multiplier = 9;</code>
   * @return Whether the multiplier field is set.
   */
  boolean hasMultiplier();
  /**
   * <pre>
   * Множитель опциона
   * </pre>
   *
   * <code>.google.type.Decimal multiplier = 9;</code>
   * @return The multiplier.
   */
  com.google.type.Decimal getMultiplier();
  /**
   * <pre>
   * Множитель опциона
   * </pre>
   *
   * <code>.google.type.Decimal multiplier = 9;</code>
   */
  com.google.type.DecimalOrBuilder getMultiplierOrBuilder();

  /**
   * <pre>
   * Дата начала экспирации
   * </pre>
   *
   * <code>.google.type.Date expiration_first_day = 10;</code>
   * @return Whether the expirationFirstDay field is set.
   */
  boolean hasExpirationFirstDay();
  /**
   * <pre>
   * Дата начала экспирации
   * </pre>
   *
   * <code>.google.type.Date expiration_first_day = 10;</code>
   * @return The expirationFirstDay.
   */
  com.google.type.Date getExpirationFirstDay();
  /**
   * <pre>
   * Дата начала экспирации
   * </pre>
   *
   * <code>.google.type.Date expiration_first_day = 10;</code>
   */
  com.google.type.DateOrBuilder getExpirationFirstDayOrBuilder();

  /**
   * <pre>
   * Дата окончания экспирации
   * </pre>
   *
   * <code>.google.type.Date expiration_last_day = 11;</code>
   * @return Whether the expirationLastDay field is set.
   */
  boolean hasExpirationLastDay();
  /**
   * <pre>
   * Дата окончания экспирации
   * </pre>
   *
   * <code>.google.type.Date expiration_last_day = 11;</code>
   * @return The expirationLastDay.
   */
  com.google.type.Date getExpirationLastDay();
  /**
   * <pre>
   * Дата окончания экспирации
   * </pre>
   *
   * <code>.google.type.Date expiration_last_day = 11;</code>
   */
  com.google.type.DateOrBuilder getExpirationLastDayOrBuilder();
}
