// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: assets/assets_service.proto

// Protobuf Java Version: 3.25.5
package grpc.tradeapi.v1.assets;

/**
 * <pre>
 * Информация о цепочке опционов
 * </pre>
 *
 * Protobuf type {@code grpc.tradeapi.v1.assets.OptionsChainResponse}
 */
public final class OptionsChainResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:grpc.tradeapi.v1.assets.OptionsChainResponse)
    OptionsChainResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use OptionsChainResponse.newBuilder() to construct.
  private OptionsChainResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OptionsChainResponse() {
    symbol_ = "";
    options_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new OptionsChainResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.tradeapi.v1.assets.AssetsServiceOuterClass.internal_static_grpc_tradeapi_v1_assets_OptionsChainResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.tradeapi.v1.assets.AssetsServiceOuterClass.internal_static_grpc_tradeapi_v1_assets_OptionsChainResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.tradeapi.v1.assets.OptionsChainResponse.class, grpc.tradeapi.v1.assets.OptionsChainResponse.Builder.class);
  }

  public static final int SYMBOL_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object symbol_ = "";
  /**
   * <pre>
   * Символ базового актива опциона
   * </pre>
   *
   * <code>string symbol = 1;</code>
   * @return The symbol.
   */
  @java.lang.Override
  public java.lang.String getSymbol() {
    java.lang.Object ref = symbol_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      symbol_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Символ базового актива опциона
   * </pre>
   *
   * <code>string symbol = 1;</code>
   * @return The bytes for symbol.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSymbolBytes() {
    java.lang.Object ref = symbol_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      symbol_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OPTIONS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<grpc.tradeapi.v1.assets.Option> options_;
  /**
   * <pre>
   * Информация об опционе
   * </pre>
   *
   * <code>repeated .grpc.tradeapi.v1.assets.Option options = 2;</code>
   */
  @java.lang.Override
  public java.util.List<grpc.tradeapi.v1.assets.Option> getOptionsList() {
    return options_;
  }
  /**
   * <pre>
   * Информация об опционе
   * </pre>
   *
   * <code>repeated .grpc.tradeapi.v1.assets.Option options = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends grpc.tradeapi.v1.assets.OptionOrBuilder> 
      getOptionsOrBuilderList() {
    return options_;
  }
  /**
   * <pre>
   * Информация об опционе
   * </pre>
   *
   * <code>repeated .grpc.tradeapi.v1.assets.Option options = 2;</code>
   */
  @java.lang.Override
  public int getOptionsCount() {
    return options_.size();
  }
  /**
   * <pre>
   * Информация об опционе
   * </pre>
   *
   * <code>repeated .grpc.tradeapi.v1.assets.Option options = 2;</code>
   */
  @java.lang.Override
  public grpc.tradeapi.v1.assets.Option getOptions(int index) {
    return options_.get(index);
  }
  /**
   * <pre>
   * Информация об опционе
   * </pre>
   *
   * <code>repeated .grpc.tradeapi.v1.assets.Option options = 2;</code>
   */
  @java.lang.Override
  public grpc.tradeapi.v1.assets.OptionOrBuilder getOptionsOrBuilder(
      int index) {
    return options_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(symbol_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, symbol_);
    }
    for (int i = 0; i < options_.size(); i++) {
      output.writeMessage(2, options_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(symbol_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, symbol_);
    }
    for (int i = 0; i < options_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, options_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.tradeapi.v1.assets.OptionsChainResponse)) {
      return super.equals(obj);
    }
    grpc.tradeapi.v1.assets.OptionsChainResponse other = (grpc.tradeapi.v1.assets.OptionsChainResponse) obj;

    if (!getSymbol()
        .equals(other.getSymbol())) return false;
    if (!getOptionsList()
        .equals(other.getOptionsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SYMBOL_FIELD_NUMBER;
    hash = (53 * hash) + getSymbol().hashCode();
    if (getOptionsCount() > 0) {
      hash = (37 * hash) + OPTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getOptionsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.tradeapi.v1.assets.OptionsChainResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.tradeapi.v1.assets.OptionsChainResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.tradeapi.v1.assets.OptionsChainResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.tradeapi.v1.assets.OptionsChainResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.tradeapi.v1.assets.OptionsChainResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.tradeapi.v1.assets.OptionsChainResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.tradeapi.v1.assets.OptionsChainResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.tradeapi.v1.assets.OptionsChainResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static grpc.tradeapi.v1.assets.OptionsChainResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static grpc.tradeapi.v1.assets.OptionsChainResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.tradeapi.v1.assets.OptionsChainResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.tradeapi.v1.assets.OptionsChainResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.tradeapi.v1.assets.OptionsChainResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Информация о цепочке опционов
   * </pre>
   *
   * Protobuf type {@code grpc.tradeapi.v1.assets.OptionsChainResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:grpc.tradeapi.v1.assets.OptionsChainResponse)
      grpc.tradeapi.v1.assets.OptionsChainResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.tradeapi.v1.assets.AssetsServiceOuterClass.internal_static_grpc_tradeapi_v1_assets_OptionsChainResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.tradeapi.v1.assets.AssetsServiceOuterClass.internal_static_grpc_tradeapi_v1_assets_OptionsChainResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.tradeapi.v1.assets.OptionsChainResponse.class, grpc.tradeapi.v1.assets.OptionsChainResponse.Builder.class);
    }

    // Construct using grpc.tradeapi.v1.assets.OptionsChainResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      symbol_ = "";
      if (optionsBuilder_ == null) {
        options_ = java.util.Collections.emptyList();
      } else {
        options_ = null;
        optionsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.tradeapi.v1.assets.AssetsServiceOuterClass.internal_static_grpc_tradeapi_v1_assets_OptionsChainResponse_descriptor;
    }

    @java.lang.Override
    public grpc.tradeapi.v1.assets.OptionsChainResponse getDefaultInstanceForType() {
      return grpc.tradeapi.v1.assets.OptionsChainResponse.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.tradeapi.v1.assets.OptionsChainResponse build() {
      grpc.tradeapi.v1.assets.OptionsChainResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.tradeapi.v1.assets.OptionsChainResponse buildPartial() {
      grpc.tradeapi.v1.assets.OptionsChainResponse result = new grpc.tradeapi.v1.assets.OptionsChainResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(grpc.tradeapi.v1.assets.OptionsChainResponse result) {
      if (optionsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          options_ = java.util.Collections.unmodifiableList(options_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.options_ = options_;
      } else {
        result.options_ = optionsBuilder_.build();
      }
    }

    private void buildPartial0(grpc.tradeapi.v1.assets.OptionsChainResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.symbol_ = symbol_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.tradeapi.v1.assets.OptionsChainResponse) {
        return mergeFrom((grpc.tradeapi.v1.assets.OptionsChainResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.tradeapi.v1.assets.OptionsChainResponse other) {
      if (other == grpc.tradeapi.v1.assets.OptionsChainResponse.getDefaultInstance()) return this;
      if (!other.getSymbol().isEmpty()) {
        symbol_ = other.symbol_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (optionsBuilder_ == null) {
        if (!other.options_.isEmpty()) {
          if (options_.isEmpty()) {
            options_ = other.options_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureOptionsIsMutable();
            options_.addAll(other.options_);
          }
          onChanged();
        }
      } else {
        if (!other.options_.isEmpty()) {
          if (optionsBuilder_.isEmpty()) {
            optionsBuilder_.dispose();
            optionsBuilder_ = null;
            options_ = other.options_;
            bitField0_ = (bitField0_ & ~0x00000002);
            optionsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getOptionsFieldBuilder() : null;
          } else {
            optionsBuilder_.addAllMessages(other.options_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              symbol_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              grpc.tradeapi.v1.assets.Option m =
                  input.readMessage(
                      grpc.tradeapi.v1.assets.Option.parser(),
                      extensionRegistry);
              if (optionsBuilder_ == null) {
                ensureOptionsIsMutable();
                options_.add(m);
              } else {
                optionsBuilder_.addMessage(m);
              }
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object symbol_ = "";
    /**
     * <pre>
     * Символ базового актива опциона
     * </pre>
     *
     * <code>string symbol = 1;</code>
     * @return The symbol.
     */
    public java.lang.String getSymbol() {
      java.lang.Object ref = symbol_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        symbol_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Символ базового актива опциона
     * </pre>
     *
     * <code>string symbol = 1;</code>
     * @return The bytes for symbol.
     */
    public com.google.protobuf.ByteString
        getSymbolBytes() {
      java.lang.Object ref = symbol_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        symbol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Символ базового актива опциона
     * </pre>
     *
     * <code>string symbol = 1;</code>
     * @param value The symbol to set.
     * @return This builder for chaining.
     */
    public Builder setSymbol(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      symbol_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Символ базового актива опциона
     * </pre>
     *
     * <code>string symbol = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSymbol() {
      symbol_ = getDefaultInstance().getSymbol();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Символ базового актива опциона
     * </pre>
     *
     * <code>string symbol = 1;</code>
     * @param value The bytes for symbol to set.
     * @return This builder for chaining.
     */
    public Builder setSymbolBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      symbol_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.util.List<grpc.tradeapi.v1.assets.Option> options_ =
      java.util.Collections.emptyList();
    private void ensureOptionsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        options_ = new java.util.ArrayList<grpc.tradeapi.v1.assets.Option>(options_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        grpc.tradeapi.v1.assets.Option, grpc.tradeapi.v1.assets.Option.Builder, grpc.tradeapi.v1.assets.OptionOrBuilder> optionsBuilder_;

    /**
     * <pre>
     * Информация об опционе
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.assets.Option options = 2;</code>
     */
    public java.util.List<grpc.tradeapi.v1.assets.Option> getOptionsList() {
      if (optionsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(options_);
      } else {
        return optionsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Информация об опционе
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.assets.Option options = 2;</code>
     */
    public int getOptionsCount() {
      if (optionsBuilder_ == null) {
        return options_.size();
      } else {
        return optionsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Информация об опционе
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.assets.Option options = 2;</code>
     */
    public grpc.tradeapi.v1.assets.Option getOptions(int index) {
      if (optionsBuilder_ == null) {
        return options_.get(index);
      } else {
        return optionsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Информация об опционе
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.assets.Option options = 2;</code>
     */
    public Builder setOptions(
        int index, grpc.tradeapi.v1.assets.Option value) {
      if (optionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOptionsIsMutable();
        options_.set(index, value);
        onChanged();
      } else {
        optionsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Информация об опционе
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.assets.Option options = 2;</code>
     */
    public Builder setOptions(
        int index, grpc.tradeapi.v1.assets.Option.Builder builderForValue) {
      if (optionsBuilder_ == null) {
        ensureOptionsIsMutable();
        options_.set(index, builderForValue.build());
        onChanged();
      } else {
        optionsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Информация об опционе
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.assets.Option options = 2;</code>
     */
    public Builder addOptions(grpc.tradeapi.v1.assets.Option value) {
      if (optionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOptionsIsMutable();
        options_.add(value);
        onChanged();
      } else {
        optionsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Информация об опционе
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.assets.Option options = 2;</code>
     */
    public Builder addOptions(
        int index, grpc.tradeapi.v1.assets.Option value) {
      if (optionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOptionsIsMutable();
        options_.add(index, value);
        onChanged();
      } else {
        optionsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Информация об опционе
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.assets.Option options = 2;</code>
     */
    public Builder addOptions(
        grpc.tradeapi.v1.assets.Option.Builder builderForValue) {
      if (optionsBuilder_ == null) {
        ensureOptionsIsMutable();
        options_.add(builderForValue.build());
        onChanged();
      } else {
        optionsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Информация об опционе
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.assets.Option options = 2;</code>
     */
    public Builder addOptions(
        int index, grpc.tradeapi.v1.assets.Option.Builder builderForValue) {
      if (optionsBuilder_ == null) {
        ensureOptionsIsMutable();
        options_.add(index, builderForValue.build());
        onChanged();
      } else {
        optionsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Информация об опционе
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.assets.Option options = 2;</code>
     */
    public Builder addAllOptions(
        java.lang.Iterable<? extends grpc.tradeapi.v1.assets.Option> values) {
      if (optionsBuilder_ == null) {
        ensureOptionsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, options_);
        onChanged();
      } else {
        optionsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Информация об опционе
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.assets.Option options = 2;</code>
     */
    public Builder clearOptions() {
      if (optionsBuilder_ == null) {
        options_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        optionsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Информация об опционе
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.assets.Option options = 2;</code>
     */
    public Builder removeOptions(int index) {
      if (optionsBuilder_ == null) {
        ensureOptionsIsMutable();
        options_.remove(index);
        onChanged();
      } else {
        optionsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Информация об опционе
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.assets.Option options = 2;</code>
     */
    public grpc.tradeapi.v1.assets.Option.Builder getOptionsBuilder(
        int index) {
      return getOptionsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Информация об опционе
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.assets.Option options = 2;</code>
     */
    public grpc.tradeapi.v1.assets.OptionOrBuilder getOptionsOrBuilder(
        int index) {
      if (optionsBuilder_ == null) {
        return options_.get(index);  } else {
        return optionsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Информация об опционе
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.assets.Option options = 2;</code>
     */
    public java.util.List<? extends grpc.tradeapi.v1.assets.OptionOrBuilder> 
         getOptionsOrBuilderList() {
      if (optionsBuilder_ != null) {
        return optionsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(options_);
      }
    }
    /**
     * <pre>
     * Информация об опционе
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.assets.Option options = 2;</code>
     */
    public grpc.tradeapi.v1.assets.Option.Builder addOptionsBuilder() {
      return getOptionsFieldBuilder().addBuilder(
          grpc.tradeapi.v1.assets.Option.getDefaultInstance());
    }
    /**
     * <pre>
     * Информация об опционе
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.assets.Option options = 2;</code>
     */
    public grpc.tradeapi.v1.assets.Option.Builder addOptionsBuilder(
        int index) {
      return getOptionsFieldBuilder().addBuilder(
          index, grpc.tradeapi.v1.assets.Option.getDefaultInstance());
    }
    /**
     * <pre>
     * Информация об опционе
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.assets.Option options = 2;</code>
     */
    public java.util.List<grpc.tradeapi.v1.assets.Option.Builder> 
         getOptionsBuilderList() {
      return getOptionsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        grpc.tradeapi.v1.assets.Option, grpc.tradeapi.v1.assets.Option.Builder, grpc.tradeapi.v1.assets.OptionOrBuilder> 
        getOptionsFieldBuilder() {
      if (optionsBuilder_ == null) {
        optionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            grpc.tradeapi.v1.assets.Option, grpc.tradeapi.v1.assets.Option.Builder, grpc.tradeapi.v1.assets.OptionOrBuilder>(
                options_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        options_ = null;
      }
      return optionsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:grpc.tradeapi.v1.assets.OptionsChainResponse)
  }

  // @@protoc_insertion_point(class_scope:grpc.tradeapi.v1.assets.OptionsChainResponse)
  private static final grpc.tradeapi.v1.assets.OptionsChainResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.tradeapi.v1.assets.OptionsChainResponse();
  }

  public static grpc.tradeapi.v1.assets.OptionsChainResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OptionsChainResponse>
      PARSER = new com.google.protobuf.AbstractParser<OptionsChainResponse>() {
    @java.lang.Override
    public OptionsChainResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<OptionsChainResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OptionsChainResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.tradeapi.v1.assets.OptionsChainResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

