// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: assets/assets_service.proto

// Protobuf Java Version: 3.25.5
package grpc.tradeapi.v1.assets;

/**
 * <pre>
 * Расписание инструмента
 * </pre>
 *
 * Protobuf type {@code grpc.tradeapi.v1.assets.ScheduleResponse}
 */
public final class ScheduleResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:grpc.tradeapi.v1.assets.ScheduleResponse)
    ScheduleResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ScheduleResponse.newBuilder() to construct.
  private ScheduleResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ScheduleResponse() {
    symbol_ = "";
    sessions_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ScheduleResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.tradeapi.v1.assets.AssetsServiceOuterClass.internal_static_grpc_tradeapi_v1_assets_ScheduleResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.tradeapi.v1.assets.AssetsServiceOuterClass.internal_static_grpc_tradeapi_v1_assets_ScheduleResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.tradeapi.v1.assets.ScheduleResponse.class, grpc.tradeapi.v1.assets.ScheduleResponse.Builder.class);
  }

  public interface SessionsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:grpc.tradeapi.v1.assets.ScheduleResponse.Sessions)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Тип сессии
     * </pre>
     *
     * <code>string type = 1;</code>
     * @return The type.
     */
    java.lang.String getType();
    /**
     * <pre>
     * Тип сессии
     * </pre>
     *
     * <code>string type = 1;</code>
     * @return The bytes for type.
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <pre>
     * Интервал сессии
     * </pre>
     *
     * <code>.google.type.Interval interval = 2;</code>
     * @return Whether the interval field is set.
     */
    boolean hasInterval();
    /**
     * <pre>
     * Интервал сессии
     * </pre>
     *
     * <code>.google.type.Interval interval = 2;</code>
     * @return The interval.
     */
    com.google.type.Interval getInterval();
    /**
     * <pre>
     * Интервал сессии
     * </pre>
     *
     * <code>.google.type.Interval interval = 2;</code>
     */
    com.google.type.IntervalOrBuilder getIntervalOrBuilder();
  }
  /**
   * <pre>
   * Сессии
   * </pre>
   *
   * Protobuf type {@code grpc.tradeapi.v1.assets.ScheduleResponse.Sessions}
   */
  public static final class Sessions extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:grpc.tradeapi.v1.assets.ScheduleResponse.Sessions)
      SessionsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Sessions.newBuilder() to construct.
    private Sessions(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Sessions() {
      type_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Sessions();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.tradeapi.v1.assets.AssetsServiceOuterClass.internal_static_grpc_tradeapi_v1_assets_ScheduleResponse_Sessions_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.tradeapi.v1.assets.AssetsServiceOuterClass.internal_static_grpc_tradeapi_v1_assets_ScheduleResponse_Sessions_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.tradeapi.v1.assets.ScheduleResponse.Sessions.class, grpc.tradeapi.v1.assets.ScheduleResponse.Sessions.Builder.class);
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object type_ = "";
    /**
     * <pre>
     * Тип сессии
     * </pre>
     *
     * <code>string type = 1;</code>
     * @return The type.
     */
    @java.lang.Override
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Тип сессии
     * </pre>
     *
     * <code>string type = 1;</code>
     * @return The bytes for type.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INTERVAL_FIELD_NUMBER = 2;
    private com.google.type.Interval interval_;
    /**
     * <pre>
     * Интервал сессии
     * </pre>
     *
     * <code>.google.type.Interval interval = 2;</code>
     * @return Whether the interval field is set.
     */
    @java.lang.Override
    public boolean hasInterval() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Интервал сессии
     * </pre>
     *
     * <code>.google.type.Interval interval = 2;</code>
     * @return The interval.
     */
    @java.lang.Override
    public com.google.type.Interval getInterval() {
      return interval_ == null ? com.google.type.Interval.getDefaultInstance() : interval_;
    }
    /**
     * <pre>
     * Интервал сессии
     * </pre>
     *
     * <code>.google.type.Interval interval = 2;</code>
     */
    @java.lang.Override
    public com.google.type.IntervalOrBuilder getIntervalOrBuilder() {
      return interval_ == null ? com.google.type.Interval.getDefaultInstance() : interval_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(type_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, type_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(2, getInterval());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(type_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, type_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getInterval());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof grpc.tradeapi.v1.assets.ScheduleResponse.Sessions)) {
        return super.equals(obj);
      }
      grpc.tradeapi.v1.assets.ScheduleResponse.Sessions other = (grpc.tradeapi.v1.assets.ScheduleResponse.Sessions) obj;

      if (!getType()
          .equals(other.getType())) return false;
      if (hasInterval() != other.hasInterval()) return false;
      if (hasInterval()) {
        if (!getInterval()
            .equals(other.getInterval())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
      if (hasInterval()) {
        hash = (37 * hash) + INTERVAL_FIELD_NUMBER;
        hash = (53 * hash) + getInterval().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static grpc.tradeapi.v1.assets.ScheduleResponse.Sessions parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.tradeapi.v1.assets.ScheduleResponse.Sessions parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.tradeapi.v1.assets.ScheduleResponse.Sessions parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.tradeapi.v1.assets.ScheduleResponse.Sessions parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.tradeapi.v1.assets.ScheduleResponse.Sessions parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.tradeapi.v1.assets.ScheduleResponse.Sessions parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.tradeapi.v1.assets.ScheduleResponse.Sessions parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.tradeapi.v1.assets.ScheduleResponse.Sessions parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static grpc.tradeapi.v1.assets.ScheduleResponse.Sessions parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static grpc.tradeapi.v1.assets.ScheduleResponse.Sessions parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.tradeapi.v1.assets.ScheduleResponse.Sessions parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.tradeapi.v1.assets.ScheduleResponse.Sessions parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(grpc.tradeapi.v1.assets.ScheduleResponse.Sessions prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Сессии
     * </pre>
     *
     * Protobuf type {@code grpc.tradeapi.v1.assets.ScheduleResponse.Sessions}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:grpc.tradeapi.v1.assets.ScheduleResponse.Sessions)
        grpc.tradeapi.v1.assets.ScheduleResponse.SessionsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return grpc.tradeapi.v1.assets.AssetsServiceOuterClass.internal_static_grpc_tradeapi_v1_assets_ScheduleResponse_Sessions_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return grpc.tradeapi.v1.assets.AssetsServiceOuterClass.internal_static_grpc_tradeapi_v1_assets_ScheduleResponse_Sessions_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                grpc.tradeapi.v1.assets.ScheduleResponse.Sessions.class, grpc.tradeapi.v1.assets.ScheduleResponse.Sessions.Builder.class);
      }

      // Construct using grpc.tradeapi.v1.assets.ScheduleResponse.Sessions.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getIntervalFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        type_ = "";
        interval_ = null;
        if (intervalBuilder_ != null) {
          intervalBuilder_.dispose();
          intervalBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return grpc.tradeapi.v1.assets.AssetsServiceOuterClass.internal_static_grpc_tradeapi_v1_assets_ScheduleResponse_Sessions_descriptor;
      }

      @java.lang.Override
      public grpc.tradeapi.v1.assets.ScheduleResponse.Sessions getDefaultInstanceForType() {
        return grpc.tradeapi.v1.assets.ScheduleResponse.Sessions.getDefaultInstance();
      }

      @java.lang.Override
      public grpc.tradeapi.v1.assets.ScheduleResponse.Sessions build() {
        grpc.tradeapi.v1.assets.ScheduleResponse.Sessions result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public grpc.tradeapi.v1.assets.ScheduleResponse.Sessions buildPartial() {
        grpc.tradeapi.v1.assets.ScheduleResponse.Sessions result = new grpc.tradeapi.v1.assets.ScheduleResponse.Sessions(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(grpc.tradeapi.v1.assets.ScheduleResponse.Sessions result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.type_ = type_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.interval_ = intervalBuilder_ == null
              ? interval_
              : intervalBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof grpc.tradeapi.v1.assets.ScheduleResponse.Sessions) {
          return mergeFrom((grpc.tradeapi.v1.assets.ScheduleResponse.Sessions)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(grpc.tradeapi.v1.assets.ScheduleResponse.Sessions other) {
        if (other == grpc.tradeapi.v1.assets.ScheduleResponse.Sessions.getDefaultInstance()) return this;
        if (!other.getType().isEmpty()) {
          type_ = other.type_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasInterval()) {
          mergeInterval(other.getInterval());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                type_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getIntervalFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object type_ = "";
      /**
       * <pre>
       * Тип сессии
       * </pre>
       *
       * <code>string type = 1;</code>
       * @return The type.
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Тип сессии
       * </pre>
       *
       * <code>string type = 1;</code>
       * @return The bytes for type.
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Тип сессии
       * </pre>
       *
       * <code>string type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        type_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Тип сессии
       * </pre>
       *
       * <code>string type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        type_ = getDefaultInstance().getType();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Тип сессии
       * </pre>
       *
       * <code>string type = 1;</code>
       * @param value The bytes for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        type_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private com.google.type.Interval interval_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.type.Interval, com.google.type.Interval.Builder, com.google.type.IntervalOrBuilder> intervalBuilder_;
      /**
       * <pre>
       * Интервал сессии
       * </pre>
       *
       * <code>.google.type.Interval interval = 2;</code>
       * @return Whether the interval field is set.
       */
      public boolean hasInterval() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       * Интервал сессии
       * </pre>
       *
       * <code>.google.type.Interval interval = 2;</code>
       * @return The interval.
       */
      public com.google.type.Interval getInterval() {
        if (intervalBuilder_ == null) {
          return interval_ == null ? com.google.type.Interval.getDefaultInstance() : interval_;
        } else {
          return intervalBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * Интервал сессии
       * </pre>
       *
       * <code>.google.type.Interval interval = 2;</code>
       */
      public Builder setInterval(com.google.type.Interval value) {
        if (intervalBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          interval_ = value;
        } else {
          intervalBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Интервал сессии
       * </pre>
       *
       * <code>.google.type.Interval interval = 2;</code>
       */
      public Builder setInterval(
          com.google.type.Interval.Builder builderForValue) {
        if (intervalBuilder_ == null) {
          interval_ = builderForValue.build();
        } else {
          intervalBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Интервал сессии
       * </pre>
       *
       * <code>.google.type.Interval interval = 2;</code>
       */
      public Builder mergeInterval(com.google.type.Interval value) {
        if (intervalBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            interval_ != null &&
            interval_ != com.google.type.Interval.getDefaultInstance()) {
            getIntervalBuilder().mergeFrom(value);
          } else {
            interval_ = value;
          }
        } else {
          intervalBuilder_.mergeFrom(value);
        }
        if (interval_ != null) {
          bitField0_ |= 0x00000002;
          onChanged();
        }
        return this;
      }
      /**
       * <pre>
       * Интервал сессии
       * </pre>
       *
       * <code>.google.type.Interval interval = 2;</code>
       */
      public Builder clearInterval() {
        bitField0_ = (bitField0_ & ~0x00000002);
        interval_ = null;
        if (intervalBuilder_ != null) {
          intervalBuilder_.dispose();
          intervalBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Интервал сессии
       * </pre>
       *
       * <code>.google.type.Interval interval = 2;</code>
       */
      public com.google.type.Interval.Builder getIntervalBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getIntervalFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * Интервал сессии
       * </pre>
       *
       * <code>.google.type.Interval interval = 2;</code>
       */
      public com.google.type.IntervalOrBuilder getIntervalOrBuilder() {
        if (intervalBuilder_ != null) {
          return intervalBuilder_.getMessageOrBuilder();
        } else {
          return interval_ == null ?
              com.google.type.Interval.getDefaultInstance() : interval_;
        }
      }
      /**
       * <pre>
       * Интервал сессии
       * </pre>
       *
       * <code>.google.type.Interval interval = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.type.Interval, com.google.type.Interval.Builder, com.google.type.IntervalOrBuilder> 
          getIntervalFieldBuilder() {
        if (intervalBuilder_ == null) {
          intervalBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.type.Interval, com.google.type.Interval.Builder, com.google.type.IntervalOrBuilder>(
                  getInterval(),
                  getParentForChildren(),
                  isClean());
          interval_ = null;
        }
        return intervalBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:grpc.tradeapi.v1.assets.ScheduleResponse.Sessions)
    }

    // @@protoc_insertion_point(class_scope:grpc.tradeapi.v1.assets.ScheduleResponse.Sessions)
    private static final grpc.tradeapi.v1.assets.ScheduleResponse.Sessions DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new grpc.tradeapi.v1.assets.ScheduleResponse.Sessions();
    }

    public static grpc.tradeapi.v1.assets.ScheduleResponse.Sessions getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Sessions>
        PARSER = new com.google.protobuf.AbstractParser<Sessions>() {
      @java.lang.Override
      public Sessions parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Sessions> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Sessions> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public grpc.tradeapi.v1.assets.ScheduleResponse.Sessions getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int SYMBOL_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object symbol_ = "";
  /**
   * <pre>
   * Символ инструмента
   * </pre>
   *
   * <code>string symbol = 1;</code>
   * @return The symbol.
   */
  @java.lang.Override
  public java.lang.String getSymbol() {
    java.lang.Object ref = symbol_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      symbol_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Символ инструмента
   * </pre>
   *
   * <code>string symbol = 1;</code>
   * @return The bytes for symbol.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSymbolBytes() {
    java.lang.Object ref = symbol_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      symbol_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SESSIONS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<grpc.tradeapi.v1.assets.ScheduleResponse.Sessions> sessions_;
  /**
   * <pre>
   * Сессии инструмента
   * </pre>
   *
   * <code>repeated .grpc.tradeapi.v1.assets.ScheduleResponse.Sessions sessions = 2;</code>
   */
  @java.lang.Override
  public java.util.List<grpc.tradeapi.v1.assets.ScheduleResponse.Sessions> getSessionsList() {
    return sessions_;
  }
  /**
   * <pre>
   * Сессии инструмента
   * </pre>
   *
   * <code>repeated .grpc.tradeapi.v1.assets.ScheduleResponse.Sessions sessions = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends grpc.tradeapi.v1.assets.ScheduleResponse.SessionsOrBuilder> 
      getSessionsOrBuilderList() {
    return sessions_;
  }
  /**
   * <pre>
   * Сессии инструмента
   * </pre>
   *
   * <code>repeated .grpc.tradeapi.v1.assets.ScheduleResponse.Sessions sessions = 2;</code>
   */
  @java.lang.Override
  public int getSessionsCount() {
    return sessions_.size();
  }
  /**
   * <pre>
   * Сессии инструмента
   * </pre>
   *
   * <code>repeated .grpc.tradeapi.v1.assets.ScheduleResponse.Sessions sessions = 2;</code>
   */
  @java.lang.Override
  public grpc.tradeapi.v1.assets.ScheduleResponse.Sessions getSessions(int index) {
    return sessions_.get(index);
  }
  /**
   * <pre>
   * Сессии инструмента
   * </pre>
   *
   * <code>repeated .grpc.tradeapi.v1.assets.ScheduleResponse.Sessions sessions = 2;</code>
   */
  @java.lang.Override
  public grpc.tradeapi.v1.assets.ScheduleResponse.SessionsOrBuilder getSessionsOrBuilder(
      int index) {
    return sessions_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(symbol_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, symbol_);
    }
    for (int i = 0; i < sessions_.size(); i++) {
      output.writeMessage(2, sessions_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(symbol_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, symbol_);
    }
    for (int i = 0; i < sessions_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, sessions_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.tradeapi.v1.assets.ScheduleResponse)) {
      return super.equals(obj);
    }
    grpc.tradeapi.v1.assets.ScheduleResponse other = (grpc.tradeapi.v1.assets.ScheduleResponse) obj;

    if (!getSymbol()
        .equals(other.getSymbol())) return false;
    if (!getSessionsList()
        .equals(other.getSessionsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SYMBOL_FIELD_NUMBER;
    hash = (53 * hash) + getSymbol().hashCode();
    if (getSessionsCount() > 0) {
      hash = (37 * hash) + SESSIONS_FIELD_NUMBER;
      hash = (53 * hash) + getSessionsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.tradeapi.v1.assets.ScheduleResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.tradeapi.v1.assets.ScheduleResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.tradeapi.v1.assets.ScheduleResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.tradeapi.v1.assets.ScheduleResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.tradeapi.v1.assets.ScheduleResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.tradeapi.v1.assets.ScheduleResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.tradeapi.v1.assets.ScheduleResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.tradeapi.v1.assets.ScheduleResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static grpc.tradeapi.v1.assets.ScheduleResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static grpc.tradeapi.v1.assets.ScheduleResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.tradeapi.v1.assets.ScheduleResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.tradeapi.v1.assets.ScheduleResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.tradeapi.v1.assets.ScheduleResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Расписание инструмента
   * </pre>
   *
   * Protobuf type {@code grpc.tradeapi.v1.assets.ScheduleResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:grpc.tradeapi.v1.assets.ScheduleResponse)
      grpc.tradeapi.v1.assets.ScheduleResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.tradeapi.v1.assets.AssetsServiceOuterClass.internal_static_grpc_tradeapi_v1_assets_ScheduleResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.tradeapi.v1.assets.AssetsServiceOuterClass.internal_static_grpc_tradeapi_v1_assets_ScheduleResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.tradeapi.v1.assets.ScheduleResponse.class, grpc.tradeapi.v1.assets.ScheduleResponse.Builder.class);
    }

    // Construct using grpc.tradeapi.v1.assets.ScheduleResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      symbol_ = "";
      if (sessionsBuilder_ == null) {
        sessions_ = java.util.Collections.emptyList();
      } else {
        sessions_ = null;
        sessionsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.tradeapi.v1.assets.AssetsServiceOuterClass.internal_static_grpc_tradeapi_v1_assets_ScheduleResponse_descriptor;
    }

    @java.lang.Override
    public grpc.tradeapi.v1.assets.ScheduleResponse getDefaultInstanceForType() {
      return grpc.tradeapi.v1.assets.ScheduleResponse.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.tradeapi.v1.assets.ScheduleResponse build() {
      grpc.tradeapi.v1.assets.ScheduleResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.tradeapi.v1.assets.ScheduleResponse buildPartial() {
      grpc.tradeapi.v1.assets.ScheduleResponse result = new grpc.tradeapi.v1.assets.ScheduleResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(grpc.tradeapi.v1.assets.ScheduleResponse result) {
      if (sessionsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          sessions_ = java.util.Collections.unmodifiableList(sessions_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.sessions_ = sessions_;
      } else {
        result.sessions_ = sessionsBuilder_.build();
      }
    }

    private void buildPartial0(grpc.tradeapi.v1.assets.ScheduleResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.symbol_ = symbol_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.tradeapi.v1.assets.ScheduleResponse) {
        return mergeFrom((grpc.tradeapi.v1.assets.ScheduleResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.tradeapi.v1.assets.ScheduleResponse other) {
      if (other == grpc.tradeapi.v1.assets.ScheduleResponse.getDefaultInstance()) return this;
      if (!other.getSymbol().isEmpty()) {
        symbol_ = other.symbol_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (sessionsBuilder_ == null) {
        if (!other.sessions_.isEmpty()) {
          if (sessions_.isEmpty()) {
            sessions_ = other.sessions_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureSessionsIsMutable();
            sessions_.addAll(other.sessions_);
          }
          onChanged();
        }
      } else {
        if (!other.sessions_.isEmpty()) {
          if (sessionsBuilder_.isEmpty()) {
            sessionsBuilder_.dispose();
            sessionsBuilder_ = null;
            sessions_ = other.sessions_;
            bitField0_ = (bitField0_ & ~0x00000002);
            sessionsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSessionsFieldBuilder() : null;
          } else {
            sessionsBuilder_.addAllMessages(other.sessions_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              symbol_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              grpc.tradeapi.v1.assets.ScheduleResponse.Sessions m =
                  input.readMessage(
                      grpc.tradeapi.v1.assets.ScheduleResponse.Sessions.parser(),
                      extensionRegistry);
              if (sessionsBuilder_ == null) {
                ensureSessionsIsMutable();
                sessions_.add(m);
              } else {
                sessionsBuilder_.addMessage(m);
              }
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object symbol_ = "";
    /**
     * <pre>
     * Символ инструмента
     * </pre>
     *
     * <code>string symbol = 1;</code>
     * @return The symbol.
     */
    public java.lang.String getSymbol() {
      java.lang.Object ref = symbol_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        symbol_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Символ инструмента
     * </pre>
     *
     * <code>string symbol = 1;</code>
     * @return The bytes for symbol.
     */
    public com.google.protobuf.ByteString
        getSymbolBytes() {
      java.lang.Object ref = symbol_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        symbol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Символ инструмента
     * </pre>
     *
     * <code>string symbol = 1;</code>
     * @param value The symbol to set.
     * @return This builder for chaining.
     */
    public Builder setSymbol(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      symbol_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Символ инструмента
     * </pre>
     *
     * <code>string symbol = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSymbol() {
      symbol_ = getDefaultInstance().getSymbol();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Символ инструмента
     * </pre>
     *
     * <code>string symbol = 1;</code>
     * @param value The bytes for symbol to set.
     * @return This builder for chaining.
     */
    public Builder setSymbolBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      symbol_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.util.List<grpc.tradeapi.v1.assets.ScheduleResponse.Sessions> sessions_ =
      java.util.Collections.emptyList();
    private void ensureSessionsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        sessions_ = new java.util.ArrayList<grpc.tradeapi.v1.assets.ScheduleResponse.Sessions>(sessions_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        grpc.tradeapi.v1.assets.ScheduleResponse.Sessions, grpc.tradeapi.v1.assets.ScheduleResponse.Sessions.Builder, grpc.tradeapi.v1.assets.ScheduleResponse.SessionsOrBuilder> sessionsBuilder_;

    /**
     * <pre>
     * Сессии инструмента
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.assets.ScheduleResponse.Sessions sessions = 2;</code>
     */
    public java.util.List<grpc.tradeapi.v1.assets.ScheduleResponse.Sessions> getSessionsList() {
      if (sessionsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(sessions_);
      } else {
        return sessionsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Сессии инструмента
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.assets.ScheduleResponse.Sessions sessions = 2;</code>
     */
    public int getSessionsCount() {
      if (sessionsBuilder_ == null) {
        return sessions_.size();
      } else {
        return sessionsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Сессии инструмента
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.assets.ScheduleResponse.Sessions sessions = 2;</code>
     */
    public grpc.tradeapi.v1.assets.ScheduleResponse.Sessions getSessions(int index) {
      if (sessionsBuilder_ == null) {
        return sessions_.get(index);
      } else {
        return sessionsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Сессии инструмента
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.assets.ScheduleResponse.Sessions sessions = 2;</code>
     */
    public Builder setSessions(
        int index, grpc.tradeapi.v1.assets.ScheduleResponse.Sessions value) {
      if (sessionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSessionsIsMutable();
        sessions_.set(index, value);
        onChanged();
      } else {
        sessionsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Сессии инструмента
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.assets.ScheduleResponse.Sessions sessions = 2;</code>
     */
    public Builder setSessions(
        int index, grpc.tradeapi.v1.assets.ScheduleResponse.Sessions.Builder builderForValue) {
      if (sessionsBuilder_ == null) {
        ensureSessionsIsMutable();
        sessions_.set(index, builderForValue.build());
        onChanged();
      } else {
        sessionsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Сессии инструмента
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.assets.ScheduleResponse.Sessions sessions = 2;</code>
     */
    public Builder addSessions(grpc.tradeapi.v1.assets.ScheduleResponse.Sessions value) {
      if (sessionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSessionsIsMutable();
        sessions_.add(value);
        onChanged();
      } else {
        sessionsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Сессии инструмента
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.assets.ScheduleResponse.Sessions sessions = 2;</code>
     */
    public Builder addSessions(
        int index, grpc.tradeapi.v1.assets.ScheduleResponse.Sessions value) {
      if (sessionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSessionsIsMutable();
        sessions_.add(index, value);
        onChanged();
      } else {
        sessionsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Сессии инструмента
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.assets.ScheduleResponse.Sessions sessions = 2;</code>
     */
    public Builder addSessions(
        grpc.tradeapi.v1.assets.ScheduleResponse.Sessions.Builder builderForValue) {
      if (sessionsBuilder_ == null) {
        ensureSessionsIsMutable();
        sessions_.add(builderForValue.build());
        onChanged();
      } else {
        sessionsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Сессии инструмента
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.assets.ScheduleResponse.Sessions sessions = 2;</code>
     */
    public Builder addSessions(
        int index, grpc.tradeapi.v1.assets.ScheduleResponse.Sessions.Builder builderForValue) {
      if (sessionsBuilder_ == null) {
        ensureSessionsIsMutable();
        sessions_.add(index, builderForValue.build());
        onChanged();
      } else {
        sessionsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Сессии инструмента
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.assets.ScheduleResponse.Sessions sessions = 2;</code>
     */
    public Builder addAllSessions(
        java.lang.Iterable<? extends grpc.tradeapi.v1.assets.ScheduleResponse.Sessions> values) {
      if (sessionsBuilder_ == null) {
        ensureSessionsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, sessions_);
        onChanged();
      } else {
        sessionsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Сессии инструмента
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.assets.ScheduleResponse.Sessions sessions = 2;</code>
     */
    public Builder clearSessions() {
      if (sessionsBuilder_ == null) {
        sessions_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        sessionsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Сессии инструмента
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.assets.ScheduleResponse.Sessions sessions = 2;</code>
     */
    public Builder removeSessions(int index) {
      if (sessionsBuilder_ == null) {
        ensureSessionsIsMutable();
        sessions_.remove(index);
        onChanged();
      } else {
        sessionsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Сессии инструмента
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.assets.ScheduleResponse.Sessions sessions = 2;</code>
     */
    public grpc.tradeapi.v1.assets.ScheduleResponse.Sessions.Builder getSessionsBuilder(
        int index) {
      return getSessionsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Сессии инструмента
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.assets.ScheduleResponse.Sessions sessions = 2;</code>
     */
    public grpc.tradeapi.v1.assets.ScheduleResponse.SessionsOrBuilder getSessionsOrBuilder(
        int index) {
      if (sessionsBuilder_ == null) {
        return sessions_.get(index);  } else {
        return sessionsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Сессии инструмента
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.assets.ScheduleResponse.Sessions sessions = 2;</code>
     */
    public java.util.List<? extends grpc.tradeapi.v1.assets.ScheduleResponse.SessionsOrBuilder> 
         getSessionsOrBuilderList() {
      if (sessionsBuilder_ != null) {
        return sessionsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(sessions_);
      }
    }
    /**
     * <pre>
     * Сессии инструмента
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.assets.ScheduleResponse.Sessions sessions = 2;</code>
     */
    public grpc.tradeapi.v1.assets.ScheduleResponse.Sessions.Builder addSessionsBuilder() {
      return getSessionsFieldBuilder().addBuilder(
          grpc.tradeapi.v1.assets.ScheduleResponse.Sessions.getDefaultInstance());
    }
    /**
     * <pre>
     * Сессии инструмента
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.assets.ScheduleResponse.Sessions sessions = 2;</code>
     */
    public grpc.tradeapi.v1.assets.ScheduleResponse.Sessions.Builder addSessionsBuilder(
        int index) {
      return getSessionsFieldBuilder().addBuilder(
          index, grpc.tradeapi.v1.assets.ScheduleResponse.Sessions.getDefaultInstance());
    }
    /**
     * <pre>
     * Сессии инструмента
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.assets.ScheduleResponse.Sessions sessions = 2;</code>
     */
    public java.util.List<grpc.tradeapi.v1.assets.ScheduleResponse.Sessions.Builder> 
         getSessionsBuilderList() {
      return getSessionsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        grpc.tradeapi.v1.assets.ScheduleResponse.Sessions, grpc.tradeapi.v1.assets.ScheduleResponse.Sessions.Builder, grpc.tradeapi.v1.assets.ScheduleResponse.SessionsOrBuilder> 
        getSessionsFieldBuilder() {
      if (sessionsBuilder_ == null) {
        sessionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            grpc.tradeapi.v1.assets.ScheduleResponse.Sessions, grpc.tradeapi.v1.assets.ScheduleResponse.Sessions.Builder, grpc.tradeapi.v1.assets.ScheduleResponse.SessionsOrBuilder>(
                sessions_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        sessions_ = null;
      }
      return sessionsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:grpc.tradeapi.v1.assets.ScheduleResponse)
  }

  // @@protoc_insertion_point(class_scope:grpc.tradeapi.v1.assets.ScheduleResponse)
  private static final grpc.tradeapi.v1.assets.ScheduleResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.tradeapi.v1.assets.ScheduleResponse();
  }

  public static grpc.tradeapi.v1.assets.ScheduleResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ScheduleResponse>
      PARSER = new com.google.protobuf.AbstractParser<ScheduleResponse>() {
    @java.lang.Override
    public ScheduleResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ScheduleResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ScheduleResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.tradeapi.v1.assets.ScheduleResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

