// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: orders/orders_service.proto

// Protobuf Java Version: 3.25.5
package grpc.tradeapi.v1.orders;

public interface OrdersResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.tradeapi.v1.orders.OrdersResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Заявки
   * </pre>
   *
   * <code>repeated .grpc.tradeapi.v1.orders.OrderState orders = 1;</code>
   */
  java.util.List<grpc.tradeapi.v1.orders.OrderState> 
      getOrdersList();
  /**
   * <pre>
   * Заявки
   * </pre>
   *
   * <code>repeated .grpc.tradeapi.v1.orders.OrderState orders = 1;</code>
   */
  grpc.tradeapi.v1.orders.OrderState getOrders(int index);
  /**
   * <pre>
   * Заявки
   * </pre>
   *
   * <code>repeated .grpc.tradeapi.v1.orders.OrderState orders = 1;</code>
   */
  int getOrdersCount();
  /**
   * <pre>
   * Заявки
   * </pre>
   *
   * <code>repeated .grpc.tradeapi.v1.orders.OrderState orders = 1;</code>
   */
  java.util.List<? extends grpc.tradeapi.v1.orders.OrderStateOrBuilder> 
      getOrdersOrBuilderList();
  /**
   * <pre>
   * Заявки
   * </pre>
   *
   * <code>repeated .grpc.tradeapi.v1.orders.OrderState orders = 1;</code>
   */
  grpc.tradeapi.v1.orders.OrderStateOrBuilder getOrdersOrBuilder(
      int index);
}
