// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: marketdata/marketdata_service.proto

// Protobuf Java Version: 3.25.5
package grpc.tradeapi.v1.marketdata;

/**
 * <pre>
 * Список агрегированных свеч
 * </pre>
 *
 * Protobuf type {@code grpc.tradeapi.v1.marketdata.BarsResponse}
 */
public final class BarsResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:grpc.tradeapi.v1.marketdata.BarsResponse)
    BarsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BarsResponse.newBuilder() to construct.
  private BarsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BarsResponse() {
    symbol_ = "";
    bars_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new BarsResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.tradeapi.v1.marketdata.MarketdataService.internal_static_grpc_tradeapi_v1_marketdata_BarsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.tradeapi.v1.marketdata.MarketdataService.internal_static_grpc_tradeapi_v1_marketdata_BarsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.tradeapi.v1.marketdata.BarsResponse.class, grpc.tradeapi.v1.marketdata.BarsResponse.Builder.class);
  }

  public static final int SYMBOL_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object symbol_ = "";
  /**
   * <pre>
   * Символ инструмента
   * </pre>
   *
   * <code>string symbol = 1;</code>
   * @return The symbol.
   */
  @java.lang.Override
  public java.lang.String getSymbol() {
    java.lang.Object ref = symbol_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      symbol_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Символ инструмента
   * </pre>
   *
   * <code>string symbol = 1;</code>
   * @return The bytes for symbol.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSymbolBytes() {
    java.lang.Object ref = symbol_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      symbol_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BARS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<grpc.tradeapi.v1.marketdata.Bar> bars_;
  /**
   * <pre>
   * Агрегированная свеча
   * </pre>
   *
   * <code>repeated .grpc.tradeapi.v1.marketdata.Bar bars = 2;</code>
   */
  @java.lang.Override
  public java.util.List<grpc.tradeapi.v1.marketdata.Bar> getBarsList() {
    return bars_;
  }
  /**
   * <pre>
   * Агрегированная свеча
   * </pre>
   *
   * <code>repeated .grpc.tradeapi.v1.marketdata.Bar bars = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends grpc.tradeapi.v1.marketdata.BarOrBuilder> 
      getBarsOrBuilderList() {
    return bars_;
  }
  /**
   * <pre>
   * Агрегированная свеча
   * </pre>
   *
   * <code>repeated .grpc.tradeapi.v1.marketdata.Bar bars = 2;</code>
   */
  @java.lang.Override
  public int getBarsCount() {
    return bars_.size();
  }
  /**
   * <pre>
   * Агрегированная свеча
   * </pre>
   *
   * <code>repeated .grpc.tradeapi.v1.marketdata.Bar bars = 2;</code>
   */
  @java.lang.Override
  public grpc.tradeapi.v1.marketdata.Bar getBars(int index) {
    return bars_.get(index);
  }
  /**
   * <pre>
   * Агрегированная свеча
   * </pre>
   *
   * <code>repeated .grpc.tradeapi.v1.marketdata.Bar bars = 2;</code>
   */
  @java.lang.Override
  public grpc.tradeapi.v1.marketdata.BarOrBuilder getBarsOrBuilder(
      int index) {
    return bars_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(symbol_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, symbol_);
    }
    for (int i = 0; i < bars_.size(); i++) {
      output.writeMessage(2, bars_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(symbol_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, symbol_);
    }
    for (int i = 0; i < bars_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, bars_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.tradeapi.v1.marketdata.BarsResponse)) {
      return super.equals(obj);
    }
    grpc.tradeapi.v1.marketdata.BarsResponse other = (grpc.tradeapi.v1.marketdata.BarsResponse) obj;

    if (!getSymbol()
        .equals(other.getSymbol())) return false;
    if (!getBarsList()
        .equals(other.getBarsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SYMBOL_FIELD_NUMBER;
    hash = (53 * hash) + getSymbol().hashCode();
    if (getBarsCount() > 0) {
      hash = (37 * hash) + BARS_FIELD_NUMBER;
      hash = (53 * hash) + getBarsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.tradeapi.v1.marketdata.BarsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.tradeapi.v1.marketdata.BarsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.tradeapi.v1.marketdata.BarsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.tradeapi.v1.marketdata.BarsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.tradeapi.v1.marketdata.BarsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.tradeapi.v1.marketdata.BarsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.tradeapi.v1.marketdata.BarsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.tradeapi.v1.marketdata.BarsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static grpc.tradeapi.v1.marketdata.BarsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static grpc.tradeapi.v1.marketdata.BarsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.tradeapi.v1.marketdata.BarsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.tradeapi.v1.marketdata.BarsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.tradeapi.v1.marketdata.BarsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Список агрегированных свеч
   * </pre>
   *
   * Protobuf type {@code grpc.tradeapi.v1.marketdata.BarsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:grpc.tradeapi.v1.marketdata.BarsResponse)
      grpc.tradeapi.v1.marketdata.BarsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.tradeapi.v1.marketdata.MarketdataService.internal_static_grpc_tradeapi_v1_marketdata_BarsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.tradeapi.v1.marketdata.MarketdataService.internal_static_grpc_tradeapi_v1_marketdata_BarsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.tradeapi.v1.marketdata.BarsResponse.class, grpc.tradeapi.v1.marketdata.BarsResponse.Builder.class);
    }

    // Construct using grpc.tradeapi.v1.marketdata.BarsResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      symbol_ = "";
      if (barsBuilder_ == null) {
        bars_ = java.util.Collections.emptyList();
      } else {
        bars_ = null;
        barsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.tradeapi.v1.marketdata.MarketdataService.internal_static_grpc_tradeapi_v1_marketdata_BarsResponse_descriptor;
    }

    @java.lang.Override
    public grpc.tradeapi.v1.marketdata.BarsResponse getDefaultInstanceForType() {
      return grpc.tradeapi.v1.marketdata.BarsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.tradeapi.v1.marketdata.BarsResponse build() {
      grpc.tradeapi.v1.marketdata.BarsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.tradeapi.v1.marketdata.BarsResponse buildPartial() {
      grpc.tradeapi.v1.marketdata.BarsResponse result = new grpc.tradeapi.v1.marketdata.BarsResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(grpc.tradeapi.v1.marketdata.BarsResponse result) {
      if (barsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          bars_ = java.util.Collections.unmodifiableList(bars_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.bars_ = bars_;
      } else {
        result.bars_ = barsBuilder_.build();
      }
    }

    private void buildPartial0(grpc.tradeapi.v1.marketdata.BarsResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.symbol_ = symbol_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.tradeapi.v1.marketdata.BarsResponse) {
        return mergeFrom((grpc.tradeapi.v1.marketdata.BarsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.tradeapi.v1.marketdata.BarsResponse other) {
      if (other == grpc.tradeapi.v1.marketdata.BarsResponse.getDefaultInstance()) return this;
      if (!other.getSymbol().isEmpty()) {
        symbol_ = other.symbol_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (barsBuilder_ == null) {
        if (!other.bars_.isEmpty()) {
          if (bars_.isEmpty()) {
            bars_ = other.bars_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureBarsIsMutable();
            bars_.addAll(other.bars_);
          }
          onChanged();
        }
      } else {
        if (!other.bars_.isEmpty()) {
          if (barsBuilder_.isEmpty()) {
            barsBuilder_.dispose();
            barsBuilder_ = null;
            bars_ = other.bars_;
            bitField0_ = (bitField0_ & ~0x00000002);
            barsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getBarsFieldBuilder() : null;
          } else {
            barsBuilder_.addAllMessages(other.bars_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              symbol_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              grpc.tradeapi.v1.marketdata.Bar m =
                  input.readMessage(
                      grpc.tradeapi.v1.marketdata.Bar.parser(),
                      extensionRegistry);
              if (barsBuilder_ == null) {
                ensureBarsIsMutable();
                bars_.add(m);
              } else {
                barsBuilder_.addMessage(m);
              }
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object symbol_ = "";
    /**
     * <pre>
     * Символ инструмента
     * </pre>
     *
     * <code>string symbol = 1;</code>
     * @return The symbol.
     */
    public java.lang.String getSymbol() {
      java.lang.Object ref = symbol_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        symbol_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Символ инструмента
     * </pre>
     *
     * <code>string symbol = 1;</code>
     * @return The bytes for symbol.
     */
    public com.google.protobuf.ByteString
        getSymbolBytes() {
      java.lang.Object ref = symbol_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        symbol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Символ инструмента
     * </pre>
     *
     * <code>string symbol = 1;</code>
     * @param value The symbol to set.
     * @return This builder for chaining.
     */
    public Builder setSymbol(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      symbol_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Символ инструмента
     * </pre>
     *
     * <code>string symbol = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSymbol() {
      symbol_ = getDefaultInstance().getSymbol();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Символ инструмента
     * </pre>
     *
     * <code>string symbol = 1;</code>
     * @param value The bytes for symbol to set.
     * @return This builder for chaining.
     */
    public Builder setSymbolBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      symbol_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.util.List<grpc.tradeapi.v1.marketdata.Bar> bars_ =
      java.util.Collections.emptyList();
    private void ensureBarsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        bars_ = new java.util.ArrayList<grpc.tradeapi.v1.marketdata.Bar>(bars_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        grpc.tradeapi.v1.marketdata.Bar, grpc.tradeapi.v1.marketdata.Bar.Builder, grpc.tradeapi.v1.marketdata.BarOrBuilder> barsBuilder_;

    /**
     * <pre>
     * Агрегированная свеча
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.marketdata.Bar bars = 2;</code>
     */
    public java.util.List<grpc.tradeapi.v1.marketdata.Bar> getBarsList() {
      if (barsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(bars_);
      } else {
        return barsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Агрегированная свеча
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.marketdata.Bar bars = 2;</code>
     */
    public int getBarsCount() {
      if (barsBuilder_ == null) {
        return bars_.size();
      } else {
        return barsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Агрегированная свеча
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.marketdata.Bar bars = 2;</code>
     */
    public grpc.tradeapi.v1.marketdata.Bar getBars(int index) {
      if (barsBuilder_ == null) {
        return bars_.get(index);
      } else {
        return barsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Агрегированная свеча
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.marketdata.Bar bars = 2;</code>
     */
    public Builder setBars(
        int index, grpc.tradeapi.v1.marketdata.Bar value) {
      if (barsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBarsIsMutable();
        bars_.set(index, value);
        onChanged();
      } else {
        barsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Агрегированная свеча
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.marketdata.Bar bars = 2;</code>
     */
    public Builder setBars(
        int index, grpc.tradeapi.v1.marketdata.Bar.Builder builderForValue) {
      if (barsBuilder_ == null) {
        ensureBarsIsMutable();
        bars_.set(index, builderForValue.build());
        onChanged();
      } else {
        barsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Агрегированная свеча
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.marketdata.Bar bars = 2;</code>
     */
    public Builder addBars(grpc.tradeapi.v1.marketdata.Bar value) {
      if (barsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBarsIsMutable();
        bars_.add(value);
        onChanged();
      } else {
        barsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Агрегированная свеча
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.marketdata.Bar bars = 2;</code>
     */
    public Builder addBars(
        int index, grpc.tradeapi.v1.marketdata.Bar value) {
      if (barsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBarsIsMutable();
        bars_.add(index, value);
        onChanged();
      } else {
        barsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Агрегированная свеча
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.marketdata.Bar bars = 2;</code>
     */
    public Builder addBars(
        grpc.tradeapi.v1.marketdata.Bar.Builder builderForValue) {
      if (barsBuilder_ == null) {
        ensureBarsIsMutable();
        bars_.add(builderForValue.build());
        onChanged();
      } else {
        barsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Агрегированная свеча
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.marketdata.Bar bars = 2;</code>
     */
    public Builder addBars(
        int index, grpc.tradeapi.v1.marketdata.Bar.Builder builderForValue) {
      if (barsBuilder_ == null) {
        ensureBarsIsMutable();
        bars_.add(index, builderForValue.build());
        onChanged();
      } else {
        barsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Агрегированная свеча
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.marketdata.Bar bars = 2;</code>
     */
    public Builder addAllBars(
        java.lang.Iterable<? extends grpc.tradeapi.v1.marketdata.Bar> values) {
      if (barsBuilder_ == null) {
        ensureBarsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, bars_);
        onChanged();
      } else {
        barsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Агрегированная свеча
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.marketdata.Bar bars = 2;</code>
     */
    public Builder clearBars() {
      if (barsBuilder_ == null) {
        bars_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        barsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Агрегированная свеча
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.marketdata.Bar bars = 2;</code>
     */
    public Builder removeBars(int index) {
      if (barsBuilder_ == null) {
        ensureBarsIsMutable();
        bars_.remove(index);
        onChanged();
      } else {
        barsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Агрегированная свеча
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.marketdata.Bar bars = 2;</code>
     */
    public grpc.tradeapi.v1.marketdata.Bar.Builder getBarsBuilder(
        int index) {
      return getBarsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Агрегированная свеча
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.marketdata.Bar bars = 2;</code>
     */
    public grpc.tradeapi.v1.marketdata.BarOrBuilder getBarsOrBuilder(
        int index) {
      if (barsBuilder_ == null) {
        return bars_.get(index);  } else {
        return barsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Агрегированная свеча
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.marketdata.Bar bars = 2;</code>
     */
    public java.util.List<? extends grpc.tradeapi.v1.marketdata.BarOrBuilder> 
         getBarsOrBuilderList() {
      if (barsBuilder_ != null) {
        return barsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(bars_);
      }
    }
    /**
     * <pre>
     * Агрегированная свеча
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.marketdata.Bar bars = 2;</code>
     */
    public grpc.tradeapi.v1.marketdata.Bar.Builder addBarsBuilder() {
      return getBarsFieldBuilder().addBuilder(
          grpc.tradeapi.v1.marketdata.Bar.getDefaultInstance());
    }
    /**
     * <pre>
     * Агрегированная свеча
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.marketdata.Bar bars = 2;</code>
     */
    public grpc.tradeapi.v1.marketdata.Bar.Builder addBarsBuilder(
        int index) {
      return getBarsFieldBuilder().addBuilder(
          index, grpc.tradeapi.v1.marketdata.Bar.getDefaultInstance());
    }
    /**
     * <pre>
     * Агрегированная свеча
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.marketdata.Bar bars = 2;</code>
     */
    public java.util.List<grpc.tradeapi.v1.marketdata.Bar.Builder> 
         getBarsBuilderList() {
      return getBarsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        grpc.tradeapi.v1.marketdata.Bar, grpc.tradeapi.v1.marketdata.Bar.Builder, grpc.tradeapi.v1.marketdata.BarOrBuilder> 
        getBarsFieldBuilder() {
      if (barsBuilder_ == null) {
        barsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            grpc.tradeapi.v1.marketdata.Bar, grpc.tradeapi.v1.marketdata.Bar.Builder, grpc.tradeapi.v1.marketdata.BarOrBuilder>(
                bars_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        bars_ = null;
      }
      return barsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:grpc.tradeapi.v1.marketdata.BarsResponse)
  }

  // @@protoc_insertion_point(class_scope:grpc.tradeapi.v1.marketdata.BarsResponse)
  private static final grpc.tradeapi.v1.marketdata.BarsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.tradeapi.v1.marketdata.BarsResponse();
  }

  public static grpc.tradeapi.v1.marketdata.BarsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BarsResponse>
      PARSER = new com.google.protobuf.AbstractParser<BarsResponse>() {
    @java.lang.Override
    public BarsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<BarsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BarsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.tradeapi.v1.marketdata.BarsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

