// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: marketdata/marketdata_service.proto

// Protobuf Java Version: 3.25.5
package grpc.tradeapi.v1.marketdata;

/**
 * <pre>
 * Запрос получения исторических данных по инструменту (агрегированные свечи)
 * </pre>
 *
 * Protobuf type {@code grpc.tradeapi.v1.marketdata.BarsRequest}
 */
public final class BarsRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:grpc.tradeapi.v1.marketdata.BarsRequest)
    BarsRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BarsRequest.newBuilder() to construct.
  private BarsRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BarsRequest() {
    symbol_ = "";
    timeframe_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new BarsRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.tradeapi.v1.marketdata.MarketdataService.internal_static_grpc_tradeapi_v1_marketdata_BarsRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.tradeapi.v1.marketdata.MarketdataService.internal_static_grpc_tradeapi_v1_marketdata_BarsRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.tradeapi.v1.marketdata.BarsRequest.class, grpc.tradeapi.v1.marketdata.BarsRequest.Builder.class);
  }

  private int bitField0_;
  public static final int SYMBOL_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object symbol_ = "";
  /**
   * <pre>
   * Символ инструмента
   * </pre>
   *
   * <code>string symbol = 1;</code>
   * @return The symbol.
   */
  @java.lang.Override
  public java.lang.String getSymbol() {
    java.lang.Object ref = symbol_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      symbol_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Символ инструмента
   * </pre>
   *
   * <code>string symbol = 1;</code>
   * @return The bytes for symbol.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSymbolBytes() {
    java.lang.Object ref = symbol_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      symbol_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMEFRAME_FIELD_NUMBER = 2;
  private int timeframe_ = 0;
  /**
   * <pre>
   * Необходимый таймфрейм
   * </pre>
   *
   * <code>.grpc.tradeapi.v1.marketdata.TimeFrame timeframe = 2;</code>
   * @return The enum numeric value on the wire for timeframe.
   */
  @java.lang.Override public int getTimeframeValue() {
    return timeframe_;
  }
  /**
   * <pre>
   * Необходимый таймфрейм
   * </pre>
   *
   * <code>.grpc.tradeapi.v1.marketdata.TimeFrame timeframe = 2;</code>
   * @return The timeframe.
   */
  @java.lang.Override public grpc.tradeapi.v1.marketdata.TimeFrame getTimeframe() {
    grpc.tradeapi.v1.marketdata.TimeFrame result = grpc.tradeapi.v1.marketdata.TimeFrame.forNumber(timeframe_);
    return result == null ? grpc.tradeapi.v1.marketdata.TimeFrame.UNRECOGNIZED : result;
  }

  public static final int INTERVAL_FIELD_NUMBER = 3;
  private com.google.type.Interval interval_;
  /**
   * <pre>
   * Начало и окончание запрашиваемого периода
   * </pre>
   *
   * <code>.google.type.Interval interval = 3;</code>
   * @return Whether the interval field is set.
   */
  @java.lang.Override
  public boolean hasInterval() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Начало и окончание запрашиваемого периода
   * </pre>
   *
   * <code>.google.type.Interval interval = 3;</code>
   * @return The interval.
   */
  @java.lang.Override
  public com.google.type.Interval getInterval() {
    return interval_ == null ? com.google.type.Interval.getDefaultInstance() : interval_;
  }
  /**
   * <pre>
   * Начало и окончание запрашиваемого периода
   * </pre>
   *
   * <code>.google.type.Interval interval = 3;</code>
   */
  @java.lang.Override
  public com.google.type.IntervalOrBuilder getIntervalOrBuilder() {
    return interval_ == null ? com.google.type.Interval.getDefaultInstance() : interval_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(symbol_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, symbol_);
    }
    if (timeframe_ != grpc.tradeapi.v1.marketdata.TimeFrame.TIME_FRAME_UNSPECIFIED.getNumber()) {
      output.writeEnum(2, timeframe_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(3, getInterval());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(symbol_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, symbol_);
    }
    if (timeframe_ != grpc.tradeapi.v1.marketdata.TimeFrame.TIME_FRAME_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, timeframe_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getInterval());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.tradeapi.v1.marketdata.BarsRequest)) {
      return super.equals(obj);
    }
    grpc.tradeapi.v1.marketdata.BarsRequest other = (grpc.tradeapi.v1.marketdata.BarsRequest) obj;

    if (!getSymbol()
        .equals(other.getSymbol())) return false;
    if (timeframe_ != other.timeframe_) return false;
    if (hasInterval() != other.hasInterval()) return false;
    if (hasInterval()) {
      if (!getInterval()
          .equals(other.getInterval())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SYMBOL_FIELD_NUMBER;
    hash = (53 * hash) + getSymbol().hashCode();
    hash = (37 * hash) + TIMEFRAME_FIELD_NUMBER;
    hash = (53 * hash) + timeframe_;
    if (hasInterval()) {
      hash = (37 * hash) + INTERVAL_FIELD_NUMBER;
      hash = (53 * hash) + getInterval().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.tradeapi.v1.marketdata.BarsRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.tradeapi.v1.marketdata.BarsRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.tradeapi.v1.marketdata.BarsRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.tradeapi.v1.marketdata.BarsRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.tradeapi.v1.marketdata.BarsRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.tradeapi.v1.marketdata.BarsRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.tradeapi.v1.marketdata.BarsRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.tradeapi.v1.marketdata.BarsRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static grpc.tradeapi.v1.marketdata.BarsRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static grpc.tradeapi.v1.marketdata.BarsRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.tradeapi.v1.marketdata.BarsRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.tradeapi.v1.marketdata.BarsRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.tradeapi.v1.marketdata.BarsRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Запрос получения исторических данных по инструменту (агрегированные свечи)
   * </pre>
   *
   * Protobuf type {@code grpc.tradeapi.v1.marketdata.BarsRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:grpc.tradeapi.v1.marketdata.BarsRequest)
      grpc.tradeapi.v1.marketdata.BarsRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.tradeapi.v1.marketdata.MarketdataService.internal_static_grpc_tradeapi_v1_marketdata_BarsRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.tradeapi.v1.marketdata.MarketdataService.internal_static_grpc_tradeapi_v1_marketdata_BarsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.tradeapi.v1.marketdata.BarsRequest.class, grpc.tradeapi.v1.marketdata.BarsRequest.Builder.class);
    }

    // Construct using grpc.tradeapi.v1.marketdata.BarsRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getIntervalFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      symbol_ = "";
      timeframe_ = 0;
      interval_ = null;
      if (intervalBuilder_ != null) {
        intervalBuilder_.dispose();
        intervalBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.tradeapi.v1.marketdata.MarketdataService.internal_static_grpc_tradeapi_v1_marketdata_BarsRequest_descriptor;
    }

    @java.lang.Override
    public grpc.tradeapi.v1.marketdata.BarsRequest getDefaultInstanceForType() {
      return grpc.tradeapi.v1.marketdata.BarsRequest.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.tradeapi.v1.marketdata.BarsRequest build() {
      grpc.tradeapi.v1.marketdata.BarsRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.tradeapi.v1.marketdata.BarsRequest buildPartial() {
      grpc.tradeapi.v1.marketdata.BarsRequest result = new grpc.tradeapi.v1.marketdata.BarsRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(grpc.tradeapi.v1.marketdata.BarsRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.symbol_ = symbol_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.timeframe_ = timeframe_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.interval_ = intervalBuilder_ == null
            ? interval_
            : intervalBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.tradeapi.v1.marketdata.BarsRequest) {
        return mergeFrom((grpc.tradeapi.v1.marketdata.BarsRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.tradeapi.v1.marketdata.BarsRequest other) {
      if (other == grpc.tradeapi.v1.marketdata.BarsRequest.getDefaultInstance()) return this;
      if (!other.getSymbol().isEmpty()) {
        symbol_ = other.symbol_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.timeframe_ != 0) {
        setTimeframeValue(other.getTimeframeValue());
      }
      if (other.hasInterval()) {
        mergeInterval(other.getInterval());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              symbol_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              timeframe_ = input.readEnum();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              input.readMessage(
                  getIntervalFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object symbol_ = "";
    /**
     * <pre>
     * Символ инструмента
     * </pre>
     *
     * <code>string symbol = 1;</code>
     * @return The symbol.
     */
    public java.lang.String getSymbol() {
      java.lang.Object ref = symbol_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        symbol_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Символ инструмента
     * </pre>
     *
     * <code>string symbol = 1;</code>
     * @return The bytes for symbol.
     */
    public com.google.protobuf.ByteString
        getSymbolBytes() {
      java.lang.Object ref = symbol_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        symbol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Символ инструмента
     * </pre>
     *
     * <code>string symbol = 1;</code>
     * @param value The symbol to set.
     * @return This builder for chaining.
     */
    public Builder setSymbol(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      symbol_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Символ инструмента
     * </pre>
     *
     * <code>string symbol = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSymbol() {
      symbol_ = getDefaultInstance().getSymbol();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Символ инструмента
     * </pre>
     *
     * <code>string symbol = 1;</code>
     * @param value The bytes for symbol to set.
     * @return This builder for chaining.
     */
    public Builder setSymbolBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      symbol_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int timeframe_ = 0;
    /**
     * <pre>
     * Необходимый таймфрейм
     * </pre>
     *
     * <code>.grpc.tradeapi.v1.marketdata.TimeFrame timeframe = 2;</code>
     * @return The enum numeric value on the wire for timeframe.
     */
    @java.lang.Override public int getTimeframeValue() {
      return timeframe_;
    }
    /**
     * <pre>
     * Необходимый таймфрейм
     * </pre>
     *
     * <code>.grpc.tradeapi.v1.marketdata.TimeFrame timeframe = 2;</code>
     * @param value The enum numeric value on the wire for timeframe to set.
     * @return This builder for chaining.
     */
    public Builder setTimeframeValue(int value) {
      timeframe_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Необходимый таймфрейм
     * </pre>
     *
     * <code>.grpc.tradeapi.v1.marketdata.TimeFrame timeframe = 2;</code>
     * @return The timeframe.
     */
    @java.lang.Override
    public grpc.tradeapi.v1.marketdata.TimeFrame getTimeframe() {
      grpc.tradeapi.v1.marketdata.TimeFrame result = grpc.tradeapi.v1.marketdata.TimeFrame.forNumber(timeframe_);
      return result == null ? grpc.tradeapi.v1.marketdata.TimeFrame.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Необходимый таймфрейм
     * </pre>
     *
     * <code>.grpc.tradeapi.v1.marketdata.TimeFrame timeframe = 2;</code>
     * @param value The timeframe to set.
     * @return This builder for chaining.
     */
    public Builder setTimeframe(grpc.tradeapi.v1.marketdata.TimeFrame value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000002;
      timeframe_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Необходимый таймфрейм
     * </pre>
     *
     * <code>.grpc.tradeapi.v1.marketdata.TimeFrame timeframe = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimeframe() {
      bitField0_ = (bitField0_ & ~0x00000002);
      timeframe_ = 0;
      onChanged();
      return this;
    }

    private com.google.type.Interval interval_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.type.Interval, com.google.type.Interval.Builder, com.google.type.IntervalOrBuilder> intervalBuilder_;
    /**
     * <pre>
     * Начало и окончание запрашиваемого периода
     * </pre>
     *
     * <code>.google.type.Interval interval = 3;</code>
     * @return Whether the interval field is set.
     */
    public boolean hasInterval() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * Начало и окончание запрашиваемого периода
     * </pre>
     *
     * <code>.google.type.Interval interval = 3;</code>
     * @return The interval.
     */
    public com.google.type.Interval getInterval() {
      if (intervalBuilder_ == null) {
        return interval_ == null ? com.google.type.Interval.getDefaultInstance() : interval_;
      } else {
        return intervalBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Начало и окончание запрашиваемого периода
     * </pre>
     *
     * <code>.google.type.Interval interval = 3;</code>
     */
    public Builder setInterval(com.google.type.Interval value) {
      if (intervalBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        interval_ = value;
      } else {
        intervalBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Начало и окончание запрашиваемого периода
     * </pre>
     *
     * <code>.google.type.Interval interval = 3;</code>
     */
    public Builder setInterval(
        com.google.type.Interval.Builder builderForValue) {
      if (intervalBuilder_ == null) {
        interval_ = builderForValue.build();
      } else {
        intervalBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Начало и окончание запрашиваемого периода
     * </pre>
     *
     * <code>.google.type.Interval interval = 3;</code>
     */
    public Builder mergeInterval(com.google.type.Interval value) {
      if (intervalBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          interval_ != null &&
          interval_ != com.google.type.Interval.getDefaultInstance()) {
          getIntervalBuilder().mergeFrom(value);
        } else {
          interval_ = value;
        }
      } else {
        intervalBuilder_.mergeFrom(value);
      }
      if (interval_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Начало и окончание запрашиваемого периода
     * </pre>
     *
     * <code>.google.type.Interval interval = 3;</code>
     */
    public Builder clearInterval() {
      bitField0_ = (bitField0_ & ~0x00000004);
      interval_ = null;
      if (intervalBuilder_ != null) {
        intervalBuilder_.dispose();
        intervalBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Начало и окончание запрашиваемого периода
     * </pre>
     *
     * <code>.google.type.Interval interval = 3;</code>
     */
    public com.google.type.Interval.Builder getIntervalBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getIntervalFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Начало и окончание запрашиваемого периода
     * </pre>
     *
     * <code>.google.type.Interval interval = 3;</code>
     */
    public com.google.type.IntervalOrBuilder getIntervalOrBuilder() {
      if (intervalBuilder_ != null) {
        return intervalBuilder_.getMessageOrBuilder();
      } else {
        return interval_ == null ?
            com.google.type.Interval.getDefaultInstance() : interval_;
      }
    }
    /**
     * <pre>
     * Начало и окончание запрашиваемого периода
     * </pre>
     *
     * <code>.google.type.Interval interval = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.type.Interval, com.google.type.Interval.Builder, com.google.type.IntervalOrBuilder> 
        getIntervalFieldBuilder() {
      if (intervalBuilder_ == null) {
        intervalBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.type.Interval, com.google.type.Interval.Builder, com.google.type.IntervalOrBuilder>(
                getInterval(),
                getParentForChildren(),
                isClean());
        interval_ = null;
      }
      return intervalBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:grpc.tradeapi.v1.marketdata.BarsRequest)
  }

  // @@protoc_insertion_point(class_scope:grpc.tradeapi.v1.marketdata.BarsRequest)
  private static final grpc.tradeapi.v1.marketdata.BarsRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.tradeapi.v1.marketdata.BarsRequest();
  }

  public static grpc.tradeapi.v1.marketdata.BarsRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BarsRequest>
      PARSER = new com.google.protobuf.AbstractParser<BarsRequest>() {
    @java.lang.Override
    public BarsRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<BarsRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BarsRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.tradeapi.v1.marketdata.BarsRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

