// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: marketdata/marketdata_service.proto

// Protobuf Java Version: 3.25.5
package grpc.tradeapi.v1.marketdata;

public interface QuoteResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.tradeapi.v1.marketdata.QuoteResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Символ инструмента
   * </pre>
   *
   * <code>string symbol = 1;</code>
   * @return The symbol.
   */
  java.lang.String getSymbol();
  /**
   * <pre>
   * Символ инструмента
   * </pre>
   *
   * <code>string symbol = 1;</code>
   * @return The bytes for symbol.
   */
  com.google.protobuf.ByteString
      getSymbolBytes();

  /**
   * <pre>
   * Цена последней сделки
   * </pre>
   *
   * <code>.grpc.tradeapi.v1.marketdata.Quote quote = 2;</code>
   * @return Whether the quote field is set.
   */
  boolean hasQuote();
  /**
   * <pre>
   * Цена последней сделки
   * </pre>
   *
   * <code>.grpc.tradeapi.v1.marketdata.Quote quote = 2;</code>
   * @return The quote.
   */
  grpc.tradeapi.v1.marketdata.Quote getQuote();
  /**
   * <pre>
   * Цена последней сделки
   * </pre>
   *
   * <code>.grpc.tradeapi.v1.marketdata.Quote quote = 2;</code>
   */
  grpc.tradeapi.v1.marketdata.QuoteOrBuilder getQuoteOrBuilder();
}
