// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: marketdata/marketdata_service.proto

// Protobuf Java Version: 3.25.5
package grpc.tradeapi.v1.marketdata;

public interface SubscribeQuoteResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.tradeapi.v1.marketdata.SubscribeQuoteResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Список котировок
   * </pre>
   *
   * <code>repeated .grpc.tradeapi.v1.marketdata.Quote quote = 1;</code>
   */
  java.util.List<grpc.tradeapi.v1.marketdata.Quote> 
      getQuoteList();
  /**
   * <pre>
   * Список котировок
   * </pre>
   *
   * <code>repeated .grpc.tradeapi.v1.marketdata.Quote quote = 1;</code>
   */
  grpc.tradeapi.v1.marketdata.Quote getQuote(int index);
  /**
   * <pre>
   * Список котировок
   * </pre>
   *
   * <code>repeated .grpc.tradeapi.v1.marketdata.Quote quote = 1;</code>
   */
  int getQuoteCount();
  /**
   * <pre>
   * Список котировок
   * </pre>
   *
   * <code>repeated .grpc.tradeapi.v1.marketdata.Quote quote = 1;</code>
   */
  java.util.List<? extends grpc.tradeapi.v1.marketdata.QuoteOrBuilder> 
      getQuoteOrBuilderList();
  /**
   * <pre>
   * Список котировок
   * </pre>
   *
   * <code>repeated .grpc.tradeapi.v1.marketdata.Quote quote = 1;</code>
   */
  grpc.tradeapi.v1.marketdata.QuoteOrBuilder getQuoteOrBuilder(
      int index);

  /**
   * <pre>
   * Ошибка стрим сервиса
   * </pre>
   *
   * <code>.grpc.tradeapi.v1.marketdata.StreamError error = 2;</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <pre>
   * Ошибка стрим сервиса
   * </pre>
   *
   * <code>.grpc.tradeapi.v1.marketdata.StreamError error = 2;</code>
   * @return The error.
   */
  grpc.tradeapi.v1.marketdata.StreamError getError();
  /**
   * <pre>
   * Ошибка стрим сервиса
   * </pre>
   *
   * <code>.grpc.tradeapi.v1.marketdata.StreamError error = 2;</code>
   */
  grpc.tradeapi.v1.marketdata.StreamErrorOrBuilder getErrorOrBuilder();
}
