// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth/auth_service.proto

// Protobuf Java Version: 3.25.5
package grpc.tradeapi.v1.auth;

public interface TokenDetailsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.tradeapi.v1.auth.TokenDetailsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * JWT-токен
   * </pre>
   *
   * <code>string token = 1;</code>
   * @return The token.
   */
  java.lang.String getToken();
  /**
   * <pre>
   * JWT-токен
   * </pre>
   *
   * <code>string token = 1;</code>
   * @return The bytes for token.
   */
  com.google.protobuf.ByteString
      getTokenBytes();
}
