// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: accounts/accounts_service.proto

// Protobuf Java Version: 3.25.5
package grpc.tradeapi.v1.accounts;

/**
 * <pre>
 * Информация о конкретном аккаунте
 * </pre>
 *
 * Protobuf type {@code grpc.tradeapi.v1.accounts.GetAccountResponse}
 */
public final class GetAccountResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:grpc.tradeapi.v1.accounts.GetAccountResponse)
    GetAccountResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetAccountResponse.newBuilder() to construct.
  private GetAccountResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetAccountResponse() {
    accountId_ = "";
    type_ = "";
    status_ = "";
    positions_ = java.util.Collections.emptyList();
    cash_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetAccountResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.tradeapi.v1.accounts.AccountsServiceOuterClass.internal_static_grpc_tradeapi_v1_accounts_GetAccountResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.tradeapi.v1.accounts.AccountsServiceOuterClass.internal_static_grpc_tradeapi_v1_accounts_GetAccountResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.tradeapi.v1.accounts.GetAccountResponse.class, grpc.tradeapi.v1.accounts.GetAccountResponse.Builder.class);
  }

  private int bitField0_;
  private int portfolioCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object portfolio_;
  public enum PortfolioCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    PORTFOLIO_MC(8),
    PORTFOLIO_MCT(9),
    PORTFOLIO_FORTS(10),
    PORTFOLIO_NOT_SET(0);
    private final int value;
    private PortfolioCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PortfolioCase valueOf(int value) {
      return forNumber(value);
    }

    public static PortfolioCase forNumber(int value) {
      switch (value) {
        case 8: return PORTFOLIO_MC;
        case 9: return PORTFOLIO_MCT;
        case 10: return PORTFOLIO_FORTS;
        case 0: return PORTFOLIO_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public PortfolioCase
  getPortfolioCase() {
    return PortfolioCase.forNumber(
        portfolioCase_);
  }

  public static final int ACCOUNT_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object accountId_ = "";
  /**
   * <pre>
   * Идентификатор аккаунта
   * </pre>
   *
   * <code>string account_id = 1;</code>
   * @return The accountId.
   */
  @java.lang.Override
  public java.lang.String getAccountId() {
    java.lang.Object ref = accountId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      accountId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Идентификатор аккаунта
   * </pre>
   *
   * <code>string account_id = 1;</code>
   * @return The bytes for accountId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAccountIdBytes() {
    java.lang.Object ref = accountId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      accountId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TYPE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object type_ = "";
  /**
   * <pre>
   * Тип аккаунта
   * </pre>
   *
   * <code>string type = 2;</code>
   * @return The type.
   */
  @java.lang.Override
  public java.lang.String getType() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      type_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Тип аккаунта
   * </pre>
   *
   * <code>string type = 2;</code>
   * @return The bytes for type.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTypeBytes() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      type_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATUS_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object status_ = "";
  /**
   * <pre>
   * Статус аккаунта
   * </pre>
   *
   * <code>string status = 3;</code>
   * @return The status.
   */
  @java.lang.Override
  public java.lang.String getStatus() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      status_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Статус аккаунта
   * </pre>
   *
   * <code>string status = 3;</code>
   * @return The bytes for status.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStatusBytes() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      status_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EQUITY_FIELD_NUMBER = 4;
  private com.google.type.Decimal equity_;
  /**
   * <pre>
   * Доступные средства плюс стоимость открытых позиций
   * </pre>
   *
   * <code>.google.type.Decimal equity = 4;</code>
   * @return Whether the equity field is set.
   */
  @java.lang.Override
  public boolean hasEquity() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Доступные средства плюс стоимость открытых позиций
   * </pre>
   *
   * <code>.google.type.Decimal equity = 4;</code>
   * @return The equity.
   */
  @java.lang.Override
  public com.google.type.Decimal getEquity() {
    return equity_ == null ? com.google.type.Decimal.getDefaultInstance() : equity_;
  }
  /**
   * <pre>
   * Доступные средства плюс стоимость открытых позиций
   * </pre>
   *
   * <code>.google.type.Decimal equity = 4;</code>
   */
  @java.lang.Override
  public com.google.type.DecimalOrBuilder getEquityOrBuilder() {
    return equity_ == null ? com.google.type.Decimal.getDefaultInstance() : equity_;
  }

  public static final int UNREALIZED_PROFIT_FIELD_NUMBER = 5;
  private com.google.type.Decimal unrealizedProfit_;
  /**
   * <pre>
   * Нереализованная прибыль
   * </pre>
   *
   * <code>.google.type.Decimal unrealized_profit = 5;</code>
   * @return Whether the unrealizedProfit field is set.
   */
  @java.lang.Override
  public boolean hasUnrealizedProfit() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * Нереализованная прибыль
   * </pre>
   *
   * <code>.google.type.Decimal unrealized_profit = 5;</code>
   * @return The unrealizedProfit.
   */
  @java.lang.Override
  public com.google.type.Decimal getUnrealizedProfit() {
    return unrealizedProfit_ == null ? com.google.type.Decimal.getDefaultInstance() : unrealizedProfit_;
  }
  /**
   * <pre>
   * Нереализованная прибыль
   * </pre>
   *
   * <code>.google.type.Decimal unrealized_profit = 5;</code>
   */
  @java.lang.Override
  public com.google.type.DecimalOrBuilder getUnrealizedProfitOrBuilder() {
    return unrealizedProfit_ == null ? com.google.type.Decimal.getDefaultInstance() : unrealizedProfit_;
  }

  public static final int POSITIONS_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private java.util.List<grpc.tradeapi.v1.accounts.Position> positions_;
  /**
   * <pre>
   * Позиции. Открытые, плюс теоретические (по неисполненным активным заявкам)
   * </pre>
   *
   * <code>repeated .grpc.tradeapi.v1.accounts.Position positions = 6;</code>
   */
  @java.lang.Override
  public java.util.List<grpc.tradeapi.v1.accounts.Position> getPositionsList() {
    return positions_;
  }
  /**
   * <pre>
   * Позиции. Открытые, плюс теоретические (по неисполненным активным заявкам)
   * </pre>
   *
   * <code>repeated .grpc.tradeapi.v1.accounts.Position positions = 6;</code>
   */
  @java.lang.Override
  public java.util.List<? extends grpc.tradeapi.v1.accounts.PositionOrBuilder> 
      getPositionsOrBuilderList() {
    return positions_;
  }
  /**
   * <pre>
   * Позиции. Открытые, плюс теоретические (по неисполненным активным заявкам)
   * </pre>
   *
   * <code>repeated .grpc.tradeapi.v1.accounts.Position positions = 6;</code>
   */
  @java.lang.Override
  public int getPositionsCount() {
    return positions_.size();
  }
  /**
   * <pre>
   * Позиции. Открытые, плюс теоретические (по неисполненным активным заявкам)
   * </pre>
   *
   * <code>repeated .grpc.tradeapi.v1.accounts.Position positions = 6;</code>
   */
  @java.lang.Override
  public grpc.tradeapi.v1.accounts.Position getPositions(int index) {
    return positions_.get(index);
  }
  /**
   * <pre>
   * Позиции. Открытые, плюс теоретические (по неисполненным активным заявкам)
   * </pre>
   *
   * <code>repeated .grpc.tradeapi.v1.accounts.Position positions = 6;</code>
   */
  @java.lang.Override
  public grpc.tradeapi.v1.accounts.PositionOrBuilder getPositionsOrBuilder(
      int index) {
    return positions_.get(index);
  }

  public static final int CASH_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private java.util.List<com.google.type.Money> cash_;
  /**
   * <pre>
   * Сумма собственных денежных средств на счете, доступная для торговли. Не включает маржинальные средства.
   * </pre>
   *
   * <code>repeated .google.type.Money cash = 7;</code>
   */
  @java.lang.Override
  public java.util.List<com.google.type.Money> getCashList() {
    return cash_;
  }
  /**
   * <pre>
   * Сумма собственных денежных средств на счете, доступная для торговли. Не включает маржинальные средства.
   * </pre>
   *
   * <code>repeated .google.type.Money cash = 7;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.google.type.MoneyOrBuilder> 
      getCashOrBuilderList() {
    return cash_;
  }
  /**
   * <pre>
   * Сумма собственных денежных средств на счете, доступная для торговли. Не включает маржинальные средства.
   * </pre>
   *
   * <code>repeated .google.type.Money cash = 7;</code>
   */
  @java.lang.Override
  public int getCashCount() {
    return cash_.size();
  }
  /**
   * <pre>
   * Сумма собственных денежных средств на счете, доступная для торговли. Не включает маржинальные средства.
   * </pre>
   *
   * <code>repeated .google.type.Money cash = 7;</code>
   */
  @java.lang.Override
  public com.google.type.Money getCash(int index) {
    return cash_.get(index);
  }
  /**
   * <pre>
   * Сумма собственных денежных средств на счете, доступная для торговли. Не включает маржинальные средства.
   * </pre>
   *
   * <code>repeated .google.type.Money cash = 7;</code>
   */
  @java.lang.Override
  public com.google.type.MoneyOrBuilder getCashOrBuilder(
      int index) {
    return cash_.get(index);
  }

  public static final int PORTFOLIO_MC_FIELD_NUMBER = 8;
  /**
   * <code>.grpc.tradeapi.v1.accounts.MC portfolio_mc = 8;</code>
   * @return Whether the portfolioMc field is set.
   */
  @java.lang.Override
  public boolean hasPortfolioMc() {
    return portfolioCase_ == 8;
  }
  /**
   * <code>.grpc.tradeapi.v1.accounts.MC portfolio_mc = 8;</code>
   * @return The portfolioMc.
   */
  @java.lang.Override
  public grpc.tradeapi.v1.accounts.MC getPortfolioMc() {
    if (portfolioCase_ == 8) {
       return (grpc.tradeapi.v1.accounts.MC) portfolio_;
    }
    return grpc.tradeapi.v1.accounts.MC.getDefaultInstance();
  }
  /**
   * <code>.grpc.tradeapi.v1.accounts.MC portfolio_mc = 8;</code>
   */
  @java.lang.Override
  public grpc.tradeapi.v1.accounts.MCOrBuilder getPortfolioMcOrBuilder() {
    if (portfolioCase_ == 8) {
       return (grpc.tradeapi.v1.accounts.MC) portfolio_;
    }
    return grpc.tradeapi.v1.accounts.MC.getDefaultInstance();
  }

  public static final int PORTFOLIO_MCT_FIELD_NUMBER = 9;
  /**
   * <code>.grpc.tradeapi.v1.accounts.MCT portfolio_mct = 9;</code>
   * @return Whether the portfolioMct field is set.
   */
  @java.lang.Override
  public boolean hasPortfolioMct() {
    return portfolioCase_ == 9;
  }
  /**
   * <code>.grpc.tradeapi.v1.accounts.MCT portfolio_mct = 9;</code>
   * @return The portfolioMct.
   */
  @java.lang.Override
  public grpc.tradeapi.v1.accounts.MCT getPortfolioMct() {
    if (portfolioCase_ == 9) {
       return (grpc.tradeapi.v1.accounts.MCT) portfolio_;
    }
    return grpc.tradeapi.v1.accounts.MCT.getDefaultInstance();
  }
  /**
   * <code>.grpc.tradeapi.v1.accounts.MCT portfolio_mct = 9;</code>
   */
  @java.lang.Override
  public grpc.tradeapi.v1.accounts.MCTOrBuilder getPortfolioMctOrBuilder() {
    if (portfolioCase_ == 9) {
       return (grpc.tradeapi.v1.accounts.MCT) portfolio_;
    }
    return grpc.tradeapi.v1.accounts.MCT.getDefaultInstance();
  }

  public static final int PORTFOLIO_FORTS_FIELD_NUMBER = 10;
  /**
   * <code>.grpc.tradeapi.v1.accounts.FORTS portfolio_forts = 10;</code>
   * @return Whether the portfolioForts field is set.
   */
  @java.lang.Override
  public boolean hasPortfolioForts() {
    return portfolioCase_ == 10;
  }
  /**
   * <code>.grpc.tradeapi.v1.accounts.FORTS portfolio_forts = 10;</code>
   * @return The portfolioForts.
   */
  @java.lang.Override
  public grpc.tradeapi.v1.accounts.FORTS getPortfolioForts() {
    if (portfolioCase_ == 10) {
       return (grpc.tradeapi.v1.accounts.FORTS) portfolio_;
    }
    return grpc.tradeapi.v1.accounts.FORTS.getDefaultInstance();
  }
  /**
   * <code>.grpc.tradeapi.v1.accounts.FORTS portfolio_forts = 10;</code>
   */
  @java.lang.Override
  public grpc.tradeapi.v1.accounts.FORTSOrBuilder getPortfolioFortsOrBuilder() {
    if (portfolioCase_ == 10) {
       return (grpc.tradeapi.v1.accounts.FORTS) portfolio_;
    }
    return grpc.tradeapi.v1.accounts.FORTS.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(accountId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, accountId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(type_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, type_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(status_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, status_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(4, getEquity());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(5, getUnrealizedProfit());
    }
    for (int i = 0; i < positions_.size(); i++) {
      output.writeMessage(6, positions_.get(i));
    }
    for (int i = 0; i < cash_.size(); i++) {
      output.writeMessage(7, cash_.get(i));
    }
    if (portfolioCase_ == 8) {
      output.writeMessage(8, (grpc.tradeapi.v1.accounts.MC) portfolio_);
    }
    if (portfolioCase_ == 9) {
      output.writeMessage(9, (grpc.tradeapi.v1.accounts.MCT) portfolio_);
    }
    if (portfolioCase_ == 10) {
      output.writeMessage(10, (grpc.tradeapi.v1.accounts.FORTS) portfolio_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(accountId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, accountId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(type_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, type_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(status_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, status_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getEquity());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getUnrealizedProfit());
    }
    for (int i = 0; i < positions_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, positions_.get(i));
    }
    for (int i = 0; i < cash_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, cash_.get(i));
    }
    if (portfolioCase_ == 8) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, (grpc.tradeapi.v1.accounts.MC) portfolio_);
    }
    if (portfolioCase_ == 9) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, (grpc.tradeapi.v1.accounts.MCT) portfolio_);
    }
    if (portfolioCase_ == 10) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, (grpc.tradeapi.v1.accounts.FORTS) portfolio_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.tradeapi.v1.accounts.GetAccountResponse)) {
      return super.equals(obj);
    }
    grpc.tradeapi.v1.accounts.GetAccountResponse other = (grpc.tradeapi.v1.accounts.GetAccountResponse) obj;

    if (!getAccountId()
        .equals(other.getAccountId())) return false;
    if (!getType()
        .equals(other.getType())) return false;
    if (!getStatus()
        .equals(other.getStatus())) return false;
    if (hasEquity() != other.hasEquity()) return false;
    if (hasEquity()) {
      if (!getEquity()
          .equals(other.getEquity())) return false;
    }
    if (hasUnrealizedProfit() != other.hasUnrealizedProfit()) return false;
    if (hasUnrealizedProfit()) {
      if (!getUnrealizedProfit()
          .equals(other.getUnrealizedProfit())) return false;
    }
    if (!getPositionsList()
        .equals(other.getPositionsList())) return false;
    if (!getCashList()
        .equals(other.getCashList())) return false;
    if (!getPortfolioCase().equals(other.getPortfolioCase())) return false;
    switch (portfolioCase_) {
      case 8:
        if (!getPortfolioMc()
            .equals(other.getPortfolioMc())) return false;
        break;
      case 9:
        if (!getPortfolioMct()
            .equals(other.getPortfolioMct())) return false;
        break;
      case 10:
        if (!getPortfolioForts()
            .equals(other.getPortfolioForts())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ACCOUNT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getAccountId().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getType().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus().hashCode();
    if (hasEquity()) {
      hash = (37 * hash) + EQUITY_FIELD_NUMBER;
      hash = (53 * hash) + getEquity().hashCode();
    }
    if (hasUnrealizedProfit()) {
      hash = (37 * hash) + UNREALIZED_PROFIT_FIELD_NUMBER;
      hash = (53 * hash) + getUnrealizedProfit().hashCode();
    }
    if (getPositionsCount() > 0) {
      hash = (37 * hash) + POSITIONS_FIELD_NUMBER;
      hash = (53 * hash) + getPositionsList().hashCode();
    }
    if (getCashCount() > 0) {
      hash = (37 * hash) + CASH_FIELD_NUMBER;
      hash = (53 * hash) + getCashList().hashCode();
    }
    switch (portfolioCase_) {
      case 8:
        hash = (37 * hash) + PORTFOLIO_MC_FIELD_NUMBER;
        hash = (53 * hash) + getPortfolioMc().hashCode();
        break;
      case 9:
        hash = (37 * hash) + PORTFOLIO_MCT_FIELD_NUMBER;
        hash = (53 * hash) + getPortfolioMct().hashCode();
        break;
      case 10:
        hash = (37 * hash) + PORTFOLIO_FORTS_FIELD_NUMBER;
        hash = (53 * hash) + getPortfolioForts().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.tradeapi.v1.accounts.GetAccountResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.tradeapi.v1.accounts.GetAccountResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.tradeapi.v1.accounts.GetAccountResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.tradeapi.v1.accounts.GetAccountResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.tradeapi.v1.accounts.GetAccountResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.tradeapi.v1.accounts.GetAccountResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.tradeapi.v1.accounts.GetAccountResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.tradeapi.v1.accounts.GetAccountResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static grpc.tradeapi.v1.accounts.GetAccountResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static grpc.tradeapi.v1.accounts.GetAccountResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.tradeapi.v1.accounts.GetAccountResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.tradeapi.v1.accounts.GetAccountResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.tradeapi.v1.accounts.GetAccountResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Информация о конкретном аккаунте
   * </pre>
   *
   * Protobuf type {@code grpc.tradeapi.v1.accounts.GetAccountResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:grpc.tradeapi.v1.accounts.GetAccountResponse)
      grpc.tradeapi.v1.accounts.GetAccountResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.tradeapi.v1.accounts.AccountsServiceOuterClass.internal_static_grpc_tradeapi_v1_accounts_GetAccountResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.tradeapi.v1.accounts.AccountsServiceOuterClass.internal_static_grpc_tradeapi_v1_accounts_GetAccountResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.tradeapi.v1.accounts.GetAccountResponse.class, grpc.tradeapi.v1.accounts.GetAccountResponse.Builder.class);
    }

    // Construct using grpc.tradeapi.v1.accounts.GetAccountResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getEquityFieldBuilder();
        getUnrealizedProfitFieldBuilder();
        getPositionsFieldBuilder();
        getCashFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      accountId_ = "";
      type_ = "";
      status_ = "";
      equity_ = null;
      if (equityBuilder_ != null) {
        equityBuilder_.dispose();
        equityBuilder_ = null;
      }
      unrealizedProfit_ = null;
      if (unrealizedProfitBuilder_ != null) {
        unrealizedProfitBuilder_.dispose();
        unrealizedProfitBuilder_ = null;
      }
      if (positionsBuilder_ == null) {
        positions_ = java.util.Collections.emptyList();
      } else {
        positions_ = null;
        positionsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000020);
      if (cashBuilder_ == null) {
        cash_ = java.util.Collections.emptyList();
      } else {
        cash_ = null;
        cashBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000040);
      if (portfolioMcBuilder_ != null) {
        portfolioMcBuilder_.clear();
      }
      if (portfolioMctBuilder_ != null) {
        portfolioMctBuilder_.clear();
      }
      if (portfolioFortsBuilder_ != null) {
        portfolioFortsBuilder_.clear();
      }
      portfolioCase_ = 0;
      portfolio_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.tradeapi.v1.accounts.AccountsServiceOuterClass.internal_static_grpc_tradeapi_v1_accounts_GetAccountResponse_descriptor;
    }

    @java.lang.Override
    public grpc.tradeapi.v1.accounts.GetAccountResponse getDefaultInstanceForType() {
      return grpc.tradeapi.v1.accounts.GetAccountResponse.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.tradeapi.v1.accounts.GetAccountResponse build() {
      grpc.tradeapi.v1.accounts.GetAccountResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.tradeapi.v1.accounts.GetAccountResponse buildPartial() {
      grpc.tradeapi.v1.accounts.GetAccountResponse result = new grpc.tradeapi.v1.accounts.GetAccountResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(grpc.tradeapi.v1.accounts.GetAccountResponse result) {
      if (positionsBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0)) {
          positions_ = java.util.Collections.unmodifiableList(positions_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.positions_ = positions_;
      } else {
        result.positions_ = positionsBuilder_.build();
      }
      if (cashBuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0)) {
          cash_ = java.util.Collections.unmodifiableList(cash_);
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.cash_ = cash_;
      } else {
        result.cash_ = cashBuilder_.build();
      }
    }

    private void buildPartial0(grpc.tradeapi.v1.accounts.GetAccountResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.accountId_ = accountId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.type_ = type_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.status_ = status_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.equity_ = equityBuilder_ == null
            ? equity_
            : equityBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.unrealizedProfit_ = unrealizedProfitBuilder_ == null
            ? unrealizedProfit_
            : unrealizedProfitBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    private void buildPartialOneofs(grpc.tradeapi.v1.accounts.GetAccountResponse result) {
      result.portfolioCase_ = portfolioCase_;
      result.portfolio_ = this.portfolio_;
      if (portfolioCase_ == 8 &&
          portfolioMcBuilder_ != null) {
        result.portfolio_ = portfolioMcBuilder_.build();
      }
      if (portfolioCase_ == 9 &&
          portfolioMctBuilder_ != null) {
        result.portfolio_ = portfolioMctBuilder_.build();
      }
      if (portfolioCase_ == 10 &&
          portfolioFortsBuilder_ != null) {
        result.portfolio_ = portfolioFortsBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.tradeapi.v1.accounts.GetAccountResponse) {
        return mergeFrom((grpc.tradeapi.v1.accounts.GetAccountResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.tradeapi.v1.accounts.GetAccountResponse other) {
      if (other == grpc.tradeapi.v1.accounts.GetAccountResponse.getDefaultInstance()) return this;
      if (!other.getAccountId().isEmpty()) {
        accountId_ = other.accountId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getType().isEmpty()) {
        type_ = other.type_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getStatus().isEmpty()) {
        status_ = other.status_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.hasEquity()) {
        mergeEquity(other.getEquity());
      }
      if (other.hasUnrealizedProfit()) {
        mergeUnrealizedProfit(other.getUnrealizedProfit());
      }
      if (positionsBuilder_ == null) {
        if (!other.positions_.isEmpty()) {
          if (positions_.isEmpty()) {
            positions_ = other.positions_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensurePositionsIsMutable();
            positions_.addAll(other.positions_);
          }
          onChanged();
        }
      } else {
        if (!other.positions_.isEmpty()) {
          if (positionsBuilder_.isEmpty()) {
            positionsBuilder_.dispose();
            positionsBuilder_ = null;
            positions_ = other.positions_;
            bitField0_ = (bitField0_ & ~0x00000020);
            positionsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPositionsFieldBuilder() : null;
          } else {
            positionsBuilder_.addAllMessages(other.positions_);
          }
        }
      }
      if (cashBuilder_ == null) {
        if (!other.cash_.isEmpty()) {
          if (cash_.isEmpty()) {
            cash_ = other.cash_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureCashIsMutable();
            cash_.addAll(other.cash_);
          }
          onChanged();
        }
      } else {
        if (!other.cash_.isEmpty()) {
          if (cashBuilder_.isEmpty()) {
            cashBuilder_.dispose();
            cashBuilder_ = null;
            cash_ = other.cash_;
            bitField0_ = (bitField0_ & ~0x00000040);
            cashBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getCashFieldBuilder() : null;
          } else {
            cashBuilder_.addAllMessages(other.cash_);
          }
        }
      }
      switch (other.getPortfolioCase()) {
        case PORTFOLIO_MC: {
          mergePortfolioMc(other.getPortfolioMc());
          break;
        }
        case PORTFOLIO_MCT: {
          mergePortfolioMct(other.getPortfolioMct());
          break;
        }
        case PORTFOLIO_FORTS: {
          mergePortfolioForts(other.getPortfolioForts());
          break;
        }
        case PORTFOLIO_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              accountId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              type_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              status_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getEquityFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  getUnrealizedProfitFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              grpc.tradeapi.v1.accounts.Position m =
                  input.readMessage(
                      grpc.tradeapi.v1.accounts.Position.parser(),
                      extensionRegistry);
              if (positionsBuilder_ == null) {
                ensurePositionsIsMutable();
                positions_.add(m);
              } else {
                positionsBuilder_.addMessage(m);
              }
              break;
            } // case 50
            case 58: {
              com.google.type.Money m =
                  input.readMessage(
                      com.google.type.Money.parser(),
                      extensionRegistry);
              if (cashBuilder_ == null) {
                ensureCashIsMutable();
                cash_.add(m);
              } else {
                cashBuilder_.addMessage(m);
              }
              break;
            } // case 58
            case 66: {
              input.readMessage(
                  getPortfolioMcFieldBuilder().getBuilder(),
                  extensionRegistry);
              portfolioCase_ = 8;
              break;
            } // case 66
            case 74: {
              input.readMessage(
                  getPortfolioMctFieldBuilder().getBuilder(),
                  extensionRegistry);
              portfolioCase_ = 9;
              break;
            } // case 74
            case 82: {
              input.readMessage(
                  getPortfolioFortsFieldBuilder().getBuilder(),
                  extensionRegistry);
              portfolioCase_ = 10;
              break;
            } // case 82
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int portfolioCase_ = 0;
    private java.lang.Object portfolio_;
    public PortfolioCase
        getPortfolioCase() {
      return PortfolioCase.forNumber(
          portfolioCase_);
    }

    public Builder clearPortfolio() {
      portfolioCase_ = 0;
      portfolio_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private java.lang.Object accountId_ = "";
    /**
     * <pre>
     * Идентификатор аккаунта
     * </pre>
     *
     * <code>string account_id = 1;</code>
     * @return The accountId.
     */
    public java.lang.String getAccountId() {
      java.lang.Object ref = accountId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        accountId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Идентификатор аккаунта
     * </pre>
     *
     * <code>string account_id = 1;</code>
     * @return The bytes for accountId.
     */
    public com.google.protobuf.ByteString
        getAccountIdBytes() {
      java.lang.Object ref = accountId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accountId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Идентификатор аккаунта
     * </pre>
     *
     * <code>string account_id = 1;</code>
     * @param value The accountId to set.
     * @return This builder for chaining.
     */
    public Builder setAccountId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      accountId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Идентификатор аккаунта
     * </pre>
     *
     * <code>string account_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAccountId() {
      accountId_ = getDefaultInstance().getAccountId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Идентификатор аккаунта
     * </pre>
     *
     * <code>string account_id = 1;</code>
     * @param value The bytes for accountId to set.
     * @return This builder for chaining.
     */
    public Builder setAccountIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      accountId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object type_ = "";
    /**
     * <pre>
     * Тип аккаунта
     * </pre>
     *
     * <code>string type = 2;</code>
     * @return The type.
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Тип аккаунта
     * </pre>
     *
     * <code>string type = 2;</code>
     * @return The bytes for type.
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Тип аккаунта
     * </pre>
     *
     * <code>string type = 2;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      type_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Тип аккаунта
     * </pre>
     *
     * <code>string type = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      type_ = getDefaultInstance().getType();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Тип аккаунта
     * </pre>
     *
     * <code>string type = 2;</code>
     * @param value The bytes for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      type_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object status_ = "";
    /**
     * <pre>
     * Статус аккаунта
     * </pre>
     *
     * <code>string status = 3;</code>
     * @return The status.
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Статус аккаунта
     * </pre>
     *
     * <code>string status = 3;</code>
     * @return The bytes for status.
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Статус аккаунта
     * </pre>
     *
     * <code>string status = 3;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      status_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Статус аккаунта
     * </pre>
     *
     * <code>string status = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      status_ = getDefaultInstance().getStatus();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Статус аккаунта
     * </pre>
     *
     * <code>string status = 3;</code>
     * @param value The bytes for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      status_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private com.google.type.Decimal equity_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.type.Decimal, com.google.type.Decimal.Builder, com.google.type.DecimalOrBuilder> equityBuilder_;
    /**
     * <pre>
     * Доступные средства плюс стоимость открытых позиций
     * </pre>
     *
     * <code>.google.type.Decimal equity = 4;</code>
     * @return Whether the equity field is set.
     */
    public boolean hasEquity() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * Доступные средства плюс стоимость открытых позиций
     * </pre>
     *
     * <code>.google.type.Decimal equity = 4;</code>
     * @return The equity.
     */
    public com.google.type.Decimal getEquity() {
      if (equityBuilder_ == null) {
        return equity_ == null ? com.google.type.Decimal.getDefaultInstance() : equity_;
      } else {
        return equityBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Доступные средства плюс стоимость открытых позиций
     * </pre>
     *
     * <code>.google.type.Decimal equity = 4;</code>
     */
    public Builder setEquity(com.google.type.Decimal value) {
      if (equityBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        equity_ = value;
      } else {
        equityBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Доступные средства плюс стоимость открытых позиций
     * </pre>
     *
     * <code>.google.type.Decimal equity = 4;</code>
     */
    public Builder setEquity(
        com.google.type.Decimal.Builder builderForValue) {
      if (equityBuilder_ == null) {
        equity_ = builderForValue.build();
      } else {
        equityBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Доступные средства плюс стоимость открытых позиций
     * </pre>
     *
     * <code>.google.type.Decimal equity = 4;</code>
     */
    public Builder mergeEquity(com.google.type.Decimal value) {
      if (equityBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          equity_ != null &&
          equity_ != com.google.type.Decimal.getDefaultInstance()) {
          getEquityBuilder().mergeFrom(value);
        } else {
          equity_ = value;
        }
      } else {
        equityBuilder_.mergeFrom(value);
      }
      if (equity_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Доступные средства плюс стоимость открытых позиций
     * </pre>
     *
     * <code>.google.type.Decimal equity = 4;</code>
     */
    public Builder clearEquity() {
      bitField0_ = (bitField0_ & ~0x00000008);
      equity_ = null;
      if (equityBuilder_ != null) {
        equityBuilder_.dispose();
        equityBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Доступные средства плюс стоимость открытых позиций
     * </pre>
     *
     * <code>.google.type.Decimal equity = 4;</code>
     */
    public com.google.type.Decimal.Builder getEquityBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getEquityFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Доступные средства плюс стоимость открытых позиций
     * </pre>
     *
     * <code>.google.type.Decimal equity = 4;</code>
     */
    public com.google.type.DecimalOrBuilder getEquityOrBuilder() {
      if (equityBuilder_ != null) {
        return equityBuilder_.getMessageOrBuilder();
      } else {
        return equity_ == null ?
            com.google.type.Decimal.getDefaultInstance() : equity_;
      }
    }
    /**
     * <pre>
     * Доступные средства плюс стоимость открытых позиций
     * </pre>
     *
     * <code>.google.type.Decimal equity = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.type.Decimal, com.google.type.Decimal.Builder, com.google.type.DecimalOrBuilder> 
        getEquityFieldBuilder() {
      if (equityBuilder_ == null) {
        equityBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.type.Decimal, com.google.type.Decimal.Builder, com.google.type.DecimalOrBuilder>(
                getEquity(),
                getParentForChildren(),
                isClean());
        equity_ = null;
      }
      return equityBuilder_;
    }

    private com.google.type.Decimal unrealizedProfit_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.type.Decimal, com.google.type.Decimal.Builder, com.google.type.DecimalOrBuilder> unrealizedProfitBuilder_;
    /**
     * <pre>
     * Нереализованная прибыль
     * </pre>
     *
     * <code>.google.type.Decimal unrealized_profit = 5;</code>
     * @return Whether the unrealizedProfit field is set.
     */
    public boolean hasUnrealizedProfit() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     * Нереализованная прибыль
     * </pre>
     *
     * <code>.google.type.Decimal unrealized_profit = 5;</code>
     * @return The unrealizedProfit.
     */
    public com.google.type.Decimal getUnrealizedProfit() {
      if (unrealizedProfitBuilder_ == null) {
        return unrealizedProfit_ == null ? com.google.type.Decimal.getDefaultInstance() : unrealizedProfit_;
      } else {
        return unrealizedProfitBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Нереализованная прибыль
     * </pre>
     *
     * <code>.google.type.Decimal unrealized_profit = 5;</code>
     */
    public Builder setUnrealizedProfit(com.google.type.Decimal value) {
      if (unrealizedProfitBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        unrealizedProfit_ = value;
      } else {
        unrealizedProfitBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Нереализованная прибыль
     * </pre>
     *
     * <code>.google.type.Decimal unrealized_profit = 5;</code>
     */
    public Builder setUnrealizedProfit(
        com.google.type.Decimal.Builder builderForValue) {
      if (unrealizedProfitBuilder_ == null) {
        unrealizedProfit_ = builderForValue.build();
      } else {
        unrealizedProfitBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Нереализованная прибыль
     * </pre>
     *
     * <code>.google.type.Decimal unrealized_profit = 5;</code>
     */
    public Builder mergeUnrealizedProfit(com.google.type.Decimal value) {
      if (unrealizedProfitBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          unrealizedProfit_ != null &&
          unrealizedProfit_ != com.google.type.Decimal.getDefaultInstance()) {
          getUnrealizedProfitBuilder().mergeFrom(value);
        } else {
          unrealizedProfit_ = value;
        }
      } else {
        unrealizedProfitBuilder_.mergeFrom(value);
      }
      if (unrealizedProfit_ != null) {
        bitField0_ |= 0x00000010;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Нереализованная прибыль
     * </pre>
     *
     * <code>.google.type.Decimal unrealized_profit = 5;</code>
     */
    public Builder clearUnrealizedProfit() {
      bitField0_ = (bitField0_ & ~0x00000010);
      unrealizedProfit_ = null;
      if (unrealizedProfitBuilder_ != null) {
        unrealizedProfitBuilder_.dispose();
        unrealizedProfitBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Нереализованная прибыль
     * </pre>
     *
     * <code>.google.type.Decimal unrealized_profit = 5;</code>
     */
    public com.google.type.Decimal.Builder getUnrealizedProfitBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return getUnrealizedProfitFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Нереализованная прибыль
     * </pre>
     *
     * <code>.google.type.Decimal unrealized_profit = 5;</code>
     */
    public com.google.type.DecimalOrBuilder getUnrealizedProfitOrBuilder() {
      if (unrealizedProfitBuilder_ != null) {
        return unrealizedProfitBuilder_.getMessageOrBuilder();
      } else {
        return unrealizedProfit_ == null ?
            com.google.type.Decimal.getDefaultInstance() : unrealizedProfit_;
      }
    }
    /**
     * <pre>
     * Нереализованная прибыль
     * </pre>
     *
     * <code>.google.type.Decimal unrealized_profit = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.type.Decimal, com.google.type.Decimal.Builder, com.google.type.DecimalOrBuilder> 
        getUnrealizedProfitFieldBuilder() {
      if (unrealizedProfitBuilder_ == null) {
        unrealizedProfitBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.type.Decimal, com.google.type.Decimal.Builder, com.google.type.DecimalOrBuilder>(
                getUnrealizedProfit(),
                getParentForChildren(),
                isClean());
        unrealizedProfit_ = null;
      }
      return unrealizedProfitBuilder_;
    }

    private java.util.List<grpc.tradeapi.v1.accounts.Position> positions_ =
      java.util.Collections.emptyList();
    private void ensurePositionsIsMutable() {
      if (!((bitField0_ & 0x00000020) != 0)) {
        positions_ = new java.util.ArrayList<grpc.tradeapi.v1.accounts.Position>(positions_);
        bitField0_ |= 0x00000020;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        grpc.tradeapi.v1.accounts.Position, grpc.tradeapi.v1.accounts.Position.Builder, grpc.tradeapi.v1.accounts.PositionOrBuilder> positionsBuilder_;

    /**
     * <pre>
     * Позиции. Открытые, плюс теоретические (по неисполненным активным заявкам)
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.accounts.Position positions = 6;</code>
     */
    public java.util.List<grpc.tradeapi.v1.accounts.Position> getPositionsList() {
      if (positionsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(positions_);
      } else {
        return positionsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Позиции. Открытые, плюс теоретические (по неисполненным активным заявкам)
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.accounts.Position positions = 6;</code>
     */
    public int getPositionsCount() {
      if (positionsBuilder_ == null) {
        return positions_.size();
      } else {
        return positionsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Позиции. Открытые, плюс теоретические (по неисполненным активным заявкам)
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.accounts.Position positions = 6;</code>
     */
    public grpc.tradeapi.v1.accounts.Position getPositions(int index) {
      if (positionsBuilder_ == null) {
        return positions_.get(index);
      } else {
        return positionsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Позиции. Открытые, плюс теоретические (по неисполненным активным заявкам)
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.accounts.Position positions = 6;</code>
     */
    public Builder setPositions(
        int index, grpc.tradeapi.v1.accounts.Position value) {
      if (positionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePositionsIsMutable();
        positions_.set(index, value);
        onChanged();
      } else {
        positionsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Позиции. Открытые, плюс теоретические (по неисполненным активным заявкам)
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.accounts.Position positions = 6;</code>
     */
    public Builder setPositions(
        int index, grpc.tradeapi.v1.accounts.Position.Builder builderForValue) {
      if (positionsBuilder_ == null) {
        ensurePositionsIsMutable();
        positions_.set(index, builderForValue.build());
        onChanged();
      } else {
        positionsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Позиции. Открытые, плюс теоретические (по неисполненным активным заявкам)
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.accounts.Position positions = 6;</code>
     */
    public Builder addPositions(grpc.tradeapi.v1.accounts.Position value) {
      if (positionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePositionsIsMutable();
        positions_.add(value);
        onChanged();
      } else {
        positionsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Позиции. Открытые, плюс теоретические (по неисполненным активным заявкам)
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.accounts.Position positions = 6;</code>
     */
    public Builder addPositions(
        int index, grpc.tradeapi.v1.accounts.Position value) {
      if (positionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePositionsIsMutable();
        positions_.add(index, value);
        onChanged();
      } else {
        positionsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Позиции. Открытые, плюс теоретические (по неисполненным активным заявкам)
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.accounts.Position positions = 6;</code>
     */
    public Builder addPositions(
        grpc.tradeapi.v1.accounts.Position.Builder builderForValue) {
      if (positionsBuilder_ == null) {
        ensurePositionsIsMutable();
        positions_.add(builderForValue.build());
        onChanged();
      } else {
        positionsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Позиции. Открытые, плюс теоретические (по неисполненным активным заявкам)
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.accounts.Position positions = 6;</code>
     */
    public Builder addPositions(
        int index, grpc.tradeapi.v1.accounts.Position.Builder builderForValue) {
      if (positionsBuilder_ == null) {
        ensurePositionsIsMutable();
        positions_.add(index, builderForValue.build());
        onChanged();
      } else {
        positionsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Позиции. Открытые, плюс теоретические (по неисполненным активным заявкам)
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.accounts.Position positions = 6;</code>
     */
    public Builder addAllPositions(
        java.lang.Iterable<? extends grpc.tradeapi.v1.accounts.Position> values) {
      if (positionsBuilder_ == null) {
        ensurePositionsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, positions_);
        onChanged();
      } else {
        positionsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Позиции. Открытые, плюс теоретические (по неисполненным активным заявкам)
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.accounts.Position positions = 6;</code>
     */
    public Builder clearPositions() {
      if (positionsBuilder_ == null) {
        positions_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
      } else {
        positionsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Позиции. Открытые, плюс теоретические (по неисполненным активным заявкам)
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.accounts.Position positions = 6;</code>
     */
    public Builder removePositions(int index) {
      if (positionsBuilder_ == null) {
        ensurePositionsIsMutable();
        positions_.remove(index);
        onChanged();
      } else {
        positionsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Позиции. Открытые, плюс теоретические (по неисполненным активным заявкам)
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.accounts.Position positions = 6;</code>
     */
    public grpc.tradeapi.v1.accounts.Position.Builder getPositionsBuilder(
        int index) {
      return getPositionsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Позиции. Открытые, плюс теоретические (по неисполненным активным заявкам)
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.accounts.Position positions = 6;</code>
     */
    public grpc.tradeapi.v1.accounts.PositionOrBuilder getPositionsOrBuilder(
        int index) {
      if (positionsBuilder_ == null) {
        return positions_.get(index);  } else {
        return positionsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Позиции. Открытые, плюс теоретические (по неисполненным активным заявкам)
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.accounts.Position positions = 6;</code>
     */
    public java.util.List<? extends grpc.tradeapi.v1.accounts.PositionOrBuilder> 
         getPositionsOrBuilderList() {
      if (positionsBuilder_ != null) {
        return positionsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(positions_);
      }
    }
    /**
     * <pre>
     * Позиции. Открытые, плюс теоретические (по неисполненным активным заявкам)
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.accounts.Position positions = 6;</code>
     */
    public grpc.tradeapi.v1.accounts.Position.Builder addPositionsBuilder() {
      return getPositionsFieldBuilder().addBuilder(
          grpc.tradeapi.v1.accounts.Position.getDefaultInstance());
    }
    /**
     * <pre>
     * Позиции. Открытые, плюс теоретические (по неисполненным активным заявкам)
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.accounts.Position positions = 6;</code>
     */
    public grpc.tradeapi.v1.accounts.Position.Builder addPositionsBuilder(
        int index) {
      return getPositionsFieldBuilder().addBuilder(
          index, grpc.tradeapi.v1.accounts.Position.getDefaultInstance());
    }
    /**
     * <pre>
     * Позиции. Открытые, плюс теоретические (по неисполненным активным заявкам)
     * </pre>
     *
     * <code>repeated .grpc.tradeapi.v1.accounts.Position positions = 6;</code>
     */
    public java.util.List<grpc.tradeapi.v1.accounts.Position.Builder> 
         getPositionsBuilderList() {
      return getPositionsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        grpc.tradeapi.v1.accounts.Position, grpc.tradeapi.v1.accounts.Position.Builder, grpc.tradeapi.v1.accounts.PositionOrBuilder> 
        getPositionsFieldBuilder() {
      if (positionsBuilder_ == null) {
        positionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            grpc.tradeapi.v1.accounts.Position, grpc.tradeapi.v1.accounts.Position.Builder, grpc.tradeapi.v1.accounts.PositionOrBuilder>(
                positions_,
                ((bitField0_ & 0x00000020) != 0),
                getParentForChildren(),
                isClean());
        positions_ = null;
      }
      return positionsBuilder_;
    }

    private java.util.List<com.google.type.Money> cash_ =
      java.util.Collections.emptyList();
    private void ensureCashIsMutable() {
      if (!((bitField0_ & 0x00000040) != 0)) {
        cash_ = new java.util.ArrayList<com.google.type.Money>(cash_);
        bitField0_ |= 0x00000040;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.type.Money, com.google.type.Money.Builder, com.google.type.MoneyOrBuilder> cashBuilder_;

    /**
     * <pre>
     * Сумма собственных денежных средств на счете, доступная для торговли. Не включает маржинальные средства.
     * </pre>
     *
     * <code>repeated .google.type.Money cash = 7;</code>
     */
    public java.util.List<com.google.type.Money> getCashList() {
      if (cashBuilder_ == null) {
        return java.util.Collections.unmodifiableList(cash_);
      } else {
        return cashBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Сумма собственных денежных средств на счете, доступная для торговли. Не включает маржинальные средства.
     * </pre>
     *
     * <code>repeated .google.type.Money cash = 7;</code>
     */
    public int getCashCount() {
      if (cashBuilder_ == null) {
        return cash_.size();
      } else {
        return cashBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Сумма собственных денежных средств на счете, доступная для торговли. Не включает маржинальные средства.
     * </pre>
     *
     * <code>repeated .google.type.Money cash = 7;</code>
     */
    public com.google.type.Money getCash(int index) {
      if (cashBuilder_ == null) {
        return cash_.get(index);
      } else {
        return cashBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Сумма собственных денежных средств на счете, доступная для торговли. Не включает маржинальные средства.
     * </pre>
     *
     * <code>repeated .google.type.Money cash = 7;</code>
     */
    public Builder setCash(
        int index, com.google.type.Money value) {
      if (cashBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCashIsMutable();
        cash_.set(index, value);
        onChanged();
      } else {
        cashBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Сумма собственных денежных средств на счете, доступная для торговли. Не включает маржинальные средства.
     * </pre>
     *
     * <code>repeated .google.type.Money cash = 7;</code>
     */
    public Builder setCash(
        int index, com.google.type.Money.Builder builderForValue) {
      if (cashBuilder_ == null) {
        ensureCashIsMutable();
        cash_.set(index, builderForValue.build());
        onChanged();
      } else {
        cashBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Сумма собственных денежных средств на счете, доступная для торговли. Не включает маржинальные средства.
     * </pre>
     *
     * <code>repeated .google.type.Money cash = 7;</code>
     */
    public Builder addCash(com.google.type.Money value) {
      if (cashBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCashIsMutable();
        cash_.add(value);
        onChanged();
      } else {
        cashBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Сумма собственных денежных средств на счете, доступная для торговли. Не включает маржинальные средства.
     * </pre>
     *
     * <code>repeated .google.type.Money cash = 7;</code>
     */
    public Builder addCash(
        int index, com.google.type.Money value) {
      if (cashBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCashIsMutable();
        cash_.add(index, value);
        onChanged();
      } else {
        cashBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Сумма собственных денежных средств на счете, доступная для торговли. Не включает маржинальные средства.
     * </pre>
     *
     * <code>repeated .google.type.Money cash = 7;</code>
     */
    public Builder addCash(
        com.google.type.Money.Builder builderForValue) {
      if (cashBuilder_ == null) {
        ensureCashIsMutable();
        cash_.add(builderForValue.build());
        onChanged();
      } else {
        cashBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Сумма собственных денежных средств на счете, доступная для торговли. Не включает маржинальные средства.
     * </pre>
     *
     * <code>repeated .google.type.Money cash = 7;</code>
     */
    public Builder addCash(
        int index, com.google.type.Money.Builder builderForValue) {
      if (cashBuilder_ == null) {
        ensureCashIsMutable();
        cash_.add(index, builderForValue.build());
        onChanged();
      } else {
        cashBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Сумма собственных денежных средств на счете, доступная для торговли. Не включает маржинальные средства.
     * </pre>
     *
     * <code>repeated .google.type.Money cash = 7;</code>
     */
    public Builder addAllCash(
        java.lang.Iterable<? extends com.google.type.Money> values) {
      if (cashBuilder_ == null) {
        ensureCashIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, cash_);
        onChanged();
      } else {
        cashBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Сумма собственных денежных средств на счете, доступная для торговли. Не включает маржинальные средства.
     * </pre>
     *
     * <code>repeated .google.type.Money cash = 7;</code>
     */
    public Builder clearCash() {
      if (cashBuilder_ == null) {
        cash_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
      } else {
        cashBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Сумма собственных денежных средств на счете, доступная для торговли. Не включает маржинальные средства.
     * </pre>
     *
     * <code>repeated .google.type.Money cash = 7;</code>
     */
    public Builder removeCash(int index) {
      if (cashBuilder_ == null) {
        ensureCashIsMutable();
        cash_.remove(index);
        onChanged();
      } else {
        cashBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Сумма собственных денежных средств на счете, доступная для торговли. Не включает маржинальные средства.
     * </pre>
     *
     * <code>repeated .google.type.Money cash = 7;</code>
     */
    public com.google.type.Money.Builder getCashBuilder(
        int index) {
      return getCashFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Сумма собственных денежных средств на счете, доступная для торговли. Не включает маржинальные средства.
     * </pre>
     *
     * <code>repeated .google.type.Money cash = 7;</code>
     */
    public com.google.type.MoneyOrBuilder getCashOrBuilder(
        int index) {
      if (cashBuilder_ == null) {
        return cash_.get(index);  } else {
        return cashBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Сумма собственных денежных средств на счете, доступная для торговли. Не включает маржинальные средства.
     * </pre>
     *
     * <code>repeated .google.type.Money cash = 7;</code>
     */
    public java.util.List<? extends com.google.type.MoneyOrBuilder> 
         getCashOrBuilderList() {
      if (cashBuilder_ != null) {
        return cashBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(cash_);
      }
    }
    /**
     * <pre>
     * Сумма собственных денежных средств на счете, доступная для торговли. Не включает маржинальные средства.
     * </pre>
     *
     * <code>repeated .google.type.Money cash = 7;</code>
     */
    public com.google.type.Money.Builder addCashBuilder() {
      return getCashFieldBuilder().addBuilder(
          com.google.type.Money.getDefaultInstance());
    }
    /**
     * <pre>
     * Сумма собственных денежных средств на счете, доступная для торговли. Не включает маржинальные средства.
     * </pre>
     *
     * <code>repeated .google.type.Money cash = 7;</code>
     */
    public com.google.type.Money.Builder addCashBuilder(
        int index) {
      return getCashFieldBuilder().addBuilder(
          index, com.google.type.Money.getDefaultInstance());
    }
    /**
     * <pre>
     * Сумма собственных денежных средств на счете, доступная для торговли. Не включает маржинальные средства.
     * </pre>
     *
     * <code>repeated .google.type.Money cash = 7;</code>
     */
    public java.util.List<com.google.type.Money.Builder> 
         getCashBuilderList() {
      return getCashFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.type.Money, com.google.type.Money.Builder, com.google.type.MoneyOrBuilder> 
        getCashFieldBuilder() {
      if (cashBuilder_ == null) {
        cashBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.google.type.Money, com.google.type.Money.Builder, com.google.type.MoneyOrBuilder>(
                cash_,
                ((bitField0_ & 0x00000040) != 0),
                getParentForChildren(),
                isClean());
        cash_ = null;
      }
      return cashBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        grpc.tradeapi.v1.accounts.MC, grpc.tradeapi.v1.accounts.MC.Builder, grpc.tradeapi.v1.accounts.MCOrBuilder> portfolioMcBuilder_;
    /**
     * <code>.grpc.tradeapi.v1.accounts.MC portfolio_mc = 8;</code>
     * @return Whether the portfolioMc field is set.
     */
    @java.lang.Override
    public boolean hasPortfolioMc() {
      return portfolioCase_ == 8;
    }
    /**
     * <code>.grpc.tradeapi.v1.accounts.MC portfolio_mc = 8;</code>
     * @return The portfolioMc.
     */
    @java.lang.Override
    public grpc.tradeapi.v1.accounts.MC getPortfolioMc() {
      if (portfolioMcBuilder_ == null) {
        if (portfolioCase_ == 8) {
          return (grpc.tradeapi.v1.accounts.MC) portfolio_;
        }
        return grpc.tradeapi.v1.accounts.MC.getDefaultInstance();
      } else {
        if (portfolioCase_ == 8) {
          return portfolioMcBuilder_.getMessage();
        }
        return grpc.tradeapi.v1.accounts.MC.getDefaultInstance();
      }
    }
    /**
     * <code>.grpc.tradeapi.v1.accounts.MC portfolio_mc = 8;</code>
     */
    public Builder setPortfolioMc(grpc.tradeapi.v1.accounts.MC value) {
      if (portfolioMcBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        portfolio_ = value;
        onChanged();
      } else {
        portfolioMcBuilder_.setMessage(value);
      }
      portfolioCase_ = 8;
      return this;
    }
    /**
     * <code>.grpc.tradeapi.v1.accounts.MC portfolio_mc = 8;</code>
     */
    public Builder setPortfolioMc(
        grpc.tradeapi.v1.accounts.MC.Builder builderForValue) {
      if (portfolioMcBuilder_ == null) {
        portfolio_ = builderForValue.build();
        onChanged();
      } else {
        portfolioMcBuilder_.setMessage(builderForValue.build());
      }
      portfolioCase_ = 8;
      return this;
    }
    /**
     * <code>.grpc.tradeapi.v1.accounts.MC portfolio_mc = 8;</code>
     */
    public Builder mergePortfolioMc(grpc.tradeapi.v1.accounts.MC value) {
      if (portfolioMcBuilder_ == null) {
        if (portfolioCase_ == 8 &&
            portfolio_ != grpc.tradeapi.v1.accounts.MC.getDefaultInstance()) {
          portfolio_ = grpc.tradeapi.v1.accounts.MC.newBuilder((grpc.tradeapi.v1.accounts.MC) portfolio_)
              .mergeFrom(value).buildPartial();
        } else {
          portfolio_ = value;
        }
        onChanged();
      } else {
        if (portfolioCase_ == 8) {
          portfolioMcBuilder_.mergeFrom(value);
        } else {
          portfolioMcBuilder_.setMessage(value);
        }
      }
      portfolioCase_ = 8;
      return this;
    }
    /**
     * <code>.grpc.tradeapi.v1.accounts.MC portfolio_mc = 8;</code>
     */
    public Builder clearPortfolioMc() {
      if (portfolioMcBuilder_ == null) {
        if (portfolioCase_ == 8) {
          portfolioCase_ = 0;
          portfolio_ = null;
          onChanged();
        }
      } else {
        if (portfolioCase_ == 8) {
          portfolioCase_ = 0;
          portfolio_ = null;
        }
        portfolioMcBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.grpc.tradeapi.v1.accounts.MC portfolio_mc = 8;</code>
     */
    public grpc.tradeapi.v1.accounts.MC.Builder getPortfolioMcBuilder() {
      return getPortfolioMcFieldBuilder().getBuilder();
    }
    /**
     * <code>.grpc.tradeapi.v1.accounts.MC portfolio_mc = 8;</code>
     */
    @java.lang.Override
    public grpc.tradeapi.v1.accounts.MCOrBuilder getPortfolioMcOrBuilder() {
      if ((portfolioCase_ == 8) && (portfolioMcBuilder_ != null)) {
        return portfolioMcBuilder_.getMessageOrBuilder();
      } else {
        if (portfolioCase_ == 8) {
          return (grpc.tradeapi.v1.accounts.MC) portfolio_;
        }
        return grpc.tradeapi.v1.accounts.MC.getDefaultInstance();
      }
    }
    /**
     * <code>.grpc.tradeapi.v1.accounts.MC portfolio_mc = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        grpc.tradeapi.v1.accounts.MC, grpc.tradeapi.v1.accounts.MC.Builder, grpc.tradeapi.v1.accounts.MCOrBuilder> 
        getPortfolioMcFieldBuilder() {
      if (portfolioMcBuilder_ == null) {
        if (!(portfolioCase_ == 8)) {
          portfolio_ = grpc.tradeapi.v1.accounts.MC.getDefaultInstance();
        }
        portfolioMcBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            grpc.tradeapi.v1.accounts.MC, grpc.tradeapi.v1.accounts.MC.Builder, grpc.tradeapi.v1.accounts.MCOrBuilder>(
                (grpc.tradeapi.v1.accounts.MC) portfolio_,
                getParentForChildren(),
                isClean());
        portfolio_ = null;
      }
      portfolioCase_ = 8;
      onChanged();
      return portfolioMcBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        grpc.tradeapi.v1.accounts.MCT, grpc.tradeapi.v1.accounts.MCT.Builder, grpc.tradeapi.v1.accounts.MCTOrBuilder> portfolioMctBuilder_;
    /**
     * <code>.grpc.tradeapi.v1.accounts.MCT portfolio_mct = 9;</code>
     * @return Whether the portfolioMct field is set.
     */
    @java.lang.Override
    public boolean hasPortfolioMct() {
      return portfolioCase_ == 9;
    }
    /**
     * <code>.grpc.tradeapi.v1.accounts.MCT portfolio_mct = 9;</code>
     * @return The portfolioMct.
     */
    @java.lang.Override
    public grpc.tradeapi.v1.accounts.MCT getPortfolioMct() {
      if (portfolioMctBuilder_ == null) {
        if (portfolioCase_ == 9) {
          return (grpc.tradeapi.v1.accounts.MCT) portfolio_;
        }
        return grpc.tradeapi.v1.accounts.MCT.getDefaultInstance();
      } else {
        if (portfolioCase_ == 9) {
          return portfolioMctBuilder_.getMessage();
        }
        return grpc.tradeapi.v1.accounts.MCT.getDefaultInstance();
      }
    }
    /**
     * <code>.grpc.tradeapi.v1.accounts.MCT portfolio_mct = 9;</code>
     */
    public Builder setPortfolioMct(grpc.tradeapi.v1.accounts.MCT value) {
      if (portfolioMctBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        portfolio_ = value;
        onChanged();
      } else {
        portfolioMctBuilder_.setMessage(value);
      }
      portfolioCase_ = 9;
      return this;
    }
    /**
     * <code>.grpc.tradeapi.v1.accounts.MCT portfolio_mct = 9;</code>
     */
    public Builder setPortfolioMct(
        grpc.tradeapi.v1.accounts.MCT.Builder builderForValue) {
      if (portfolioMctBuilder_ == null) {
        portfolio_ = builderForValue.build();
        onChanged();
      } else {
        portfolioMctBuilder_.setMessage(builderForValue.build());
      }
      portfolioCase_ = 9;
      return this;
    }
    /**
     * <code>.grpc.tradeapi.v1.accounts.MCT portfolio_mct = 9;</code>
     */
    public Builder mergePortfolioMct(grpc.tradeapi.v1.accounts.MCT value) {
      if (portfolioMctBuilder_ == null) {
        if (portfolioCase_ == 9 &&
            portfolio_ != grpc.tradeapi.v1.accounts.MCT.getDefaultInstance()) {
          portfolio_ = grpc.tradeapi.v1.accounts.MCT.newBuilder((grpc.tradeapi.v1.accounts.MCT) portfolio_)
              .mergeFrom(value).buildPartial();
        } else {
          portfolio_ = value;
        }
        onChanged();
      } else {
        if (portfolioCase_ == 9) {
          portfolioMctBuilder_.mergeFrom(value);
        } else {
          portfolioMctBuilder_.setMessage(value);
        }
      }
      portfolioCase_ = 9;
      return this;
    }
    /**
     * <code>.grpc.tradeapi.v1.accounts.MCT portfolio_mct = 9;</code>
     */
    public Builder clearPortfolioMct() {
      if (portfolioMctBuilder_ == null) {
        if (portfolioCase_ == 9) {
          portfolioCase_ = 0;
          portfolio_ = null;
          onChanged();
        }
      } else {
        if (portfolioCase_ == 9) {
          portfolioCase_ = 0;
          portfolio_ = null;
        }
        portfolioMctBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.grpc.tradeapi.v1.accounts.MCT portfolio_mct = 9;</code>
     */
    public grpc.tradeapi.v1.accounts.MCT.Builder getPortfolioMctBuilder() {
      return getPortfolioMctFieldBuilder().getBuilder();
    }
    /**
     * <code>.grpc.tradeapi.v1.accounts.MCT portfolio_mct = 9;</code>
     */
    @java.lang.Override
    public grpc.tradeapi.v1.accounts.MCTOrBuilder getPortfolioMctOrBuilder() {
      if ((portfolioCase_ == 9) && (portfolioMctBuilder_ != null)) {
        return portfolioMctBuilder_.getMessageOrBuilder();
      } else {
        if (portfolioCase_ == 9) {
          return (grpc.tradeapi.v1.accounts.MCT) portfolio_;
        }
        return grpc.tradeapi.v1.accounts.MCT.getDefaultInstance();
      }
    }
    /**
     * <code>.grpc.tradeapi.v1.accounts.MCT portfolio_mct = 9;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        grpc.tradeapi.v1.accounts.MCT, grpc.tradeapi.v1.accounts.MCT.Builder, grpc.tradeapi.v1.accounts.MCTOrBuilder> 
        getPortfolioMctFieldBuilder() {
      if (portfolioMctBuilder_ == null) {
        if (!(portfolioCase_ == 9)) {
          portfolio_ = grpc.tradeapi.v1.accounts.MCT.getDefaultInstance();
        }
        portfolioMctBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            grpc.tradeapi.v1.accounts.MCT, grpc.tradeapi.v1.accounts.MCT.Builder, grpc.tradeapi.v1.accounts.MCTOrBuilder>(
                (grpc.tradeapi.v1.accounts.MCT) portfolio_,
                getParentForChildren(),
                isClean());
        portfolio_ = null;
      }
      portfolioCase_ = 9;
      onChanged();
      return portfolioMctBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        grpc.tradeapi.v1.accounts.FORTS, grpc.tradeapi.v1.accounts.FORTS.Builder, grpc.tradeapi.v1.accounts.FORTSOrBuilder> portfolioFortsBuilder_;
    /**
     * <code>.grpc.tradeapi.v1.accounts.FORTS portfolio_forts = 10;</code>
     * @return Whether the portfolioForts field is set.
     */
    @java.lang.Override
    public boolean hasPortfolioForts() {
      return portfolioCase_ == 10;
    }
    /**
     * <code>.grpc.tradeapi.v1.accounts.FORTS portfolio_forts = 10;</code>
     * @return The portfolioForts.
     */
    @java.lang.Override
    public grpc.tradeapi.v1.accounts.FORTS getPortfolioForts() {
      if (portfolioFortsBuilder_ == null) {
        if (portfolioCase_ == 10) {
          return (grpc.tradeapi.v1.accounts.FORTS) portfolio_;
        }
        return grpc.tradeapi.v1.accounts.FORTS.getDefaultInstance();
      } else {
        if (portfolioCase_ == 10) {
          return portfolioFortsBuilder_.getMessage();
        }
        return grpc.tradeapi.v1.accounts.FORTS.getDefaultInstance();
      }
    }
    /**
     * <code>.grpc.tradeapi.v1.accounts.FORTS portfolio_forts = 10;</code>
     */
    public Builder setPortfolioForts(grpc.tradeapi.v1.accounts.FORTS value) {
      if (portfolioFortsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        portfolio_ = value;
        onChanged();
      } else {
        portfolioFortsBuilder_.setMessage(value);
      }
      portfolioCase_ = 10;
      return this;
    }
    /**
     * <code>.grpc.tradeapi.v1.accounts.FORTS portfolio_forts = 10;</code>
     */
    public Builder setPortfolioForts(
        grpc.tradeapi.v1.accounts.FORTS.Builder builderForValue) {
      if (portfolioFortsBuilder_ == null) {
        portfolio_ = builderForValue.build();
        onChanged();
      } else {
        portfolioFortsBuilder_.setMessage(builderForValue.build());
      }
      portfolioCase_ = 10;
      return this;
    }
    /**
     * <code>.grpc.tradeapi.v1.accounts.FORTS portfolio_forts = 10;</code>
     */
    public Builder mergePortfolioForts(grpc.tradeapi.v1.accounts.FORTS value) {
      if (portfolioFortsBuilder_ == null) {
        if (portfolioCase_ == 10 &&
            portfolio_ != grpc.tradeapi.v1.accounts.FORTS.getDefaultInstance()) {
          portfolio_ = grpc.tradeapi.v1.accounts.FORTS.newBuilder((grpc.tradeapi.v1.accounts.FORTS) portfolio_)
              .mergeFrom(value).buildPartial();
        } else {
          portfolio_ = value;
        }
        onChanged();
      } else {
        if (portfolioCase_ == 10) {
          portfolioFortsBuilder_.mergeFrom(value);
        } else {
          portfolioFortsBuilder_.setMessage(value);
        }
      }
      portfolioCase_ = 10;
      return this;
    }
    /**
     * <code>.grpc.tradeapi.v1.accounts.FORTS portfolio_forts = 10;</code>
     */
    public Builder clearPortfolioForts() {
      if (portfolioFortsBuilder_ == null) {
        if (portfolioCase_ == 10) {
          portfolioCase_ = 0;
          portfolio_ = null;
          onChanged();
        }
      } else {
        if (portfolioCase_ == 10) {
          portfolioCase_ = 0;
          portfolio_ = null;
        }
        portfolioFortsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.grpc.tradeapi.v1.accounts.FORTS portfolio_forts = 10;</code>
     */
    public grpc.tradeapi.v1.accounts.FORTS.Builder getPortfolioFortsBuilder() {
      return getPortfolioFortsFieldBuilder().getBuilder();
    }
    /**
     * <code>.grpc.tradeapi.v1.accounts.FORTS portfolio_forts = 10;</code>
     */
    @java.lang.Override
    public grpc.tradeapi.v1.accounts.FORTSOrBuilder getPortfolioFortsOrBuilder() {
      if ((portfolioCase_ == 10) && (portfolioFortsBuilder_ != null)) {
        return portfolioFortsBuilder_.getMessageOrBuilder();
      } else {
        if (portfolioCase_ == 10) {
          return (grpc.tradeapi.v1.accounts.FORTS) portfolio_;
        }
        return grpc.tradeapi.v1.accounts.FORTS.getDefaultInstance();
      }
    }
    /**
     * <code>.grpc.tradeapi.v1.accounts.FORTS portfolio_forts = 10;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        grpc.tradeapi.v1.accounts.FORTS, grpc.tradeapi.v1.accounts.FORTS.Builder, grpc.tradeapi.v1.accounts.FORTSOrBuilder> 
        getPortfolioFortsFieldBuilder() {
      if (portfolioFortsBuilder_ == null) {
        if (!(portfolioCase_ == 10)) {
          portfolio_ = grpc.tradeapi.v1.accounts.FORTS.getDefaultInstance();
        }
        portfolioFortsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            grpc.tradeapi.v1.accounts.FORTS, grpc.tradeapi.v1.accounts.FORTS.Builder, grpc.tradeapi.v1.accounts.FORTSOrBuilder>(
                (grpc.tradeapi.v1.accounts.FORTS) portfolio_,
                getParentForChildren(),
                isClean());
        portfolio_ = null;
      }
      portfolioCase_ = 10;
      onChanged();
      return portfolioFortsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:grpc.tradeapi.v1.accounts.GetAccountResponse)
  }

  // @@protoc_insertion_point(class_scope:grpc.tradeapi.v1.accounts.GetAccountResponse)
  private static final grpc.tradeapi.v1.accounts.GetAccountResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.tradeapi.v1.accounts.GetAccountResponse();
  }

  public static grpc.tradeapi.v1.accounts.GetAccountResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetAccountResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetAccountResponse>() {
    @java.lang.Override
    public GetAccountResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetAccountResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetAccountResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.tradeapi.v1.accounts.GetAccountResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

