// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: accounts/accounts_service.proto

// Protobuf Java Version: 3.25.5
package grpc.tradeapi.v1.accounts;

/**
 * <pre>
 *
 *Общий тип для счетов Московской Биржи. Включает в себя как единые, так и специализированные (моно) счета для разных секций биржи.
 *- Единый торговый счет (ЕТС): Позволяет торговать на нескольких рынках (фондовый, валютный. срочный, spb, иностранные бумаги, иностранные фьючерсы) с единой денежной позиции.
 *- Моно-счет фондового рынка MOEX: Изолированный счет для торговли акциями, облигациями и паями.
 *- Моно-счет валютного рынка MOEX: Изолированный счет для операций с валютными парами (например, CNYRUB_TOM).
 * </pre>
 *
 * Protobuf type {@code grpc.tradeapi.v1.accounts.MC}
 */
public final class MC extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:grpc.tradeapi.v1.accounts.MC)
    MCOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MC.newBuilder() to construct.
  private MC(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MC() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MC();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.tradeapi.v1.accounts.AccountsServiceOuterClass.internal_static_grpc_tradeapi_v1_accounts_MC_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.tradeapi.v1.accounts.AccountsServiceOuterClass.internal_static_grpc_tradeapi_v1_accounts_MC_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.tradeapi.v1.accounts.MC.class, grpc.tradeapi.v1.accounts.MC.Builder.class);
  }

  private int bitField0_;
  public static final int AVAILABLE_CASH_FIELD_NUMBER = 1;
  private com.google.type.Decimal availableCash_;
  /**
   * <pre>
   * Сумма собственных денежных средств на счете, доступная для торговли. Включает маржинальные средства.
   * </pre>
   *
   * <code>.google.type.Decimal available_cash = 1;</code>
   * @return Whether the availableCash field is set.
   */
  @java.lang.Override
  public boolean hasAvailableCash() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Сумма собственных денежных средств на счете, доступная для торговли. Включает маржинальные средства.
   * </pre>
   *
   * <code>.google.type.Decimal available_cash = 1;</code>
   * @return The availableCash.
   */
  @java.lang.Override
  public com.google.type.Decimal getAvailableCash() {
    return availableCash_ == null ? com.google.type.Decimal.getDefaultInstance() : availableCash_;
  }
  /**
   * <pre>
   * Сумма собственных денежных средств на счете, доступная для торговли. Включает маржинальные средства.
   * </pre>
   *
   * <code>.google.type.Decimal available_cash = 1;</code>
   */
  @java.lang.Override
  public com.google.type.DecimalOrBuilder getAvailableCashOrBuilder() {
    return availableCash_ == null ? com.google.type.Decimal.getDefaultInstance() : availableCash_;
  }

  public static final int INITIAL_MARGIN_FIELD_NUMBER = 2;
  private com.google.type.Decimal initialMargin_;
  /**
   * <code>.google.type.Decimal initial_margin = 2;</code>
   * @return Whether the initialMargin field is set.
   */
  @java.lang.Override
  public boolean hasInitialMargin() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.google.type.Decimal initial_margin = 2;</code>
   * @return The initialMargin.
   */
  @java.lang.Override
  public com.google.type.Decimal getInitialMargin() {
    return initialMargin_ == null ? com.google.type.Decimal.getDefaultInstance() : initialMargin_;
  }
  /**
   * <code>.google.type.Decimal initial_margin = 2;</code>
   */
  @java.lang.Override
  public com.google.type.DecimalOrBuilder getInitialMarginOrBuilder() {
    return initialMargin_ == null ? com.google.type.Decimal.getDefaultInstance() : initialMargin_;
  }

  public static final int MAINTENANCE_MARGIN_FIELD_NUMBER = 3;
  private com.google.type.Decimal maintenanceMargin_;
  /**
   * <code>.google.type.Decimal maintenance_margin = 3;</code>
   * @return Whether the maintenanceMargin field is set.
   */
  @java.lang.Override
  public boolean hasMaintenanceMargin() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>.google.type.Decimal maintenance_margin = 3;</code>
   * @return The maintenanceMargin.
   */
  @java.lang.Override
  public com.google.type.Decimal getMaintenanceMargin() {
    return maintenanceMargin_ == null ? com.google.type.Decimal.getDefaultInstance() : maintenanceMargin_;
  }
  /**
   * <code>.google.type.Decimal maintenance_margin = 3;</code>
   */
  @java.lang.Override
  public com.google.type.DecimalOrBuilder getMaintenanceMarginOrBuilder() {
    return maintenanceMargin_ == null ? com.google.type.Decimal.getDefaultInstance() : maintenanceMargin_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getAvailableCash());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getInitialMargin());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(3, getMaintenanceMargin());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getAvailableCash());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getInitialMargin());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getMaintenanceMargin());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.tradeapi.v1.accounts.MC)) {
      return super.equals(obj);
    }
    grpc.tradeapi.v1.accounts.MC other = (grpc.tradeapi.v1.accounts.MC) obj;

    if (hasAvailableCash() != other.hasAvailableCash()) return false;
    if (hasAvailableCash()) {
      if (!getAvailableCash()
          .equals(other.getAvailableCash())) return false;
    }
    if (hasInitialMargin() != other.hasInitialMargin()) return false;
    if (hasInitialMargin()) {
      if (!getInitialMargin()
          .equals(other.getInitialMargin())) return false;
    }
    if (hasMaintenanceMargin() != other.hasMaintenanceMargin()) return false;
    if (hasMaintenanceMargin()) {
      if (!getMaintenanceMargin()
          .equals(other.getMaintenanceMargin())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasAvailableCash()) {
      hash = (37 * hash) + AVAILABLE_CASH_FIELD_NUMBER;
      hash = (53 * hash) + getAvailableCash().hashCode();
    }
    if (hasInitialMargin()) {
      hash = (37 * hash) + INITIAL_MARGIN_FIELD_NUMBER;
      hash = (53 * hash) + getInitialMargin().hashCode();
    }
    if (hasMaintenanceMargin()) {
      hash = (37 * hash) + MAINTENANCE_MARGIN_FIELD_NUMBER;
      hash = (53 * hash) + getMaintenanceMargin().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.tradeapi.v1.accounts.MC parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.tradeapi.v1.accounts.MC parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.tradeapi.v1.accounts.MC parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.tradeapi.v1.accounts.MC parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.tradeapi.v1.accounts.MC parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.tradeapi.v1.accounts.MC parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.tradeapi.v1.accounts.MC parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.tradeapi.v1.accounts.MC parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static grpc.tradeapi.v1.accounts.MC parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static grpc.tradeapi.v1.accounts.MC parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.tradeapi.v1.accounts.MC parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.tradeapi.v1.accounts.MC parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.tradeapi.v1.accounts.MC prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *
   *Общий тип для счетов Московской Биржи. Включает в себя как единые, так и специализированные (моно) счета для разных секций биржи.
   *- Единый торговый счет (ЕТС): Позволяет торговать на нескольких рынках (фондовый, валютный. срочный, spb, иностранные бумаги, иностранные фьючерсы) с единой денежной позиции.
   *- Моно-счет фондового рынка MOEX: Изолированный счет для торговли акциями, облигациями и паями.
   *- Моно-счет валютного рынка MOEX: Изолированный счет для операций с валютными парами (например, CNYRUB_TOM).
   * </pre>
   *
   * Protobuf type {@code grpc.tradeapi.v1.accounts.MC}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:grpc.tradeapi.v1.accounts.MC)
      grpc.tradeapi.v1.accounts.MCOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.tradeapi.v1.accounts.AccountsServiceOuterClass.internal_static_grpc_tradeapi_v1_accounts_MC_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.tradeapi.v1.accounts.AccountsServiceOuterClass.internal_static_grpc_tradeapi_v1_accounts_MC_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.tradeapi.v1.accounts.MC.class, grpc.tradeapi.v1.accounts.MC.Builder.class);
    }

    // Construct using grpc.tradeapi.v1.accounts.MC.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getAvailableCashFieldBuilder();
        getInitialMarginFieldBuilder();
        getMaintenanceMarginFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      availableCash_ = null;
      if (availableCashBuilder_ != null) {
        availableCashBuilder_.dispose();
        availableCashBuilder_ = null;
      }
      initialMargin_ = null;
      if (initialMarginBuilder_ != null) {
        initialMarginBuilder_.dispose();
        initialMarginBuilder_ = null;
      }
      maintenanceMargin_ = null;
      if (maintenanceMarginBuilder_ != null) {
        maintenanceMarginBuilder_.dispose();
        maintenanceMarginBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.tradeapi.v1.accounts.AccountsServiceOuterClass.internal_static_grpc_tradeapi_v1_accounts_MC_descriptor;
    }

    @java.lang.Override
    public grpc.tradeapi.v1.accounts.MC getDefaultInstanceForType() {
      return grpc.tradeapi.v1.accounts.MC.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.tradeapi.v1.accounts.MC build() {
      grpc.tradeapi.v1.accounts.MC result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.tradeapi.v1.accounts.MC buildPartial() {
      grpc.tradeapi.v1.accounts.MC result = new grpc.tradeapi.v1.accounts.MC(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(grpc.tradeapi.v1.accounts.MC result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.availableCash_ = availableCashBuilder_ == null
            ? availableCash_
            : availableCashBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.initialMargin_ = initialMarginBuilder_ == null
            ? initialMargin_
            : initialMarginBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.maintenanceMargin_ = maintenanceMarginBuilder_ == null
            ? maintenanceMargin_
            : maintenanceMarginBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.tradeapi.v1.accounts.MC) {
        return mergeFrom((grpc.tradeapi.v1.accounts.MC)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.tradeapi.v1.accounts.MC other) {
      if (other == grpc.tradeapi.v1.accounts.MC.getDefaultInstance()) return this;
      if (other.hasAvailableCash()) {
        mergeAvailableCash(other.getAvailableCash());
      }
      if (other.hasInitialMargin()) {
        mergeInitialMargin(other.getInitialMargin());
      }
      if (other.hasMaintenanceMargin()) {
        mergeMaintenanceMargin(other.getMaintenanceMargin());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getAvailableCashFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getInitialMarginFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getMaintenanceMarginFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.type.Decimal availableCash_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.type.Decimal, com.google.type.Decimal.Builder, com.google.type.DecimalOrBuilder> availableCashBuilder_;
    /**
     * <pre>
     * Сумма собственных денежных средств на счете, доступная для торговли. Включает маржинальные средства.
     * </pre>
     *
     * <code>.google.type.Decimal available_cash = 1;</code>
     * @return Whether the availableCash field is set.
     */
    public boolean hasAvailableCash() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Сумма собственных денежных средств на счете, доступная для торговли. Включает маржинальные средства.
     * </pre>
     *
     * <code>.google.type.Decimal available_cash = 1;</code>
     * @return The availableCash.
     */
    public com.google.type.Decimal getAvailableCash() {
      if (availableCashBuilder_ == null) {
        return availableCash_ == null ? com.google.type.Decimal.getDefaultInstance() : availableCash_;
      } else {
        return availableCashBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Сумма собственных денежных средств на счете, доступная для торговли. Включает маржинальные средства.
     * </pre>
     *
     * <code>.google.type.Decimal available_cash = 1;</code>
     */
    public Builder setAvailableCash(com.google.type.Decimal value) {
      if (availableCashBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        availableCash_ = value;
      } else {
        availableCashBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Сумма собственных денежных средств на счете, доступная для торговли. Включает маржинальные средства.
     * </pre>
     *
     * <code>.google.type.Decimal available_cash = 1;</code>
     */
    public Builder setAvailableCash(
        com.google.type.Decimal.Builder builderForValue) {
      if (availableCashBuilder_ == null) {
        availableCash_ = builderForValue.build();
      } else {
        availableCashBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Сумма собственных денежных средств на счете, доступная для торговли. Включает маржинальные средства.
     * </pre>
     *
     * <code>.google.type.Decimal available_cash = 1;</code>
     */
    public Builder mergeAvailableCash(com.google.type.Decimal value) {
      if (availableCashBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          availableCash_ != null &&
          availableCash_ != com.google.type.Decimal.getDefaultInstance()) {
          getAvailableCashBuilder().mergeFrom(value);
        } else {
          availableCash_ = value;
        }
      } else {
        availableCashBuilder_.mergeFrom(value);
      }
      if (availableCash_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Сумма собственных денежных средств на счете, доступная для торговли. Включает маржинальные средства.
     * </pre>
     *
     * <code>.google.type.Decimal available_cash = 1;</code>
     */
    public Builder clearAvailableCash() {
      bitField0_ = (bitField0_ & ~0x00000001);
      availableCash_ = null;
      if (availableCashBuilder_ != null) {
        availableCashBuilder_.dispose();
        availableCashBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Сумма собственных денежных средств на счете, доступная для торговли. Включает маржинальные средства.
     * </pre>
     *
     * <code>.google.type.Decimal available_cash = 1;</code>
     */
    public com.google.type.Decimal.Builder getAvailableCashBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getAvailableCashFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Сумма собственных денежных средств на счете, доступная для торговли. Включает маржинальные средства.
     * </pre>
     *
     * <code>.google.type.Decimal available_cash = 1;</code>
     */
    public com.google.type.DecimalOrBuilder getAvailableCashOrBuilder() {
      if (availableCashBuilder_ != null) {
        return availableCashBuilder_.getMessageOrBuilder();
      } else {
        return availableCash_ == null ?
            com.google.type.Decimal.getDefaultInstance() : availableCash_;
      }
    }
    /**
     * <pre>
     * Сумма собственных денежных средств на счете, доступная для торговли. Включает маржинальные средства.
     * </pre>
     *
     * <code>.google.type.Decimal available_cash = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.type.Decimal, com.google.type.Decimal.Builder, com.google.type.DecimalOrBuilder> 
        getAvailableCashFieldBuilder() {
      if (availableCashBuilder_ == null) {
        availableCashBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.type.Decimal, com.google.type.Decimal.Builder, com.google.type.DecimalOrBuilder>(
                getAvailableCash(),
                getParentForChildren(),
                isClean());
        availableCash_ = null;
      }
      return availableCashBuilder_;
    }

    private com.google.type.Decimal initialMargin_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.type.Decimal, com.google.type.Decimal.Builder, com.google.type.DecimalOrBuilder> initialMarginBuilder_;
    /**
     * <code>.google.type.Decimal initial_margin = 2;</code>
     * @return Whether the initialMargin field is set.
     */
    public boolean hasInitialMargin() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.google.type.Decimal initial_margin = 2;</code>
     * @return The initialMargin.
     */
    public com.google.type.Decimal getInitialMargin() {
      if (initialMarginBuilder_ == null) {
        return initialMargin_ == null ? com.google.type.Decimal.getDefaultInstance() : initialMargin_;
      } else {
        return initialMarginBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.type.Decimal initial_margin = 2;</code>
     */
    public Builder setInitialMargin(com.google.type.Decimal value) {
      if (initialMarginBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        initialMargin_ = value;
      } else {
        initialMarginBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.google.type.Decimal initial_margin = 2;</code>
     */
    public Builder setInitialMargin(
        com.google.type.Decimal.Builder builderForValue) {
      if (initialMarginBuilder_ == null) {
        initialMargin_ = builderForValue.build();
      } else {
        initialMarginBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.google.type.Decimal initial_margin = 2;</code>
     */
    public Builder mergeInitialMargin(com.google.type.Decimal value) {
      if (initialMarginBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          initialMargin_ != null &&
          initialMargin_ != com.google.type.Decimal.getDefaultInstance()) {
          getInitialMarginBuilder().mergeFrom(value);
        } else {
          initialMargin_ = value;
        }
      } else {
        initialMarginBuilder_.mergeFrom(value);
      }
      if (initialMargin_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.type.Decimal initial_margin = 2;</code>
     */
    public Builder clearInitialMargin() {
      bitField0_ = (bitField0_ & ~0x00000002);
      initialMargin_ = null;
      if (initialMarginBuilder_ != null) {
        initialMarginBuilder_.dispose();
        initialMarginBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.type.Decimal initial_margin = 2;</code>
     */
    public com.google.type.Decimal.Builder getInitialMarginBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getInitialMarginFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.type.Decimal initial_margin = 2;</code>
     */
    public com.google.type.DecimalOrBuilder getInitialMarginOrBuilder() {
      if (initialMarginBuilder_ != null) {
        return initialMarginBuilder_.getMessageOrBuilder();
      } else {
        return initialMargin_ == null ?
            com.google.type.Decimal.getDefaultInstance() : initialMargin_;
      }
    }
    /**
     * <code>.google.type.Decimal initial_margin = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.type.Decimal, com.google.type.Decimal.Builder, com.google.type.DecimalOrBuilder> 
        getInitialMarginFieldBuilder() {
      if (initialMarginBuilder_ == null) {
        initialMarginBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.type.Decimal, com.google.type.Decimal.Builder, com.google.type.DecimalOrBuilder>(
                getInitialMargin(),
                getParentForChildren(),
                isClean());
        initialMargin_ = null;
      }
      return initialMarginBuilder_;
    }

    private com.google.type.Decimal maintenanceMargin_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.type.Decimal, com.google.type.Decimal.Builder, com.google.type.DecimalOrBuilder> maintenanceMarginBuilder_;
    /**
     * <code>.google.type.Decimal maintenance_margin = 3;</code>
     * @return Whether the maintenanceMargin field is set.
     */
    public boolean hasMaintenanceMargin() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.google.type.Decimal maintenance_margin = 3;</code>
     * @return The maintenanceMargin.
     */
    public com.google.type.Decimal getMaintenanceMargin() {
      if (maintenanceMarginBuilder_ == null) {
        return maintenanceMargin_ == null ? com.google.type.Decimal.getDefaultInstance() : maintenanceMargin_;
      } else {
        return maintenanceMarginBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.type.Decimal maintenance_margin = 3;</code>
     */
    public Builder setMaintenanceMargin(com.google.type.Decimal value) {
      if (maintenanceMarginBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        maintenanceMargin_ = value;
      } else {
        maintenanceMarginBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.google.type.Decimal maintenance_margin = 3;</code>
     */
    public Builder setMaintenanceMargin(
        com.google.type.Decimal.Builder builderForValue) {
      if (maintenanceMarginBuilder_ == null) {
        maintenanceMargin_ = builderForValue.build();
      } else {
        maintenanceMarginBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.google.type.Decimal maintenance_margin = 3;</code>
     */
    public Builder mergeMaintenanceMargin(com.google.type.Decimal value) {
      if (maintenanceMarginBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          maintenanceMargin_ != null &&
          maintenanceMargin_ != com.google.type.Decimal.getDefaultInstance()) {
          getMaintenanceMarginBuilder().mergeFrom(value);
        } else {
          maintenanceMargin_ = value;
        }
      } else {
        maintenanceMarginBuilder_.mergeFrom(value);
      }
      if (maintenanceMargin_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.type.Decimal maintenance_margin = 3;</code>
     */
    public Builder clearMaintenanceMargin() {
      bitField0_ = (bitField0_ & ~0x00000004);
      maintenanceMargin_ = null;
      if (maintenanceMarginBuilder_ != null) {
        maintenanceMarginBuilder_.dispose();
        maintenanceMarginBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.type.Decimal maintenance_margin = 3;</code>
     */
    public com.google.type.Decimal.Builder getMaintenanceMarginBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getMaintenanceMarginFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.type.Decimal maintenance_margin = 3;</code>
     */
    public com.google.type.DecimalOrBuilder getMaintenanceMarginOrBuilder() {
      if (maintenanceMarginBuilder_ != null) {
        return maintenanceMarginBuilder_.getMessageOrBuilder();
      } else {
        return maintenanceMargin_ == null ?
            com.google.type.Decimal.getDefaultInstance() : maintenanceMargin_;
      }
    }
    /**
     * <code>.google.type.Decimal maintenance_margin = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.type.Decimal, com.google.type.Decimal.Builder, com.google.type.DecimalOrBuilder> 
        getMaintenanceMarginFieldBuilder() {
      if (maintenanceMarginBuilder_ == null) {
        maintenanceMarginBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.type.Decimal, com.google.type.Decimal.Builder, com.google.type.DecimalOrBuilder>(
                getMaintenanceMargin(),
                getParentForChildren(),
                isClean());
        maintenanceMargin_ = null;
      }
      return maintenanceMarginBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:grpc.tradeapi.v1.accounts.MC)
  }

  // @@protoc_insertion_point(class_scope:grpc.tradeapi.v1.accounts.MC)
  private static final grpc.tradeapi.v1.accounts.MC DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.tradeapi.v1.accounts.MC();
  }

  public static grpc.tradeapi.v1.accounts.MC getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MC>
      PARSER = new com.google.protobuf.AbstractParser<MC>() {
    @java.lang.Override
    public MC parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<MC> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MC> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.tradeapi.v1.accounts.MC getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

