// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: accounts/accounts_service.proto

// Protobuf Java Version: 3.25.5
package grpc.tradeapi.v1.accounts;

public interface PositionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.tradeapi.v1.accounts.Position)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Символ инструмента
   * </pre>
   *
   * <code>string symbol = 1;</code>
   * @return The symbol.
   */
  java.lang.String getSymbol();
  /**
   * <pre>
   * Символ инструмента
   * </pre>
   *
   * <code>string symbol = 1;</code>
   * @return The bytes for symbol.
   */
  com.google.protobuf.ByteString
      getSymbolBytes();

  /**
   * <pre>
   * Количество в шт., значение со знаком определяющее (long-short)
   * </pre>
   *
   * <code>.google.type.Decimal quantity = 2;</code>
   * @return Whether the quantity field is set.
   */
  boolean hasQuantity();
  /**
   * <pre>
   * Количество в шт., значение со знаком определяющее (long-short)
   * </pre>
   *
   * <code>.google.type.Decimal quantity = 2;</code>
   * @return The quantity.
   */
  com.google.type.Decimal getQuantity();
  /**
   * <pre>
   * Количество в шт., значение со знаком определяющее (long-short)
   * </pre>
   *
   * <code>.google.type.Decimal quantity = 2;</code>
   */
  com.google.type.DecimalOrBuilder getQuantityOrBuilder();

  /**
   * <pre>
   * Средняя цена. Не заполняется для FORTS позиций
   * </pre>
   *
   * <code>.google.type.Decimal average_price = 3;</code>
   * @return Whether the averagePrice field is set.
   */
  boolean hasAveragePrice();
  /**
   * <pre>
   * Средняя цена. Не заполняется для FORTS позиций
   * </pre>
   *
   * <code>.google.type.Decimal average_price = 3;</code>
   * @return The averagePrice.
   */
  com.google.type.Decimal getAveragePrice();
  /**
   * <pre>
   * Средняя цена. Не заполняется для FORTS позиций
   * </pre>
   *
   * <code>.google.type.Decimal average_price = 3;</code>
   */
  com.google.type.DecimalOrBuilder getAveragePriceOrBuilder();

  /**
   * <pre>
   * Текущая цена
   * </pre>
   *
   * <code>.google.type.Decimal current_price = 4;</code>
   * @return Whether the currentPrice field is set.
   */
  boolean hasCurrentPrice();
  /**
   * <pre>
   * Текущая цена
   * </pre>
   *
   * <code>.google.type.Decimal current_price = 4;</code>
   * @return The currentPrice.
   */
  com.google.type.Decimal getCurrentPrice();
  /**
   * <pre>
   * Текущая цена
   * </pre>
   *
   * <code>.google.type.Decimal current_price = 4;</code>
   */
  com.google.type.DecimalOrBuilder getCurrentPriceOrBuilder();

  /**
   * <pre>
   * Поддерживающее гарантийное обеспечение. Заполняется только для FORTS позиций
   * </pre>
   *
   * <code>.google.type.Decimal maintenance_margin = 5;</code>
   * @return Whether the maintenanceMargin field is set.
   */
  boolean hasMaintenanceMargin();
  /**
   * <pre>
   * Поддерживающее гарантийное обеспечение. Заполняется только для FORTS позиций
   * </pre>
   *
   * <code>.google.type.Decimal maintenance_margin = 5;</code>
   * @return The maintenanceMargin.
   */
  com.google.type.Decimal getMaintenanceMargin();
  /**
   * <pre>
   * Поддерживающее гарантийное обеспечение. Заполняется только для FORTS позиций
   * </pre>
   *
   * <code>.google.type.Decimal maintenance_margin = 5;</code>
   */
  com.google.type.DecimalOrBuilder getMaintenanceMarginOrBuilder();

  /**
   * <pre>
   * Прибыль за текущий день. Не заполняется для FORTS позиций
   * </pre>
   *
   * <code>.google.type.Decimal daily_pnl = 6;</code>
   * @return Whether the dailyPnl field is set.
   */
  boolean hasDailyPnl();
  /**
   * <pre>
   * Прибыль за текущий день. Не заполняется для FORTS позиций
   * </pre>
   *
   * <code>.google.type.Decimal daily_pnl = 6;</code>
   * @return The dailyPnl.
   */
  com.google.type.Decimal getDailyPnl();
  /**
   * <pre>
   * Прибыль за текущий день. Не заполняется для FORTS позиций
   * </pre>
   *
   * <code>.google.type.Decimal daily_pnl = 6;</code>
   */
  com.google.type.DecimalOrBuilder getDailyPnlOrBuilder();

  /**
   * <pre>
   * Нереализованная прибыль текущей позиции
   * </pre>
   *
   * <code>.google.type.Decimal unrealized_pnl = 7;</code>
   * @return Whether the unrealizedPnl field is set.
   */
  boolean hasUnrealizedPnl();
  /**
   * <pre>
   * Нереализованная прибыль текущей позиции
   * </pre>
   *
   * <code>.google.type.Decimal unrealized_pnl = 7;</code>
   * @return The unrealizedPnl.
   */
  com.google.type.Decimal getUnrealizedPnl();
  /**
   * <pre>
   * Нереализованная прибыль текущей позиции
   * </pre>
   *
   * <code>.google.type.Decimal unrealized_pnl = 7;</code>
   */
  com.google.type.DecimalOrBuilder getUnrealizedPnlOrBuilder();
}
